include/list.h File Reference
#include <stdlib.h>
Data Structures
struct list_iterator_t
struct list_node
struct list_t
Macros
#define LIST_FREE free
#define LIST_MALLOC malloc
#define LIST_VERSION `0.0.5`
Typedefs
typedef struct list_node list_node_t
Enumerations
enum list_direction_t { LIST_HEAD,
 LIST_TAIL
 }
Functions
 list_node_t * list_at (list_t *self, int index)
void list_destroy (list_t *self)
 list_node_t * list_find (list_t *self, void *val)
void list_iterator_destroy (list_iterator_t *self)
 list_iterator_t * list_iterator_new (list_t *list, list_direction_t direction)
 list_iterator_t * list_iterator_new_from_node (list_node_t *node, list_direction_t direction)
 list_node_t * list_iterator_next (list_iterator_t *self)
 list_node_t * list_lpop (list_t *self)
 list_node_t * list_lpush (list_t *self, list_node_t *node)
 list_t * list_new ()
 list_node_t * list_node_new (void *val)
void list_remove (list_t *self, list_node_t *node)
 list_node_t * list_rpop (list_t *self)
 list_node_t * list_rpush (list_t *self, list_node_t *node)
Macro Definition Documentation
LIST_FREE
#define LIST_FREE free
Definition at line 28 of file list.h.
Referenced by list_destroy(), list_iterator_destroy(), and list_remove().
LIST_MALLOC
#define LIST_MALLOC malloc
Definition at line 24 of file list.h.
Referenced by list_iterator_new_from_node(), list_new(), and list_node_new().
LIST_VERSION
#define LIST_VERSION `0.0.5`
Definition at line 19 of file list.h.
Typedef Documentation
list_node_t
typedef struct list_node list_node_t
Enumeration Type Documentation
list_direction_t
enum list_direction_t
Enumerator
LIST_HEAD
LIST_TAIL
Definition at line 35 of file list.h.
             {
    LIST_HEAD
  , LIST_TAIL
} list_direction_t;
Function Documentation
list_at()
 list_node_t* list_at (list_t * self, int index)
Definition at line 162 of file list.c.
References LIST_HEAD, list_iterator_destroy(), list_iterator_new(), list_iterator_next(), and LIST_TAIL.
                                              {
  list_direction_t direction = LIST_HEAD;
  if (index < 0) {
    direction = LIST_TAIL;
    index = ~index;
  }
  if ((unsigned)index < self->len) {
    list_iterator_t *it = list_iterator_new(self, direction);
    list_node_t *node = list_iterator_next(it);
    while (index--)
      node = list_iterator_next(it);
    list_iterator_destroy(it);
    return node;
  }
  return NULL;
}
list_destroy()
void list_destroy (list_t * self)
Definition at line 30 of file list.c.
References LIST_FREE, list_node::next, and list_node::val.
Referenced by deinit_routines().
                                {
  unsigned int len = self->len;
  list_node_t *next;
  list_node_t *curr = self->head;
  while (len--) {
    next = curr->next;
    if (self->free)
      self->free(curr->val);
    LIST_FREE(curr);
    curr = next;
  }
  LIST_FREE(self);
}
list_find()
 list_node_t* list_find (list_t * self, void * val)
Definition at line 136 of file list.c.
References LIST_HEAD, list_iterator_destroy(), list_iterator_new(), list_iterator_next(), and list_node::val.
                                                {
  list_iterator_t *it = list_iterator_new(self, LIST_HEAD);
  list_node_t *node;
  while ((node = list_iterator_next(it))) {
    if (self->match) {
      if (self->match(val, node->val)) {
        list_iterator_destroy(it);
        return node;
      }
    } else {
      if (val == node->val) {
        list_iterator_destroy(it);
        return node;
      }
    }
  }
  list_iterator_destroy(it);
  return NULL;
}
list_iterator_destroy()
void list_iterator_destroy (list_iterator_t * self)
Definition at line 52 of file list_iterator.c.
References LIST_FREE.
Referenced by list_at(), list_find(), and routine_task().
                                                  {
  LIST_FREE(self);
  self = NULL;
}
list_iterator_new()
 list_iterator_t* list_iterator_new (list_t * list, list_direction_t direction)
Definition at line 15 of file list_iterator.c.
References list_t::head, LIST_HEAD, list_iterator_new_from_node(), and list_t::tail.
Referenced by list_at(), list_find(), and routine_task().
                                                                             {
  list_node_t *node = direction == LIST_HEAD ? list->head : list->tail;
  return list_iterator_new_from_node(node, direction);
}
list_iterator_new_from_node()
 list_iterator_t* list_iterator_new_from_node (list_node_t * node, list_direction_t direction)
Definition at line 25 of file list_iterator.c.
References LIST_MALLOC, and list_iterator_t::next.
Referenced by list_iterator_new().
                                                                         {
  list_iterator_t *self;
  if (!(self = LIST_MALLOC(sizeof(list_iterator_t))))
    return NULL;
  self->next = node;
  self->direction = direction;
  return self;
}
list_iterator_next()
 list_node_t* list_iterator_next (list_iterator_t * self)
Definition at line 40 of file list_iterator.c.
References LIST_HEAD, list_node::next, and list_node::prev.
Referenced by list_at(), list_find(), and routine_task().
                                                       {
  list_node_t *curr = self->next;
  if (curr) {
    self->next = self->direction == LIST_HEAD ? curr->next : curr->prev;
  }
  return curr;
}
list_lpop()
 list_node_t* list_lpop (list_t * self)
Definition at line 93 of file list.c.
References list_node::next, and list_node::prev.
                                     {
  if (!self->len)
    return NULL;
  list_node_t *node = self->head;
  if (--self->len) {
    (self->head = node->next)->prev = NULL;
  } else {
    self->head = self->tail = NULL;
  }
  node->next = node->prev = NULL;
  return node;
}
list_lpush()
 list_node_t* list_lpush (list_t * self, list_node_t * node)
Definition at line 114 of file list.c.
References list_node::next, and list_node::prev.
                                                         {
  if (!node)
    return NULL;
  if (self->len) {
    node->next = self->head;
    node->prev = NULL;
    self->head->prev = node;
    self->head = node;
  } else {
    self->head = self->tail = node;
    node->prev = node->next = NULL;
  }
  ++self->len;
  return node;
}
list_new()
 list_t* list_new ()
Definition at line 14 of file list.c.
References list_t::head, and LIST_MALLOC.
Referenced by init_routine().
                   {
  list_t *self;
  if (!(self = LIST_MALLOC(sizeof(list_t))))
    return NULL;
  self->head = NULL;
  self->tail = NULL;
  self->free = NULL;
  self->match = NULL;
  self->len = 0;
  return self;
}
list_node_new()
 list_node_t* list_node_new (void * val)
Definition at line 14 of file list_node.c.
References LIST_MALLOC, list_node::next, list_node::prev, and list_node::val.
Referenced by register_routine().
                                      {
  list_node_t *self;
  if (!(self = LIST_MALLOC(sizeof(list_node_t))))
    return NULL;
  self->prev = NULL;
  self->next = NULL;
  self->val = val;
  return self;
}
list_remove()
void list_remove (list_t * self, list_node_t * node)
Definition at line 186 of file list.c.
References LIST_FREE, list_node::next, list_node::prev, and list_node::val.
                                                  {
  node->prev ? (node->prev->next = node->next) : (self->head = node->next);
  node->next ? (node->next->prev = node->prev) : (self->tail = node->prev);
  if (self->free)
    self->free(node->val);
  LIST_FREE(node);
  --self->len;
}
list_rpop()
 list_node_t* list_rpop (list_t * self)
Definition at line 73 of file list.c.
References list_node::next, and list_node::prev.
                                     {
  if (!self->len)
    return NULL;
  list_node_t *node = self->tail;
  if (--self->len) {
    (self->tail = node->prev)->next = NULL;
  } else {
    self->tail = self->head = NULL;
  }
  node->next = node->prev = NULL;
  return node;
}
list_rpush()
 list_node_t* list_rpush (list_t * self, list_node_t * node)
Definition at line 51 of file list.c.
References list_node::next, and list_node::prev.
Referenced by register_routine().
                                                         {
  if (!node)
    return NULL;
  if (self->len) {
    node->prev = self->tail;
    node->next = NULL;
    self->tail->next = node;
    self->tail = node;
  } else {
    self->head = self->tail = node;
    node->prev = node->next = NULL;
  }
  ++self->len;
  return node;
}