src/claw.c File Reference
#include `claw.h`
#include `log.h`
#include `toggle.h`
Functions
void close_claw ()
Drives the motors to close the claw.
void open_claw ()
Drives the motors to open the claw.
void set_claw_motor (const int v)
sets the claw motor speed
void update_claw ()
Updates the claw motor values.
Variables
static enum claw_state state = CLAW_NEUTRAL_STATE
Function Documentation
close_claw()
void close_claw ()
Drives the motors to close the claw.
Author
Chris Jerrett
Definition at line 44 of file claw.c.
References CLAW_MOTOR, MIN_CLAW_SPEED, and set_motor_immediate().
Referenced by autonomous().
{ set_motor_immediate(CLAW_MOTOR, MIN_CLAW_SPEED); }
open_claw()
void open_claw ()
Drives the motors to open the claw.
Author
Chris Jerrett
Definition at line 38 of file claw.c.
References CLAW_MOTOR, MAX_CLAW_SPEED, and set_motor_immediate().
Referenced by autonomous().
{ set_motor_immediate(CLAW_MOTOR, MAX_CLAW_SPEED); }
set_claw_motor()
void set_claw_motor (const int v)
sets the claw motor speed
Author
Chris Jerrett
Definition at line 32 of file claw.c.
References CLAW_MOTOR, and set_motor_immediate().
Referenced by autonomous(), and update_claw().
{ set_motor_immediate(CLAW_MOTOR, v); }
update_claw()
void update_claw ()
Updates the claw motor values.
Author
Chris Jerrett
Definition at line 10 of file claw.c.
References CLAW_CLOSE, CLAW_CLOSE_STATE, CLAW_NEUTRAL_STATE, CLAW_OPEN, CLAW_OPEN_STATE, MAX_CLAW_SPEED, MIN_CLAW_SPEED, set_claw_motor(), and state.
Referenced by operatorControl().
                   {
  if (joystickGetDigital(CLAW_CLOSE)) {
    state = CLAW_CLOSE_STATE;
  } else if (joystickGetDigital(CLAW_OPEN)) {
    state = CLAW_OPEN_STATE;
  } else {
    state = CLAW_NEUTRAL_STATE;
  }
  if (state == CLAW_CLOSE_STATE) {
    set_claw_motor(MAX_CLAW_SPEED);
  } else if (state == CLAW_OPEN_STATE) {
    set_claw_motor(MIN_CLAW_SPEED);
  } else {
    set_claw_motor(0);
  }
}
Variable Documentation
state
enum claw_state state = CLAW_NEUTRAL_STATE [static]
Definition at line 4 of file claw.c.
Referenced by update_claw().