include/mobile_goal_intake.h File Reference
#include `controller.h`
#include `motor_ports.h`
#include `slew.h`
Functions
void lower_intake ()
lowers the intake
void raise_intake ()
raises the intake
void set_intake_motor (int n)
sets the intake motor
void update_intake ()
updates the mobile goal intake in teleop.
Function Documentation
lower_intake()
void lower_intake ()
lowers the intake
Definition at line 7 of file mobile_goal_intake.c.
References set_intake_motor().
Referenced by autonomous(), and update_intake().
{ set_intake_motor(-100); }
raise_intake()
void raise_intake ()
raises the intake
Definition at line 9 of file mobile_goal_intake.c.
References set_intake_motor().
Referenced by autonomous(), and update_intake().
{ set_intake_motor(100); }
set_intake_motor()
void set_intake_motor (int n)
sets the intake motor
Author
Chris Jerrett
Definition at line 5 of file mobile_goal_intake.c.
References INTAKE_MOTOR, and set_motor_immediate().
Referenced by autonomous(), lower_intake(), raise_intake(), and update_intake().
{ set_motor_immediate(INTAKE_MOTOR, n); }
update_intake()
void update_intake ()
updates the mobile goal intake in teleop.
Author
Chris Jerrett
Definition at line 14 of file mobile_goal_intake.c.
References lower_intake(), MASTER, raise_intake(), and set_intake_motor().
Referenced by operatorControl().
                     {
  if (joystickGetDigital(MASTER, 7, JOY_UP)) {
    raise_intake();
  } else if (joystickGetDigital(MASTER, 7, JOY_DOWN)) {
    lower_intake();
  } else
    set_intake_motor(0);
}