include/localization.h File Reference
Declarations and macros for determining the location of the robot. [WIP].
#include `encoders.h`
#include `matrix.h`
#include <API.h>
#include <math.h>
Data Structures
struct location
Vector storing the cartesian cords and an angle.
Macros
#define LOCALIZATION_UPDATE_FREQUENCY 0.500
How often the localization code updates the position.
Functions
int calculate_encoder_angle ()
struct location get_position ()
Gets the current posituion of the robot.
bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)
Starts the localization process.
void update_position ()
Updates the position from the localization.
Detailed Description
Declarations and macros for determining the location of the robot. [WIP].
Author
Chris Jerrett, Christian Desimone
Date
9/27/2017
Definition in file localization.h.
Macro Definition Documentation
LOCALIZATION_UPDATE_FREQUENCY
#define LOCALIZATION_UPDATE_FREQUENCY 0.500
How often the localization code updates the position.
Definition at line 19 of file localization.h.
Referenced by calculate_gryo_anglular_velocity(), init_localization(), and integrate_gyro_w().
Function Documentation
calculate_encoder_angle()
int calculate_encoder_angle ()
Definition at line 101 of file localization.c.
References CPR, get_encoder_ticks(), and WIDTH.
Referenced by autonomous().
                              {
#define WIDTH 13.5
#define CPR 392.0
#define WHEEL_RADIUS 2
  int dist_r = get_encoder_ticks(0) / CPR;
  int dist_l = get_encoder_ticks(1) / CPR;
  return ((dist_r - dist_l) / WIDTH);
}
get_position()
struct location get_position ()
Gets the current posituion of the robot.
Parameters
gyro1 The first gyro
Returns
the loacation of the robot as a struct.
Definition at line 32 of file localization.c.
{}
init_localization()
bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)
Starts the localization process.
Author
Chris Jerrett
Parameters
gyro1 The first gyro The multiplier parameter can tune the gyro to adapt to specific sensors. The default value at this time is 196; higher values will increase the number of degrees reported for a fixed actual rotation, while lower values will decrease the number of degrees reported. If your robot is consistently turning too far, increase the multiplier, and if it is not turning far enough, decrease the multiplier.
Definition at line 123 of file localization.c.
References g1, last_call, localization_task, LOCALIZATION_UPDATE_FREQUENCY, makeMatrix(), and update_position().
                                                                  {
  g1 = gyroInit(gyro1, multiplier);
  // init state matrix
  // one dimensional vector with x, y, theta, acceleration in x and y
  state_matrix = makeMatrix(1, 5);
  localization_task =
      taskRunLoop(update_position, LOCALIZATION_UPDATE_FREQUENCY * 1000);
  last_call = millis();
  return true;
}
update_position()
void update_position ()
Updates the position from the localization.
Author
Chris Jerrett
Definition at line 39 of file localization.c.
References calculate_accelerometer_odemetry(), and last_call.
Referenced by init_localization().
                       {
  // int curr_theta = calculate_angle();
  struct accelerometer_odometry oddem = calculate_accelerometer_odemetry();
  // printf("x: %d y: %d T: %d\n", a.x, a.y, 0);
  /*int l = 1;
  int vr = get_encoder_velocity(1);
  int vl = get_encoder_velocity(2);
  int theta_dot = (vr - vl) / l;
  int curr_theta = theta + theta_dot;
  double dt = LOCALIZATION_UPDATE_FREQUENCY;
  double v_tot = (vr+vl)/2.0;
  int x_curr = x - v_tot*dt*sin(curr_theta);
  int y_curr = y + v_tot*dt*cos(curr_theta);
  x = x_curr;
  y = y_curr;*/
  last_call = millis();
}