src/routines.c File Reference
#include `routines.h`
#include `controller.h`
#include `list.h`
#include `log.h`
#include `toggle.h`
#include <API.h>
Functions
void deinit_routines ()
void init_routine ()
void register_routine (void(*routine)(), button_t on_buttons, button_t *prohibited_buttons)
void routine_task ()
Variables
static list_t * routine_list
static TaskHandle routine_task_var
Function Documentation
deinit_routines()
void deinit_routines ()
Definition at line 33 of file routines.c.
References list_destroy().
{ list_destroy(routine_list); }
init_routine()
void init_routine ()
Definition at line 28 of file routines.c.
References list_new(), routine_task(), and routine_task_var.
Referenced by operatorControl().
                    {
  routine_list = list_new();
  routine_task_var = taskRunLoop(routine_task, 20);
}
register_routine()
void register_routine (void(*)() routine, button_t on_buttons, button_t * prohibited_buttons)
Definition at line 35 of file routines.c.
References routine_t::blocked_buttons, list_node_new(), list_rpush(), routine_t::on_button, routine_t::routine, and list_node::val.
                                                    {
  struct routine_t *r = (struct routine_t *)malloc(sizeof(routine_t));
  r->blocked_buttons = prohibited_buttons;
  r->routine = routine;
  r->on_button = on_buttons;
  list_node_t *node = list_node_new(r);
  node->val = r;
  list_rpush(routine_list, node);
}
routine_task()
void routine_task ()
Definition at line 12 of file routines.c.
References buttonIsNewPress(), LIST_HEAD, list_iterator_destroy(), list_iterator_new(), list_iterator_next(), routine_t::on_button, routine_t::routine, and list_node::val.
Referenced by init_routine().
                    {
  list_node_t *node;
  list_iterator_t *it = list_iterator_new(routine_list, LIST_HEAD);
  if (it != NULL) {
    while (node = list_iterator_next(it)) {
      if (node->val != NULL) {
        routine_t *routine = (routine_t *)(node->val);
        if (buttonIsNewPress(routine->on_button)) {
          routine->routine();
        }
      }
    }
  }
  list_iterator_destroy(it);
}
Variable Documentation
routine_list
 list_t* routine_list [static]
Definition at line 8 of file routines.c.
routine_task_var
TaskHandle routine_task_var [static]
Definition at line 10 of file routines.c.
Referenced by init_routine().