src/localization.c File Reference
#include `localization.h`
#include `vmath.h`
#include <inttypes.h>
Data Structures
struct accelerometer_odometry
struct encoder_odemtry
Macros
#define CPR 392.0
#define CPR 392.0
#define WHEEL_RADIUS 2
#define WHEEL_RADIUS 2
#define WIDTH 13.5
#define WIDTH 13.5
Functions
static struct accelerometer_odometry calculate_accelerometer_odemetry ()
static double calculate_angle ()
int calculate_encoder_angle ()
static void calculate_encoder_odemetry ()
static double calculate_gryo_anglular_velocity ()
struct location get_position ()
Gets the current posituion of the robot.
bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)
Starts the localization process.
static double integrate_gyro_w (int new_w)
void update_position ()
Updates the position from the localization.
Variables
static Gyro g1
static int last_call = 0
static TaskHandle localization_task
 matrix * state_matrix
Macro Definition Documentation
CPR [1/2]
#define CPR 392.0
Referenced by calculate_encoder_angle(), and calculate_encoder_odemetry().
CPR [2/2]
#define CPR 392.0
WHEEL_RADIUS [1/2]
#define WHEEL_RADIUS 2
WHEEL_RADIUS [2/2]
#define WHEEL_RADIUS 2
WIDTH [1/2]
#define WIDTH 13.5
Referenced by calculate_encoder_angle(), and calculate_encoder_odemetry().
WIDTH [2/2]
#define WIDTH 13.5
Function Documentation
calculate_accelerometer_odemetry()
static struct accelerometer_odometry calculate_accelerometer_odemetry () [static]
Definition at line 59 of file localization.c.
References last_call.
Referenced by update_position().
                                                                        {
  static double vel_acumm_x = 0;
  static double vel_acumm_y = 0;
  int32_t accel_x_rel = (int32_t)analogReadCalibratedHR(2);
  int32_t accel_y_rel = (int32_t)analogReadCalibratedHR(3);
  // Ignore atom format string errors
  printf("x: %+" PRId32 " y: %+" PRId32 "\n", accel_x_rel, accel_y_rel);
  double delta_time = ((millis() - last_call) / 1000.0);
  // double accel_x_abs = (accel_x_rel * cos(theta) + accel_y_rel * sin(theta))
  // * delta_time; double accel_y_abs = (accel_y_rel * cos(theta) +
  // accel_x_rel
  // * sin(theta)) * delta_time;
  // vel_acumm_x += accel_x_abs;
  // vel_acumm_y += accel_y_abs;
  // double new_x = x + vel_acumm_x * delta_time;
  // double new_y = y + vel_acumm_y * delta_time;
  struct accelerometer_odometry od;
  // od.x = new_x;
  // od.y = new_y;
  return od;
}
calculate_angle()
static double calculate_angle () [static]
calculate_encoder_angle()
int calculate_encoder_angle ()
Definition at line 101 of file localization.c.
References CPR, get_encoder_ticks(), and WIDTH.
Referenced by autonomous().
                              {
#define WIDTH 13.5
#define CPR 392.0
#define WHEEL_RADIUS 2
  int dist_r = get_encoder_ticks(0) / CPR;
  int dist_l = get_encoder_ticks(1) / CPR;
  return ((dist_r - dist_l) / WIDTH);
}
calculate_encoder_odemetry()
static void calculate_encoder_odemetry () [static]
Definition at line 110 of file localization.c.
References CPR, get_encoder_ticks(), M_PI, encoder_odemtry::theta, and WIDTH.
                                         {
#define WIDTH 13.5
#define CPR 392.0
#define WHEEL_RADIUS 2
  int dist_r = get_encoder_ticks(0) / CPR;
  int dist_l = get_encoder_ticks(1) / CPR;
  printf("dist_r: %d dist_l: %d\n", dist_r, dist_l);
  int theta = (dist_l - dist_r) / WIDTH;
  printf("theta: %d\n", theta);
  int arc_length = ((M_PI * theta) * (WIDTH * WIDTH) / (8));
}
calculate_gryo_anglular_velocity()
static double calculate_gryo_anglular_velocity () [static]
Definition at line 93 of file localization.c.
References g1, and LOCALIZATION_UPDATE_FREQUENCY.
                                                 {
  static int last_gyro = 0;
  int current = gyroGet(g1);
  // Calculate w (angluar velocity in degrees per second)
  double w = (current - last_gyro) / (LOCALIZATION_UPDATE_FREQUENCY / 1000.0);
  return w;
}
get_position()
struct location get_position ()
Gets the current posituion of the robot.
Parameters
gyro1 The first gyro
Returns
the loacation of the robot as a struct.
Definition at line 32 of file localization.c.
{}
init_localization()
bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)
Starts the localization process.
Author
Chris Jerrett
Parameters
gyro1 The first gyro The multiplier parameter can tune the gyro to adapt to specific sensors. The default value at this time is 196; higher values will increase the number of degrees reported for a fixed actual rotation, while lower values will decrease the number of degrees reported. If your robot is consistently turning too far, increase the multiplier, and if it is not turning far enough, decrease the multiplier.
Definition at line 123 of file localization.c.
References g1, last_call, localization_task, LOCALIZATION_UPDATE_FREQUENCY, makeMatrix(), and update_position().
                                                                  {
  g1 = gyroInit(gyro1, multiplier);
  // init state matrix
  // one dimensional vector with x, y, theta, acceleration in x and y
  state_matrix = makeMatrix(1, 5);
  localization_task =
      taskRunLoop(update_position, LOCALIZATION_UPDATE_FREQUENCY * 1000);
  last_call = millis();
  return true;
}
integrate_gyro_w()
static double integrate_gyro_w (int new_w) [static]
Definition at line 87 of file localization.c.
References LOCALIZATION_UPDATE_FREQUENCY, and encoder_odemtry::theta.
                                          {
  static double theta = 0;
  double delta_theta = new_w * LOCALIZATION_UPDATE_FREQUENCY;
  theta += delta_theta;
}
update_position()
void update_position ()
Updates the position from the localization.
Author
Chris Jerrett
Definition at line 39 of file localization.c.
References calculate_accelerometer_odemetry(), and last_call.
Referenced by init_localization().
                       {
  // int curr_theta = calculate_angle();
  struct accelerometer_odometry oddem = calculate_accelerometer_odemetry();
  // printf("x: %d y: %d T: %d\n", a.x, a.y, 0);
  /*int l = 1;
  int vr = get_encoder_velocity(1);
  int vl = get_encoder_velocity(2);
  int theta_dot = (vr - vl) / l;
  int curr_theta = theta + theta_dot;
  double dt = LOCALIZATION_UPDATE_FREQUENCY;
  double v_tot = (vr+vl)/2.0;
  int x_curr = x - v_tot*dt*sin(curr_theta);
  int y_curr = y + v_tot*dt*cos(curr_theta);
  x = x_curr;
  y = y_curr;*/
  last_call = millis();
}
Variable Documentation
g1
Gyro g1 [static]
Definition at line 5 of file localization.c.
Referenced by calculate_gryo_anglular_velocity(), and init_localization().
last_call
int last_call = 0 [static]
Definition at line 8 of file localization.c.
Referenced by calculate_accelerometer_odemetry(), init_localization(), and update_position().
localization_task
TaskHandle localization_task [static]
Definition at line 6 of file localization.c.
Referenced by init_localization().
state_matrix
 matrix* state_matrix
Definition at line 10 of file localization.c.