src/list_iterator.c File Reference
#include `list.h`
Functions
void list_iterator_destroy (list_iterator_t *self)
 list_iterator_t * list_iterator_new (list_t *list, list_direction_t direction)
 list_iterator_t * list_iterator_new_from_node (list_node_t *node, list_direction_t direction)
 list_node_t * list_iterator_next (list_iterator_t *self)
Function Documentation
list_iterator_destroy()
void list_iterator_destroy (list_iterator_t * self)
Definition at line 52 of file list_iterator.c.
References LIST_FREE.
Referenced by list_at(), list_find(), and routine_task().
                                                  {
  LIST_FREE(self);
  self = NULL;
}
list_iterator_new()
 list_iterator_t* list_iterator_new (list_t * list, list_direction_t direction)
Definition at line 15 of file list_iterator.c.
References list_t::head, LIST_HEAD, list_iterator_new_from_node(), and list_t::tail.
Referenced by list_at(), list_find(), and routine_task().
                                                                             {
  list_node_t *node = direction == LIST_HEAD ? list->head : list->tail;
  return list_iterator_new_from_node(node, direction);
}
list_iterator_new_from_node()
 list_iterator_t* list_iterator_new_from_node (list_node_t * node, list_direction_t direction)
Definition at line 25 of file list_iterator.c.
References LIST_MALLOC, and list_iterator_t::next.
Referenced by list_iterator_new().
                                                                         {
  list_iterator_t *self;
  if (!(self = LIST_MALLOC(sizeof(list_iterator_t))))
    return NULL;
  self->next = node;
  self->direction = direction;
  return self;
}
list_iterator_next()
 list_node_t* list_iterator_next (list_iterator_t * self)
Definition at line 40 of file list_iterator.c.
References LIST_HEAD, list_node::next, and list_node::prev.
Referenced by list_at(), list_find(), and routine_task().
                                                       {
  list_node_t *curr = self->next;
  if (curr) {
    self->next = self->direction == LIST_HEAD ? curr->next : curr->prev;
  }
  return curr;
}