src/lifter.c File Reference
#include `lifter.h`
#include `log.h`
Functions
void autostack_routine ()
double getLifterHeight ()
Gets the height of the lifter in inches.
int getLifterTicks ()
Gets the value of the lifter pot.
float lifterPotentiometerToDegree (int x)
height of the lifter in degrees from 0 height
void lower_main_lifter ()
Lowers the main lifter.
void lower_secondary_lifter ()
Lowers the secondary lifter.
static void main_lifter_update ()
void raise_main_lifter ()
Raises the main lifter.
void raise_secondary_lifter ()
Raises the main lifter.
static void secondary_lifter_update ()
void set_lifter_pos (int pos)
Sets the lifter positions to the given value.
void set_main_lifter_motors (const int v)
Sets the main lifter motors to the given value.
void set_secondary_lifter_motors (const int v)
Sets the secondary lifter motors to the given value.
void update_lifter ()
Updates the lifter in teleop.
Variables
static bool lifter_autostack_routine_interupt = false
static bool lifter_autostack_running = false
Ultrasonic lifter_ultrasonic
static bool secondary_override = false
Function Documentation
autostack_routine()
void autostack_routine ()
Definition at line 9 of file lifter.c.
References lifter_ultrasonic, raise_main_lifter(), and set_main_lifter_motors().
                         {
  int instruction_couter = 0;
  bool routine_complete = false;
  while (true) {
    if (instruction_couter == 0) {
      int dist = ultrasonicGet(lifter_ultrasonic);
      if (dist > 11 || dist == -ULTRA_BAD_RESPONSE) {
        raise_main_lifter();
      } else {
        set_main_lifter_motors(0);
        instruction_couter = 1;
      }
    }
  }
}
getLifterHeight()
double getLifterHeight ()
Gets the height of the lifter in inches.
Returns
the height of the lifter.
Author
Chris Jerrett
Date
9/17/2017
Definition at line 216 of file lifter.c.
References getLifterTicks().
                         {
  unsigned int ticks = getLifterTicks();
  return (-2 * pow(10, (-9 * ticks)) + 6 * (pow(10, (-6 * ticks * ticks))) +
          0.0198 * ticks + 2.3033);
}
getLifterTicks()
int getLifterTicks ()
Gets the value of the lifter pot.
Returns
the value of the pot.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 207 of file lifter.c.
References LIFTER.
Referenced by getLifterHeight().
{ return analogRead(LIFTER); }
lifterPotentiometerToDegree()
float lifterPotentiometerToDegree (int x)
height of the lifter in degrees from 0 height
Parameters
x the pot value
Returns
the positions in degrees
Author
Chris Jerrett
Date
10/13/2017
Definition at line 196 of file lifter.c.
References DEG_MAX, INIT_ROTATION, and TICK_MAX.
                                         {
  return (x - INIT_ROTATION) / TICK_MAX * DEG_MAX;
}
lower_main_lifter()
void lower_main_lifter ()
Lowers the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 70 of file lifter.c.
References MAX_SPEED, and set_main_lifter_motors().
{ set_main_lifter_motors(MAX_SPEED); }
lower_secondary_lifter()
void lower_secondary_lifter ()
Lowers the secondary lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 86 of file lifter.c.
References MAX_SPEED, and set_secondary_lifter_motors().
{ set_secondary_lifter_motors(MAX_SPEED); }
main_lifter_update()
static void main_lifter_update () [static]
Definition at line 90 of file lifter.c.
References lifter_autostack_running, LIFTER_DOWN, lifter_ultrasonic, LIFTER_UP, MAIN_LIFTER_POT, MAX_SPEED, MIN_SPEED, secondary_override, and set_main_lifter_motors().
Referenced by update_lifter().
                                 {
  if (lifter_autostack_running)
    return;
  static int count = 0;
  static bool pid_on = false;
  static int main_target = 0;
  int main_motor_speed = 0;
  static long long main_i = 0;
  if (count == 20) {
    main_target = analogRead(MAIN_LIFTER_POT);
  }
  if (pid_on && count > 20) {
    int curr = analogRead(MAIN_LIFTER_POT);
    static int main_last_p = 0;
    int main_p = curr - main_target;
    main_i += main_p;
    int main_d = main_last_p - main_p;
    // main_motor_speed = MAIN_LIFTER_P * main_p + MAIN_LIFTER_I * main_i +
    // MAIN_LIFTER_D * main_d;
    main_last_p = main_p;
  } else {
    main_i = 0;
    count++;
  }
  if (joystickGetDigital(LIFTER_UP)) {
    int ultra = ultrasonicGet(lifter_ultrasonic);
    main_motor_speed = MAX_SPEED;
    count = 0;
  } else if (joystickGetDigital(LIFTER_DOWN)) {
    main_motor_speed = MIN_SPEED;
    count = 0;
    secondary_override = false;
  } else {
    secondary_override = false;
  }
  set_main_lifter_motors(main_motor_speed);
  pid_on = true;
}
raise_main_lifter()
void raise_main_lifter ()
Raises the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 62 of file lifter.c.
References MAX_SPEED, and set_main_lifter_motors().
Referenced by autostack_routine().
{ set_main_lifter_motors(MAX_SPEED); }
raise_secondary_lifter()
void raise_secondary_lifter ()
Raises the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 78 of file lifter.c.
References MIN_SPEED, and set_secondary_lifter_motors().
{ set_secondary_lifter_motors(MIN_SPEED / 1.5); }
secondary_lifter_update()
static void secondary_lifter_update () [static]
Definition at line 130 of file lifter.c.
References lifter_autostack_running, MAX_SPEED, MIN_SPEED, SECONDARY_LIFTER_D, SECONDARY_LIFTER_DOWN, SECONDARY_LIFTER_I, SECONDARY_LIFTER_P, SECONDARY_LIFTER_POT_PORT, SECONDARY_LIFTER_UP, and set_secondary_lifter_motors().
Referenced by update_lifter().
                                      {
  if (lifter_autostack_running)
    return;
  static int count = 0;
  // static bool pid_on = false;
  static int second_target = 0;
  int second_motor_speed = 0;
  static long long second_i = 0;
  if (count < 10) {
    second_target = analogRead(SECONDARY_LIFTER_POT_PORT);
    count++;
  }
  int curr = analogRead(SECONDARY_LIFTER_POT_PORT);
  static int second_last_p = 0;
  int second_p = curr - second_target;
  second_i += second_p;
  int second_d = second_last_p - second_p;
  second_motor_speed = SECONDARY_LIFTER_P * second_p +
                       SECONDARY_LIFTER_I * second_i +
                       SECONDARY_LIFTER_D * second_d;
  second_last_p = second_p;
  if (joystickGetDigital(SECONDARY_LIFTER_DOWN)) {
    second_motor_speed = MAX_SPEED;
    count = 0;
    second_i = 0;
    second_target = analogRead(SECONDARY_LIFTER_POT_PORT);
  } else if (joystickGetDigital(SECONDARY_LIFTER_UP)) {
    second_motor_speed = MIN_SPEED;
    count = 0;
    second_i = 0;
    second_target =
        second_target > 3000 ? 4095 : analogRead(SECONDARY_LIFTER_POT_PORT);
    ;
  } else {
    second_target = second_target > 3000 ? 4095 : second_target;
  }
  second_motor_speed = abs(second_motor_speed) < 20 ? 0 : second_motor_speed;
  /*printf("Motor %d \n", second_motor_speed);
  printf("P %d \n", second_p);
  printf("I %lld \n", second_i);
  printf("D %d \n", second_d);*/
  set_secondary_lifter_motors(second_motor_speed);
}
set_lifter_pos()
void set_lifter_pos (int pos)
Sets the lifter positions to the given value.
Parameters
pos The height in inches
Author
Chris Jerrett
Date
9/12/2017
Definition at line 54 of file lifter.c.
{}
set_main_lifter_motors()
void set_main_lifter_motors (const int v)
Sets the main lifter motors to the given value.
Parameters
v value for the lifter motor. Between -128 - 127, any values outside are clamped.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 45 of file lifter.c.
References MOTOR_LIFT, and set_motor_slew().
Referenced by autonomous(), autostack_routine(), lower_main_lifter(), main_lifter_update(), and raise_main_lifter().
{ set_motor_slew(MOTOR_LIFT, v); }
set_secondary_lifter_motors()
void set_secondary_lifter_motors (const int v)
Sets the secondary lifter motors to the given value.
Parameters
v value for the lifter motor. Between -128 - 127, any values outside are clamped.
Author
Chris Jerrett
Date
1/6/2018
Definition at line 33 of file lifter.c.
References MOTOR_SECONDARY_LIFTER, and set_motor_immediate().
Referenced by autonomous(), lower_secondary_lifter(), raise_secondary_lifter(), and secondary_lifter_update().
                                              {
  set_motor_immediate(MOTOR_SECONDARY_LIFTER, v);
}
update_lifter()
void update_lifter ()
Updates the lifter in teleop.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 183 of file lifter.c.
References main_lifter_update(), secondary_lifter_update(), and secondary_override.
Referenced by operatorControl().
                     {
  main_lifter_update();
  if (!secondary_override)
    secondary_lifter_update();
}
Variable Documentation
lifter_autostack_routine_interupt
bool lifter_autostack_routine_interupt = false [static]
Definition at line 7 of file lifter.c.
lifter_autostack_running
bool lifter_autostack_running = false [static]
Definition at line 6 of file lifter.c.
Referenced by main_lifter_update(), and secondary_lifter_update().
lifter_ultrasonic
Ultrasonic lifter_ultrasonic
Definition at line 4 of file lifter.c.
Referenced by autostack_routine(), initialize(), and main_lifter_update().
secondary_override
bool secondary_override = false [static]
Definition at line 88 of file lifter.c.
Referenced by main_lifter_update(), and update_lifter().