src/battery.c File Reference
#include `battery.h`
#include <API.h>
Functions
double backup_battery_voltage ()
gets the backup battery voltage
bool battery_level_acceptable ()
returns if the batteries are acceptable
double main_battery_voltage ()
gets the main battery voltage
Function Documentation
backup_battery_voltage()
double backup_battery_voltage ()
gets the backup battery voltage
Author
Chris Jerrett
Definition at line 8 of file battery.c.
References powerLevelBackup().
Referenced by battery_level_acceptable().
                                {
  return powerLevelBackup() / 1000.0;
}
battery_level_acceptable()
bool battery_level_acceptable ()
returns if the batteries are acceptable
See also
MIN_MAIN_VOLTAGE
MIN_BACKUP_VOLTAGE
Author
Chris Jerrett
Definition at line 12 of file battery.c.
References backup_battery_voltage(), main_battery_voltage(), MIN_BACKUP_VOLTAGE, and MIN_MAIN_VOLTAGE.
                                {
  if(main_battery_voltage() < MIN_MAIN_VOLTAGE) return false;
  if(backup_battery_voltage() < MIN_BACKUP_VOLTAGE) return false;
  return true;
}
main_battery_voltage()
double main_battery_voltage ()
gets the main battery voltage
Author
Chris Jerrett
Definition at line 4 of file battery.c.
References powerLevelMain().
Referenced by battery_level_acceptable().
                              {
  return powerLevelMain() / 1000.0;
}