include/battery.h File Reference
Battery management related functions.
#include <API.h>
Macros
#define MIN_BACKUP_VOLTAGE 7.8
The minimum acceptable backup battery voltage beofre a match.
#define MIN_MAIN_VOLTAGE 7.8
The minimum acceptable main battery voltage beofre a match.
Functions
double backup_battery_voltage ()
gets the backup battery voltage
bool battery_level_acceptable ()
returns if the batteries are acceptable
double main_battery_voltage ()
gets the main battery voltage
Detailed Description
Battery management related functions.
Author
Chris Jerrett
Date
9/18/2017
Definition in file battery.h.
Macro Definition Documentation
MIN_BACKUP_VOLTAGE
#define MIN_BACKUP_VOLTAGE 7.8
The minimum acceptable backup battery voltage beofre a match.
Definition at line 20 of file battery.h.
Referenced by battery_level_acceptable().
MIN_MAIN_VOLTAGE
#define MIN_MAIN_VOLTAGE 7.8
The minimum acceptable main battery voltage beofre a match.
Definition at line 15 of file battery.h.
Referenced by battery_level_acceptable().
Function Documentation
backup_battery_voltage()
double backup_battery_voltage ()
gets the backup battery voltage
Author
Chris Jerrett
Definition at line 17 of file battery.c.
Referenced by battery_level_acceptable().
                                {
  return powerLevelBackup() / 1000.0;
}
battery_level_acceptable()
bool battery_level_acceptable ()
returns if the batteries are acceptable
See also
MIN_MAIN_VOLTAGE
MIN_BACKUP_VOLTAGE
Author
Chris Jerrett
Definition at line 28 of file battery.c.
References backup_battery_voltage(), main_battery_voltage(), MIN_BACKUP_VOLTAGE, and MIN_MAIN_VOLTAGE.
                                {
  if(main_battery_voltage() < MIN_MAIN_VOLTAGE) return false;
  if(backup_battery_voltage() < MIN_BACKUP_VOLTAGE) return false;
  return true;
}
main_battery_voltage()
double main_battery_voltage ()
gets the main battery voltage
Author
Chris Jerrett
Definition at line 9 of file battery.c.
Referenced by battery_level_acceptable().
                              {
  return powerLevelMain() / 1000.0;
}