src/claw.c File Reference
#include `claw.h`
Functions
void close_claw ()
Drives the motors to close the claw.
unsigned int getClawTicks ()
Gets the claw position in potentiometer ticks.
void open_claw ()
Drives the motors to open the claw.
void set_claw_motor (const int v)
sets the claw motor speed
void update_claw ()
Updates the claw motor values.
Function Documentation
close_claw()
void close_claw ()
Drives the motors to close the claw.
Author
Chris Jerrett
Definition at line 67 of file claw.c.
References CLAW_MOTOR, MIN_CLAW_SPEED, and set_motor_immediate().
Referenced by autonomous().
                  {
  set_motor_immediate(CLAW_MOTOR, MIN_CLAW_SPEED);
}
getClawTicks()
unsigned int getClawTicks ()
Gets the claw position in potentiometer ticks.
Author
Chris Jerrett
Definition at line 51 of file claw.c.
References analogRead(), and CLAW_POT.
Referenced by update_claw().
                           {
  return analogRead(CLAW_POT);
}
open_claw()
void open_claw ()
Drives the motors to open the claw.
Author
Chris Jerrett
Definition at line 59 of file claw.c.
References CLAW_MOTOR, MAX_CLAW_SPEED, and set_motor_immediate().
Referenced by autonomous().
                 {
  set_motor_immediate(CLAW_MOTOR, MAX_CLAW_SPEED);
}
set_claw_motor()
void set_claw_motor (const int v)
sets the claw motor speed
Author
Chris Jerrett
Definition at line 43 of file claw.c.
References CLAW_MOTOR, and set_motor_immediate().
Referenced by update_claw().
                                {
  set_motor_immediate(CLAW_MOTOR, v);
}
update_claw()
void update_claw ()
Updates the claw motor values.
Author
Chris Jerrett
Definition at line 7 of file claw.c.
References CLAW_CLOSE, CLAW_CLOSE_STATE, CLAW_CLOSE_VAL, CLAW_D, CLAW_OPEN, CLAW_OPEN_STATE, CLAW_OPEN_VAL, CLAW_P, getClawTicks(), joystickGetDigital(), and set_claw_motor().
Referenced by operatorControl().
                   {
  //Set the Error used in calculating d
  static int last_error = 0;
  //Set the initial claw state to open
  static enum claw_state state = CLAW_OPEN_STATE;
  //Listen for input and either close or open the claw
  if(joystickGetDigital(CLAW_CLOSE)){
    state = CLAW_CLOSE_STATE;
  }
  else if(joystickGetDigital(CLAW_OPEN)){
    state = CLAW_OPEN_STATE;
  } else {
    //set the default motor speed
    int p = 0;
    //Change the base speed to the difference between the target
    // and the current value
    if(state == CLAW_OPEN_STATE) {
      p = getClawTicks() - CLAW_OPEN_VAL;
    } else {
      p = getClawTicks() - CLAW_CLOSE_VAL;
    }
    //Set the d value to the difference between the current p and the last p
    int d = (p - last_error);
    //Set last error for use the next time the function is run
    last_error = p;
    //Construct the final motor speed value
    int motor = CLAW_P * p + CLAW_D * d;
    //Set the motor speed
    set_claw_motor(motor);
  }
}