include/claw.h File Reference
Code for controlling the claw that grabs the cones.
#include `slew.h`
#include <API.h>
#include `controller.h`
#include `motor_ports.h`
#include `sensor_ports.h`
Macros
#define CLAW_CLOSE MASTER, 6, JOY_UP
The joystick parameters for closing the claw.
#define CLAW_CLOSE_VAL 3000
The potentiometer value for a closed claw.
#define CLAW_D .1
The derivative constant for the claw PID controller.
#define CLAW_I 0
The integral constant for the claw PID controller.
#define CLAW_OPEN MASTER, 6, JOY_DOWN
The joystick parameters for opening the claw.
#define CLAW_OPEN_VAL 1500
The potentiometer value for a open claw.
#define CLAW_P .1
The proportional constant for the claw PID controller.
#define MAX_CLAW_SPEED 50
The max motor vlaue of the claw.
#define MIN_CLAW_SPEED -50
The min motor vlaue of the claw.
Enumerations
enum claw_state { CLAW_OPEN_STATE,
 CLAW_CLOSE_STATE
 }
The different states of the claw.
Functions
void close_claw ()
Drives the motors to close the claw.
unsigned int getClawTicks ()
Gets the claw position in potentiometer ticks.
void open_claw ()
Drives the motors to open the claw.
void set_claw_motor (const int v)
sets the claw motor speed
void update_claw ()
Updates the claw motor values.
Detailed Description
Code for controlling the claw that grabs the cones.
Author
Chris Jerrett, Christian Desimone
Date
8/30/2017
Definition in file claw.h.
Macro Definition Documentation
CLAW_CLOSE
#define CLAW_CLOSE MASTER, 6, JOY_UP
The joystick parameters for closing the claw.
Author
Chris Jerrett
Definition at line 47 of file claw.h.
Referenced by update_claw().
CLAW_CLOSE_VAL
#define CLAW_CLOSE_VAL 3000
The potentiometer value for a closed claw.
Author
Chris Jerrett
Definition at line 59 of file claw.h.
Referenced by update_claw().
CLAW_D
#define CLAW_D .1
The derivative constant for the claw PID controller.
Author
Chris Jerrett
Definition at line 25 of file claw.h.
Referenced by update_claw().
CLAW_I
#define CLAW_I 0
The integral constant for the claw PID controller.
Author
Chris Jerrett
Definition at line 30 of file claw.h.
CLAW_OPEN
#define CLAW_OPEN MASTER, 6, JOY_DOWN
The joystick parameters for opening the claw.
Author
Chris Jerrett
Definition at line 53 of file claw.h.
Referenced by update_claw().
CLAW_OPEN_VAL
#define CLAW_OPEN_VAL 1500
The potentiometer value for a open claw.
Author
Chris Jerrett
Definition at line 65 of file claw.h.
Referenced by update_claw().
CLAW_P
#define CLAW_P .1
The proportional constant for the claw PID controller.
Author
Chris Jerrett
Definition at line 20 of file claw.h.
Referenced by update_claw().
MAX_CLAW_SPEED
#define MAX_CLAW_SPEED 50
The max motor vlaue of the claw.
Author
Chris Jerrett
Definition at line 36 of file claw.h.
Referenced by open_claw().
MIN_CLAW_SPEED
#define MIN_CLAW_SPEED -50
The min motor vlaue of the claw.
Author
Chris Jerrett
Definition at line 41 of file claw.h.
Referenced by close_claw().
Enumeration Type Documentation
claw_state
enum claw_state
The different states of the claw.
Author
Chris Jerrett
Enumerator
CLAW_OPEN_STATE
CLAW_CLOSE_STATE
Definition at line 101 of file claw.h.
                {
  CLAW_OPEN_STATE,
  CLAW_CLOSE_STATE
};
Function Documentation
close_claw()
void close_claw ()
Drives the motors to close the claw.
Author
Chris Jerrett
Definition at line 67 of file claw.c.
References CLAW_MOTOR, MIN_CLAW_SPEED, and set_motor_immediate().
Referenced by autonomous().
                  {
  set_motor_immediate(CLAW_MOTOR, MIN_CLAW_SPEED);
}
getClawTicks()
unsigned int getClawTicks ()
Gets the claw position in potentiometer ticks.
Author
Chris Jerrett
Definition at line 51 of file claw.c.
References CLAW_POT.
Referenced by update_claw().
                           {
  return analogRead(CLAW_POT);
}
open_claw()
void open_claw ()
Drives the motors to open the claw.
Author
Chris Jerrett
Definition at line 59 of file claw.c.
References CLAW_MOTOR, MAX_CLAW_SPEED, and set_motor_immediate().
Referenced by autonomous().
                 {
  set_motor_immediate(CLAW_MOTOR, MAX_CLAW_SPEED);
}
set_claw_motor()
void set_claw_motor (const int v)
sets the claw motor speed
Author
Chris Jerrett
Definition at line 43 of file claw.c.
References CLAW_MOTOR, and set_motor_immediate().
Referenced by update_claw().
                                {
  set_motor_immediate(CLAW_MOTOR, v);
}
update_claw()
void update_claw ()
Updates the claw motor values.
Author
Chris Jerrett
Definition at line 7 of file claw.c.
References CLAW_CLOSE, CLAW_CLOSE_STATE, CLAW_CLOSE_VAL, CLAW_D, CLAW_OPEN, CLAW_OPEN_STATE, CLAW_OPEN_VAL, CLAW_P, getClawTicks(), and set_claw_motor().
Referenced by operatorControl().
                   {
  //Set the Error used in calculating d
  static int last_error = 0;
  //Set the initial claw state to open
  static enum claw_state state = CLAW_OPEN_STATE;
  //Listen for input and either close or open the claw
  if(joystickGetDigital(CLAW_CLOSE)){
    state = CLAW_CLOSE_STATE;
  }
  else if(joystickGetDigital(CLAW_OPEN)){
    state = CLAW_OPEN_STATE;
  } else {
    //set the default motor speed
    int p = 0;
    //Change the base speed to the difference between the target
    // and the current value
    if(state == CLAW_OPEN_STATE) {
      p = getClawTicks() - CLAW_OPEN_VAL;
    } else {
      p = getClawTicks() - CLAW_CLOSE_VAL;
    }
    //Set the d value to the difference between the current p and the last p
    int d = (p - last_error);
    //Set last error for use the next time the function is run
    last_error = p;
    //Construct the final motor speed value
    int motor = CLAW_P * p + CLAW_D * d;
    //Set the motor speed
    set_claw_motor(motor);
  }
}