src/drive.c File Reference
#include `drive.h`
#include `motor_ports.h`
#include `vmath.h`
#include `controller.h`
#include `slew.h`
#include <API.h>
#include `log.h`
Functions
int getThresh ()
Gets the deadzone threshhold on the drive.
static float joystickExp (int joystickVal)
Applies exponential scale to a joystick value.
void set_side_speed (side_t side, int speed)
sets the speed of one side of the robot.
void setThresh (int t)
Sets the deadzone threshhold on the drive.
void update_drive_motors ()
Updates the drive motors during teleop.
Variables
static int thresh = 30
Function Documentation
getThresh()
int getThresh ()
Gets the deadzone threshhold on the drive.
Author
Christian Desimone
Definition at line 17 of file drive.c.
References thresh.
               {
  return thresh;
}
joystickExp()
static float joystickExp (int joystickVal) [static]
Applies exponential scale to a joystick value.
Author
Christian DeSimone, Chris Jerrett
Parameters
joystickVal the analog value from the joystick
Date
9/21/2017
Definition at line 87 of file drive.c.
References THRESHOLD.
                                          {
    //make the offset negative if moving backwards
    if (abs(joystickVal) < THRESHOLD) {
            return 0;
    }
    int offset;
  //Use the threshold to ensure the joystick values are significant
    if (joystickVal < 0) {
        offset = - (THRESHOLD);
    } else {
        offset = THRESHOLD;
    }
  //Apply the function ((((x/10)^3)/18) + offset) * 0.8 to the joystick value
    return (pow(joystickVal/10 , 3) / 18 + offset) * 0.8;
}
set_side_speed()
void set_side_speed (side_t side, int speed)
sets the speed of one side of the robot.
Author
Christian Desimone
Parameters
side a side enum which indicates the size.
speed the speed of the side. Can range from -127 - 127 negative being back and positive forwards
Definition at line 68 of file drive.c.
References BOTH, LEFT, MOTOR_BACK_LEFT, MOTOR_BACK_RIGHT, MOTOR_FRONT_LEFT, MOTOR_FRONT_RIGHT, MOTOR_MIDDLE_LEFT, MOTOR_MIDDLE_RIGHT, RIGHT, and set_motor_slew().
Referenced by autonomous(), and update_drive_motors().
                                           {
  if(side == RIGHT || side == BOTH){
    set_motor_slew(MOTOR_BACK_RIGHT , -speed);
    set_motor_slew(MOTOR_FRONT_RIGHT, -speed);
    set_motor_slew(MOTOR_MIDDLE_RIGHT, -speed);
  }
  if(side == LEFT || side == BOTH){
    set_motor_slew(MOTOR_BACK_LEFT, speed);
    set_motor_slew(MOTOR_MIDDLE_LEFT, speed);
    set_motor_slew(MOTOR_FRONT_LEFT, speed);
  }
}
setThresh()
void setThresh (int t)
Sets the deadzone threshhold on the drive.
Author
Christian Desimone
Definition at line 25 of file drive.c.
References thresh.
                     {
  thresh = t;
}
update_drive_motors()
void update_drive_motors ()
Updates the drive motors during teleop.
Author
Christian Desimone
Date
9/5/17
Definition at line 34 of file drive.c.
References get_mode(), LEFT, MASTER, PARTNER, PARTNER_CONTROLLER_MODE, RIGHT, set_side_speed(), thresh, cord::x, and cord::y.
Referenced by operatorControl().
                          {
  //Get the joystick values from the controller
  int x = 0;
  int y = 0;
  if(get_mode() == PARTNER_CONTROLLER_MODE) {
    x = (joystickGetAnalog(PARTNER, 3));
    y = (joystickGetAnalog(PARTNER, 1));
  } else {
    x = -(joystickGetAnalog(MASTER, 3));
    y = (joystickGetAnalog(MASTER, 1));
  }
  //Make sure the joystick values are significant enough to change the motors
  if(x < thresh && x > -thresh){
    x = 0;
  }
  if(y < thresh && y > -thresh){
    y = 0;
  }
  //Create motor values for the left and right from the x and y of the joystick
  int r = (x + y);
  int l = -(x - y);
  //Set the drive motors
  set_side_speed(LEFT, l);
  set_side_speed(RIGHT, -r);
}
Variable Documentation
thresh
int thresh = 30 [static]
Definition at line 10 of file drive.c.
Referenced by getThresh(), setThresh(), and update_drive_motors().