include/drive.h File Reference
Drive base definitions and enumerations.
#include <API.h>
#include `partner.h`
Macros
#define THRESHOLD 10
The dead spot on the controller to avoid running motors at low speeds.
Typedefs
typedef enum side side_t
enumeration indication side of the robot.
Enumerations
enum side { LEFT,
 BOTH,
 RIGHT
 }
enumeration indication side of the robot.
Functions
void set_side_speed (side_t side, int speed)
sets the speed of one side of the robot.
void setThresh (int t)
Sets the deadzone threshhold on the drive.
void update_drive_motors ()
Updates the drive motors during teleop.
Detailed Description
Drive base definitions and enumerations.
Author
Chris Jerrett
Date
9/9/2017
Definition in file drive.h.
Macro Definition Documentation
THRESHOLD
#define THRESHOLD 10
The dead spot on the controller to avoid running motors at low speeds.
Definition at line 18 of file drive.h.
Referenced by joystickExp().
Typedef Documentation
side_t
typedef enum side side_t
enumeration indication side of the robot.
Author
Christian Desimone
Date
9/7/2017 Side can be right, both of left. Contained in side typedef, so enum is unnecessary.
Enumeration Type Documentation
side
enum side
enumeration indication side of the robot.
Author
Christian Desimone
Date
9/7/2017 Side can be right, both of left. Contained in side typedef, so enum is unnecessary.
Enumerator
LEFT
BOTH
RIGHT
Definition at line 26 of file drive.h.
                 {
  LEFT,
  BOTH,
  RIGHT
} side_t;
Function Documentation
set_side_speed()
void set_side_speed (side_t side, int speed)
sets the speed of one side of the robot.
Author
Christian Desimone
Parameters
side a side enum which indicates the size.
speed the speed of the side. Can range from -127 - 127 negative being back and positive forwards
Definition at line 68 of file drive.c.
References BOTH, LEFT, MOTOR_BACK_LEFT, MOTOR_BACK_RIGHT, MOTOR_FRONT_LEFT, MOTOR_FRONT_RIGHT, MOTOR_MIDDLE_LEFT, MOTOR_MIDDLE_RIGHT, RIGHT, and set_motor_slew().
Referenced by autonomous(), and update_drive_motors().
                                           {
  if(side == RIGHT || side == BOTH){
    set_motor_slew(MOTOR_BACK_RIGHT , -speed);
    set_motor_slew(MOTOR_FRONT_RIGHT, -speed);
    set_motor_slew(MOTOR_MIDDLE_RIGHT, -speed);
  }
  if(side == LEFT || side == BOTH){
    set_motor_slew(MOTOR_BACK_LEFT, speed);
    set_motor_slew(MOTOR_MIDDLE_LEFT, speed);
    set_motor_slew(MOTOR_FRONT_LEFT, speed);
  }
}
setThresh()
void setThresh (int t)
Sets the deadzone threshhold on the drive.
Author
Chris Jerrett
Christian Desimone
Definition at line 25 of file drive.c.
References thresh.
                     {
  thresh = t;
}
update_drive_motors()
void update_drive_motors ()
Updates the drive motors during teleop.
Author
Christian Desimone
Date
9/5/17
Definition at line 34 of file drive.c.
References get_mode(), LEFT, MASTER, PARTNER, PARTNER_CONTROLLER_MODE, RIGHT, set_side_speed(), thresh, cord::x, and cord::y.
Referenced by operatorControl().
                          {
  //Get the joystick values from the controller
  int x = 0;
  int y = 0;
  if(get_mode() == PARTNER_CONTROLLER_MODE) {
    x = (joystickGetAnalog(PARTNER, 3));
    y = (joystickGetAnalog(PARTNER, 1));
  } else {
    x = -(joystickGetAnalog(MASTER, 3));
    y = (joystickGetAnalog(MASTER, 1));
  }
  //Make sure the joystick values are significant enough to change the motors
  if(x < thresh && x > -thresh){
    x = 0;
  }
  if(y < thresh && y > -thresh){
    y = 0;
  }
  //Create motor values for the left and right from the x and y of the joystick
  int r = (x + y);
  int l = -(x - y);
  //Set the drive motors
  set_side_speed(LEFT, l);
  set_side_speed(RIGHT, -r);
}