src/encoders.c File Reference
#include `encoders.h`
#include <API.h>
Functions
int get_encoder_ticks (unsigned char address)
Gets the encoder ticks since last reset.
int get_encoder_velocity (unsigned char address)
Gets the encoder reads.
bool init_encoders ()
Initializes all motor encoders.
Function Documentation
get_encoder_ticks()
int get_encoder_ticks (unsigned char address)
Gets the encoder ticks since last reset.
Author
Chris Jerrett
Date
9/15/2017
Definition at line 12 of file encoders.c.
References imeGet().
                                             {
  int i = 0;
  imeGet(address, &i);
  return i;
}
get_encoder_velocity()
int get_encoder_velocity (unsigned char address)
Gets the encoder reads.
Author
Chris Jerrett
Date
9/15/2017
Definition at line 18 of file encoders.c.
References imeGetVelocity().
                                                {
  int i = 0;
  imeGetVelocity(address, &i);
  return i;
}
init_encoders()
bool init_encoders ()
Initializes all motor encoders.
Author
Chris Jerrett
Date
9/9/2017
See also
IME_NUMBER
Definition at line 4 of file encoders.c.
References IME_NUMBER, and imeInitializeAll().
                     {
  #ifdef IME_NUMBER
  return imeInitializeAll() == IME_NUMBER;
  #else
  return imeInitializeAll();
  #endif
}