include/encoders.h File Reference
wrapper around encoder functions
#include <API.h>
Macros
#define IME_NUMBER 6
The number of IMEs. This number is compared against the number detect in init_encoders.
Functions
int get_encoder_ticks (unsigned char address)
Gets the encoder ticks since last reset.
int get_encoder_velocity (unsigned char address)
Gets the encoder reads.
bool init_encoders ()
Initializes all motor encoders.
Detailed Description
wrapper around encoder functions
Author
Chris Jerrett, Christian Desimone
Date
9/9/2017
Definition in file encoders.h.
Macro Definition Documentation
IME_NUMBER
#define IME_NUMBER 6
The number of IMEs. This number is compared against the number detect in init_encoders.
See also
init_encoders()
Author
Chris Jerrett
Date
9/9/2017
See also
IME_NUMBER
Definition at line 20 of file encoders.h.
Referenced by init_encoders().
Function Documentation
get_encoder_ticks()
int get_encoder_ticks (unsigned char address)
Gets the encoder ticks since last reset.
Author
Chris Jerrett
Date
9/15/2017
Definition at line 23 of file encoders.c.
References imeGet().
                                             {
  int i = 0;
  imeGet(address, &i);
  return i;
}
get_encoder_velocity()
int get_encoder_velocity (unsigned char address)
Gets the encoder reads.
Author
Chris Jerrett
Date
9/15/2017
Definition at line 34 of file encoders.c.
References imeGetVelocity().
                                                {
  int i = 0;
  imeGetVelocity(address, &i);
  return i;
}
init_encoders()
bool init_encoders ()
Initializes all motor encoders.
Author
Chris Jerrett
Date
9/9/2017
See also
IME_NUMBER
Definition at line 10 of file encoders.c.
References IME_NUMBER, and imeInitializeAll().
                     {
  #ifdef IME_NUMBER
  return imeInitializeAll() == IME_NUMBER;
  #else
  return imeInitializeAll();
  #endif
}