src/init.c File Reference
File for initialization code.
Functions
void initialize ()
Runs user initialization code.
void initializeIO ()
Runs pre-initialization code.
Variables
 Ultrasonic lifter_ultrasonic
Detailed Description
File for initialization code.
This file should contain the user initialize() function and any functions related to it.
Any copyright is dedicated to the Public Domain. http://creativecommons.org/publicdomain/zero/1.0/
PROS contains FreeRTOS (http://www.freertos.org) whose source code may be obtained from http://sourceforge.net/projects/freertos/files/ or on request.
Definition in file init.c.
Function Documentation
initialize()
void initialize ()
Runs user initialization code.
This function will be started in its own task with the default priority and stack size once when the robot is starting up. It is possible that the VEXnet communication link may not be fully established at this time, so reading from the VEX Joystick may fail.
This function should initialize most sensors (gyro, encoders, ultrasonics), LCDs, global variables, and IMEs.
This function must exit relatively promptly, or the operatorControl() and autonomous() tasks will not start. An autonomous mode selection menu like the pre_auton() in other environments can be implemented in this task if desired.
Definition at line 52 of file init.c.
References battery_level_acceptable(), error(), info(), init_encoders(), init_error(), init_main_lcd(), init_menu_var(), lifter_ultrasonic, setTeamName(), STRING_TYPE, and ultrasonicInit().
                  {
  init_main_lcd(uart1);
  info("LCD Init");
  if (!battery_level_acceptable())
    error("Bad main/backup bat");
  menu_t *t =
      init_menu_var(STRING_TYPE, "TEST Menu", 5, "1", "2", "3", "4", "5");
  init_error(true, uart2);
  setTeamName("9228A");
  init_encoders();
  lifter_ultrasonic = ultrasonicInit(4, 5);
}
initializeIO()
void initializeIO ()
Runs pre-initialization code.
This function will be started in kernel mode one time while the VEX Cortex is starting up. As the scheduler is still paused, most API functions will fail.
The purpose of this function is solely to set the default pin modes (pinMode()) and port states (digitalWrite()) of limit switches, push buttons, and solenoids. It can also safely configure a UART port (usartOpen()) but cannot set up an LCD (lcdInit()).
Definition at line 36 of file init.c.
References watchdogInit().
{ watchdogInit(); }
Variable Documentation
lifter_ultrasonic
 Ultrasonic lifter_ultrasonic
Definition at line 24 of file sensors.h.
Referenced by autostack_routine(), initialize(), and main_lifter_update().