include/lcd.h File Reference
LCD wrapper functions and macros.
#include <API.h>
Data Structures
struct lcd_buttons
represents the state of the lcd buttons
Macros
#define BOTTOM_ROW 2
The bottom row on the lcd screen.
#define TOP_ROW 1
The top row on the lcd screen.
Enumerations
enum button_state { RELEASED = false,
 PRESSED = true
 }
Represents the state of a button.
Functions
void init_main_lcd (FILE *lcd)
Initializes the lcd screen. Also will initialize the lcd_port var. Must be called before any lcd function can be called.
void lcd_clear ()
Clears the lcd.
 lcd_buttons lcd_get_pressed_buttons ()
Returns the pressed buttons.
void lcd_print (unsigned int line, const char *str)
prints a string to a line on the lcd
void lcd_printf (unsigned int line, const char *format_str,...)
prints a formated string to a line on the lcd. Smilar to printf
void lcd_set_backlight (bool state)
sets the backlight of the lcd
void promt_confirmation (const char *confirm_text)
Prompts the user to confirm a string. User must press middle button to confirm. Function is not thread safe and will stall a thread.
Detailed Description
LCD wrapper functions and macros.
Author
Chris Jerrett
Date
9/9/2017
Definition in file lcd.h.
Macro Definition Documentation
BOTTOM_ROW
#define BOTTOM_ROW 2
The bottom row on the lcd screen.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 25 of file lcd.h.
Referenced by log_info().
TOP_ROW
#define TOP_ROW 1
The top row on the lcd screen.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 18 of file lcd.h.
Referenced by display_menu(), and log_info().
Enumeration Type Documentation
button_state
enum button_state
Represents the state of a button.
A button can be pressed of RELEASED. Release is false which is also 0. PRESSED is true or 1.
Author
Chris Jerrett
Date
9/9/2017
Enumerator
RELEASED A released button
PRESSED A pressed button
Definition at line 36 of file lcd.h.
             {
  RELEASED = false,
  PRESSED = true,
} button_state;
Function Documentation
init_main_lcd()
void init_main_lcd (FILE * lcd)
Initializes the lcd screen. Also will initialize the lcd_port var. Must be called before any lcd function can be called.
Parameters
lcd the urart port of the lcd screen
See also
uart1
uart2
Author
Chris Jerrett
Date
9/9/2017
Definition at line 60 of file lcd.c.
References lcd_port, lcdClear(), and lcdInit().
                              {
  lcdInit(lcd);
  lcdClear(lcd);
  lcd_port = lcd;
}
lcd_clear()
void lcd_clear ()
Clears the lcd.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 46 of file lcd.c.
References lcd_assert(), lcd_port, and lcdClear().
                 {
  lcd_assert();
  lcdClear(lcd_port);
}
lcd_get_pressed_buttons()
 lcd_buttons lcd_get_pressed_buttons ()
Returns the pressed buttons.
Returns
a struct containing the states of all three buttons.
Author
Chris Jerrett
Date
9/9/2017
See also
lcd_buttons
Definition at line 27 of file lcd.c.
References lcd_assert(), lcd_port, lcdReadButtons(), lcd_buttons::left, lcd_buttons::middle, PRESSED, RELEASED, and lcd_buttons::right.
Referenced by display_menu(), and promt_confirmation().
                                     {
  lcd_assert();
  unsigned int btn_binary = lcdReadButtons(lcd_port);
  bool left = btn_binary & 0x1;//0001
  bool middle = btn_binary & 0x2;//0010
  bool right = btn_binary & 0x4;//0100
  lcd_buttons btns;
  btns.left = left ? PRESSED : RELEASED;
  btns.middle = middle ? PRESSED : RELEASED;
  btns.right = right ? PRESSED : RELEASED;
  return btns;
}
lcd_print()
void lcd_print (unsigned int line, const char * str)
prints a string to a line on the lcd
Parameters
line the line to print on
str string to print
Author
Chris Jerrett
Date
9/9/2017
Definition at line 73 of file lcd.c.
References lcd_assert(), lcd_port, and lcdSetText().
Referenced by display_menu(), and promt_confirmation().
                                                   {
  lcd_assert();
  lcdSetText(lcd_port, line, str);
}
lcd_printf()
void lcd_printf (unsigned int line, const char * format_str, ...)
prints a formated string to a line on the lcd. Smilar to printf
Parameters
line the line to print on
format_str format string string to print
Author
Chris Jerrett
Date
9/9/2017
Definition at line 85 of file lcd.c.
References lcd_assert(), and lcd_port.
                                                                {
  lcd_assert();
  lcdPrint(lcd_port, line, format_str);
}
lcd_set_backlight()
void lcd_set_backlight (bool state)
sets the backlight of the lcd
Parameters
state a boolean representing the state of the backlight. true = on, false = off.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 96 of file lcd.c.
References lcd_assert(), lcd_port, and lcdSetBacklight().
                                   {
  lcd_assert();
  lcdSetBacklight(lcd_port, state);
}
promt_confirmation()
void promt_confirmation (const char * confirm_text)
Prompts the user to confirm a string. User must press middle button to confirm. Function is not thread safe and will stall a thread.
Parameters
confirm_text the text for the user to confirm.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 110 of file lcd.c.
References delay(), lcd_assert(), lcd_get_pressed_buttons(), lcd_print(), and PRESSED.
                                                  {
  lcd_assert();
  lcd_print(1, confirm_text);
  while(lcd_get_pressed_buttons().middle != PRESSED){
    delay(200);
  }
}