src/lcd.c File Reference
#include `lcd.h`
Functions
void init_main_lcd (FILE *lcd)
Initializes the lcd screen. Also will initialize the lcd_port var. Must be called before any lcd function can be called.
static void lcd_assert ()
Asserts the lcd is initialized Works by checking is the File *lcd_port is the default NULL value and thus not set.
void lcd_clear ()
Clears the lcd.
lcd_buttons lcd_get_pressed_buttons ()
Returns the pressed buttons.
void lcd_print (unsigned int line, const char *str)
prints a string to a line on the lcd
void lcd_printf (unsigned int line, const char *format_str,...)
prints a formated string to a line on the lcd. Smilar to printf
void lcd_set_backlight (bool state)
sets the backlight of the lcd
void promt_confirmation (const char *confirm_text)
Prompts the user to confirm a string. User must press middle button to confirm. Function is not thread safe and will stall a thread.
Variables
static FILE * lcd_port = NULL
Function Documentation
init_main_lcd()
void init_main_lcd (FILE * lcd)
Initializes the lcd screen. Also will initialize the lcd_port var. Must be called before any lcd function can be called.
Parameters
lcd the urart port of the lcd screen
See also
uart1
uart2
Author
Chris Jerrett
Date
9/9/2017
Definition at line 39 of file lcd.c.
References lcd_port.
Referenced by initialize().
                              {
  lcdInit(lcd);
  lcd_port = lcd;
}
lcd_assert()
static void lcd_assert () [static]
Asserts the lcd is initialized Works by checking is the File *lcd_port is the default NULL value and thus not set.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 13 of file lcd.c.
References lcd_port.
Referenced by lcd_clear(), lcd_get_pressed_buttons(), lcd_print(), lcd_printf(), lcd_set_backlight(), and promt_confirmation().
                          {
  if(lcd_port != NULL) {
    printf("LCD NULL!");
    exit(1);
  }
}
lcd_clear()
void lcd_clear ()
Clears the lcd.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 34 of file lcd.c.
References lcd_assert(), and lcd_port.
                 {
  lcd_assert();
  lcdClear(lcd_port);
}
lcd_get_pressed_buttons()
lcd_buttons lcd_get_pressed_buttons ()
Returns the pressed buttons.
Returns
a struct containing the states of all three buttons.
Author
Chris Jerrett
Date
9/9/2017
See also
lcd_buttons
Definition at line 20 of file lcd.c.
References lcd_assert(), lcd_port, lcd_buttons::left, lcd_buttons::middle, PRESSED, RELEASED, and lcd_buttons::right.
Referenced by display_menu(), and promt_confirmation().
                                     {
  lcd_assert();
  unsigned int btn_binary = lcdReadButtons(lcd_port);
  bool left = btn_binary & 0x1;
  bool middle = btn_binary & 0x2;
  bool right = btn_binary & 0x4;
  lcd_buttons btns;
  btns.left = left ? PRESSED : RELEASED;
  btns.middle = middle ? PRESSED : RELEASED;
  btns.right = right ? PRESSED : RELEASED;
  return btns;
}
lcd_print()
void lcd_print (unsigned int line, const char * str)
prints a string to a line on the lcd
Parameters
line the line to print on
str string to print
Author
Chris Jerrett
Date
9/9/2017
Definition at line 44 of file lcd.c.
References lcd_assert(), and lcd_port.
Referenced by display_menu(), and promt_confirmation().
                                                    {
  lcd_assert();
  lcdSetText(lcd_port, line, str);
}
lcd_printf()
void lcd_printf (unsigned int line, const char * format_str, ...)
prints a formated string to a line on the lcd. Smilar to printf
Parameters
line the line to print on
format_str format string string to print
Author
Chris Jerrett
Date
9/9/2017
Definition at line 49 of file lcd.c.
References lcd_assert(), and lcd_port.
                                                                 {
  lcd_assert();
  lcdPrint(lcd_port, line, format_str);
}
lcd_set_backlight()
void lcd_set_backlight (bool state)
sets the backlight of the lcd
Parameters
state a boolean representing the state of the backlight. true = on, false = off.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 54 of file lcd.c.
References lcd_assert(), and lcd_port.
                                    {
  lcd_assert();
  lcdSetBacklight(lcd_port, state);
}
promt_confirmation()
void promt_confirmation (const char * confirm_text)
Prompts the user to confirm a string. User must press middle button to confirm. Function is not thread safe and will stall a thread.
Parameters
confirm_text the text for the user to confirm.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 59 of file lcd.c.
References lcd_assert(), lcd_get_pressed_buttons(), lcd_print(), and PRESSED.
Referenced by initialize().
                                                  {
  lcd_assert();
  lcd_print(1, confirm_text);
  while(lcd_get_pressed_buttons().middle != PRESSED){
    delay(200);
  }
}
Variable Documentation
lcd_port
FILE* lcd_port = NULL [static]
The port of the initialized lcd
Definition at line 4 of file lcd.c.
Referenced by init_main_lcd(), lcd_assert(), lcd_clear(), lcd_get_pressed_buttons(), lcd_print(), lcd_printf(), and lcd_set_backlight().