src/lifter.c File Reference
Functions
void autostack_routine (void *param)
Autostacks a cone once picked up.
double getLifterHeight ()
Gets the height of the lifter in inches.
int getLifterTicks ()
Gets the value of the lifter pot.
void interrupt_auto_stack (void *param)
Stpos an autostack in case of an error.
float lifterPotentiometerToDegree (int x)
height of the lifter in degrees from 0 height
void lower_main_lifter ()
Lowers the main lifter.
void lower_secondary_lifter ()
Lowers the secondary lifter.
static void main_lifter_update ()
static void quit_auto_static ()
void raise_main_lifter ()
Raises the main lifter.
void raise_secondary_lifter ()
Raises the main lifter.
static void secondary_lifter_update ()
void set_lifter_pos (int pos)
Sets the lifter positions to the given value.
void set_main_lifter_motors (const int v)
Sets the main lifter motors to the given value.
void set_secondary_lifter_motors (const int v)
Sets the secondary lifter motors to the given value.
void update_lifter ()
Updates the lifter in teleop.
Variables
static bool lifter_autostack_routine_interupt = false
bool lifter_autostack_running = false
static bool secondary_override = false
Function Documentation
autostack_routine()
void autostack_routine (void * param)
Autostacks a cone once picked up.
Parameters
param ignored parameter
Definition at line 20 of file lifter.c.
References analogRead(), delay(), info(), lifter_autostack_routine_interupt, lifter_autostack_running, lifter_ultrasonic, printf(), quit_auto_static(), raise_secondary_lifter(), set_claw_motor(), set_main_lifter_motors(), set_secondary_lifter_motors(), and ultrasonicGet().
Referenced by operatorControl().
                                    {
  lifter_autostack_routine_interupt = false;
  lifter_autostack_running = true;
  raise_secondary_lifter();
  while (analogRead(SECONDARY_LIFTER_POT_PORT) < 1600) {
    set_secondary_lifter_motors(MIN_SPEED);
    if (lifter_autostack_routine_interupt) {
      quit_auto_static();
      return;
    }
    delay(50);
    info("1");
  }
  set_secondary_lifter_motors(0);
  bool lifted = false;
  int val = ultrasonicGet(lifter_ultrasonic);
  printf("%d\n", val);
  while (val < 10 && val != ULTRA_BAD_RESPONSE) {
    if (lifter_autostack_routine_interupt) {
      quit_auto_static();
      return;
    }
    set_main_lifter_motors(MAX_SPEED);
    info("2");
    lifted = true;
    delay(50);
    val = ultrasonicGet(lifter_ultrasonic);
    printf("%d\n", val);
  }
  if (lifter_autostack_routine_interupt) {
    quit_auto_static();
    return;
  }
  delay(200);
  if (lifted)
    delay(50);
  if (lifter_autostack_routine_interupt) {
    quit_auto_static();
    return;
  }
  set_main_lifter_motors(0);
  set_secondary_lifter_motors(0);
  while (analogRead(SECONDARY_LIFTER_POT_PORT) < 3000) {
    if (lifter_autostack_routine_interupt) {
      quit_auto_static();
      return;
    }
    set_secondary_lifter_motors(MIN_SPEED);
    delay(50);
    info("3");
  }
  set_main_lifter_motors(MIN_SPEED / 1.333);
  while (val > 10) {
    if (lifter_autostack_routine_interupt) {
      quit_auto_static();
      return;
    }
    info("2");
    lifted = true;
    delay(30);
    val = ultrasonicGet(lifter_ultrasonic);
    printf("%d\n", val);
  }
  set_main_lifter_motors(0);
  set_claw_motor(MIN_CLAW_SPEED);
  if (lifter_autostack_routine_interupt) {
    quit_auto_static();
    return;
  }
  delay(500);
  if (lifter_autostack_routine_interupt) {
    quit_auto_static();
    return;
  }
  set_main_lifter_motors(MAX_SPEED);
  if (lifter_autostack_routine_interupt) {
    quit_auto_static();
    return;
  }
  delay(300);
  set_main_lifter_motors(MIN_SPEED);
  set_claw_motor(0);
  set_secondary_lifter_motors(0);
  lifter_autostack_running = false;
}
getLifterHeight()
double getLifterHeight ()
Gets the height of the lifter in inches.
Returns
the height of the lifter.
Author
Chris Jerrett
Date
9/17/2017
Definition at line 306 of file lifter.c.
References getLifterTicks().
                         {
  unsigned int ticks = getLifterTicks();
  return (-2 * pow(10, (-9 * ticks)) + 6 * (pow(10, (-6 * ticks * ticks))) +
          0.0198 * ticks + 2.3033);
}
getLifterTicks()
int getLifterTicks ()
Gets the value of the lifter pot.
Returns
the value of the pot.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 297 of file lifter.c.
References analogRead().
Referenced by getLifterHeight().
{ return analogRead(LIFTER); }
interrupt_auto_stack()
void interrupt_auto_stack (void * param)
Stpos an autostack in case of an error.
Parameters
param ignore parameter
Definition at line 8 of file lifter.c.
References info(), and lifter_autostack_routine_interupt.
Referenced by operatorControl().
                                       {
  info("int");
  lifter_autostack_routine_interupt = true;
}
lifterPotentiometerToDegree()
float lifterPotentiometerToDegree (int x)
height of the lifter in degrees from 0 height
Parameters
x the pot value
Returns
the positions in degrees
Author
Chris Jerrett
Date
10/13/2017
Definition at line 286 of file lifter.c.
                                         {
  return (x - INIT_ROTATION) / TICK_MAX * DEG_MAX;
}
lower_main_lifter()
void lower_main_lifter ()
Lowers the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 160 of file lifter.c.
References set_main_lifter_motors().
{ set_main_lifter_motors(MAX_SPEED); }
lower_secondary_lifter()
void lower_secondary_lifter ()
Lowers the secondary lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 176 of file lifter.c.
References set_secondary_lifter_motors().
{ set_secondary_lifter_motors(MAX_SPEED); }
main_lifter_update()
static void main_lifter_update () [static]
Definition at line 180 of file lifter.c.
References analogRead(), error(), joystickGetDigital(), lifter_autostack_running, lifter_ultrasonic, secondary_override, set_main_lifter_motors(), and ultrasonicGet().
Referenced by update_lifter().
                                 {
  if (lifter_autostack_running) {
    error("True");
    return;
  }
  error("1");
  static int count = 0;
  static bool pid_on = false;
  static int main_target = 0;
  int main_motor_speed = 0;
  static long long main_i = 0;
  if (count == 20) {
    main_target = analogRead(MAIN_LIFTER_POT);
  }
  if (pid_on && count > 20) {
    int curr = analogRead(MAIN_LIFTER_POT);
    static int main_last_p = 0;
    int main_p = curr - main_target;
    main_i += main_p;
    int main_d = main_last_p - main_p;
    // main_motor_speed = MAIN_LIFTER_P * main_p + MAIN_LIFTER_I * main_i +
    // MAIN_LIFTER_D * main_d;
    main_last_p = main_p;
  } else {
    main_i = 0;
    count++;
  }
  error("2");
  if (joystickGetDigital(LIFTER_UP)) {
    int ultra = ultrasonicGet(lifter_ultrasonic);
    main_motor_speed = MAX_SPEED;
    count = 0;
  } else if (joystickGetDigital(LIFTER_DOWN)) {
    main_motor_speed = MIN_SPEED;
    count = 0;
    secondary_override = false;
  } else {
    secondary_override = false;
  }
  set_main_lifter_motors(main_motor_speed);
  pid_on = true;
}
quit_auto_static()
static void quit_auto_static () [inline], [static]
Definition at line 13 of file lifter.c.
References lifter_autostack_running, set_claw_motor(), set_main_lifter_motors(), and set_secondary_lifter_motors().
Referenced by autostack_routine().
                                      {
  set_main_lifter_motors(0);
  set_secondary_lifter_motors(0);
  set_claw_motor(0);
  lifter_autostack_running = false;
}
raise_main_lifter()
void raise_main_lifter ()
Raises the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 152 of file lifter.c.
References set_main_lifter_motors().
{ set_main_lifter_motors(MAX_SPEED); }
raise_secondary_lifter()
void raise_secondary_lifter ()
Raises the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 168 of file lifter.c.
References set_secondary_lifter_motors().
Referenced by autostack_routine().
{ set_secondary_lifter_motors(MIN_SPEED / 1.5); }
secondary_lifter_update()
static void secondary_lifter_update () [static]
Definition at line 223 of file lifter.c.
References analogRead(), claw_grab_cone(), joystickGetDigital(), lifter_autostack_running, and set_secondary_lifter_motors().
Referenced by update_lifter().
                                      {
  if (lifter_autostack_running)
    return;
  static int count = 0;
  // static bool pid_on = false;
  static int second_target = 0;
  int second_motor_speed = 0;
  static long long second_i = 0;
  if (count < 10) {
    second_target = analogRead(SECONDARY_LIFTER_POT_PORT);
    count++;
  }
  int curr = analogRead(SECONDARY_LIFTER_POT_PORT);
  static int second_last_p = 0;
  int second_p = curr - second_target;
  second_i += second_p;
  int second_d = second_last_p - second_p;
  second_motor_speed = SECONDARY_LIFTER_P * second_p +
                       SECONDARY_LIFTER_I * second_i +
                       SECONDARY_LIFTER_D * second_d;
  second_last_p = second_p;
  if (joystickGetDigital(SECONDARY_LIFTER_DOWN)) {
    second_motor_speed = MAX_SPEED;
    count = 0;
    second_i = 0;
    second_target = analogRead(SECONDARY_LIFTER_POT_PORT);
    claw_grab_cone();
  } else if (joystickGetDigital(SECONDARY_LIFTER_UP)) {
    second_motor_speed = MIN_SPEED;
    count = 0;
    second_i = 0;
    second_target =
        second_target > 3000 ? 4095 : analogRead(SECONDARY_LIFTER_POT_PORT);
  } else {
    second_target = second_target > 3000 ? 4095 : second_target;
  }
  second_motor_speed = abs(second_motor_speed) < 20 ? 0 : second_motor_speed;
  set_secondary_lifter_motors(second_motor_speed);
}
set_lifter_pos()
void set_lifter_pos (int pos)
Sets the lifter positions to the given value.
Parameters
pos The height in inches
Author
Chris Jerrett
Date
9/12/2017
Definition at line 144 of file lifter.c.
{}
set_main_lifter_motors()
void set_main_lifter_motors (const int v)
Sets the main lifter motors to the given value.
Parameters
v value for the lifter motor. Between -128 - 127, any values outside are clamped.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 133 of file lifter.c.
References set_motor_slew().
Referenced by auton_rasie_main_lifter(), autostack_routine(), lower_main_lifter(), main_lifter_update(), quit_auto_static(), and raise_main_lifter().
                                         {
  set_motor_slew(MOTOR_MAIN_LIFTER, v);
}
set_secondary_lifter_motors()
void set_secondary_lifter_motors (const int v)
Sets the secondary lifter motors to the given value.
Parameters
v value for the lifter motor. Between -128 - 127, any values outside are clamped.
Author
Chris Jerrett
Date
1/6/2018
Definition at line 121 of file lifter.c.
References set_motor_immediate().
Referenced by auton_raise_sec_lifter_max(), autonomous(), autostack_routine(), deploy_seoncdary_lifter(), lower_secondary_lifter(), quit_auto_static(), raise_secondary_lifter(), and secondary_lifter_update().
                                              {
  set_motor_immediate(MOTOR_SECONDARY_LIFTER, v);
}
update_lifter()
void update_lifter ()
Updates the lifter in teleop.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 272 of file lifter.c.
References analogRead(), main_lifter_update(), printf(), secondary_lifter_update(), and secondary_override.
Referenced by operatorControl().
                     {
  printf("%d \n", analogRead(SECONDARY_LIFTER_POT_PORT));
  main_lifter_update();
  if (!secondary_override)
    secondary_lifter_update();
}
Variable Documentation
lifter_autostack_routine_interupt
bool lifter_autostack_routine_interupt = false [static]
Definition at line 6 of file lifter.c.
Referenced by autostack_routine(), and interrupt_auto_stack().
lifter_autostack_running
bool lifter_autostack_running = false
Definition at line 5 of file lifter.c.
Referenced by autostack_routine(), main_lifter_update(), quit_auto_static(), secondary_lifter_update(), and update_claw().
secondary_override
bool secondary_override = false [static]
Definition at line 178 of file lifter.c.
Referenced by main_lifter_update(), and update_lifter().