include/lifter.h File Reference
Declarations and macros for controlling and manipulating the lifter.
#include <API.h>
#include `motor_ports.h`
#include `sensor_ports.h`
#include `slew.h`
#include `controller.h`
#include `potentiometer.h`
#include `partner.h`
#include `drive.h`
Macros
#define HEIGHT 19.1 - 3.8
The integral constant for the lifter PID.
#define INIT_ROTATION 680
The initial rotation of the lifter potentiometer at height zero.
#define LIFTER_D 0
The derivative constant for the lifter PID.
#define LIFTER_DOWN MASTER, 5, JOY_DOWN
The lifter down controller params.
#define LIFTER_DOWN_PARTNER PARTNER, 5, JOY_DOWN
The lifter down controller params for the partner.
#define LIFTER_DRIVER_LOAD MASTER, RIGHT_BUTTONS, JOY_RIGHT
Height to raise lifter to driver preload height.
#define LIFTER_I 0
The integral constant for the lifter PID.
#define LIFTER_P .15
The proportional constant for the lifter PID.
#define LIFTER_UP MASTER, 5, JOY_UP
The lifter up controller params.
#define LIFTER_UP_PARTNER PARTNER, 5, JOY_UP
The lifter up controller params for the partner.
#define MAIN_LIFTER_MIN_HEIGHT 1700
#define MAIN_LIFTER_POT 1
#define SECONDARY_LIFTER_MAX_HEIGHT 2500
#define SECONDARY_LIFTER_MIN_HEIGHT 1300
#define SECONDARY_LIFTER_POT_PORT 2
#define THRESHOLD 10
The threshold of a signficant speed for the lifter.
Functions
double getLifterHeight ()
Gets the height of the lifter in inches.
int getLifterTicks ()
Gets the value of the lifter pot.
float lifterPotentiometerToDegree (int x)
height of the lifter in degrees from 0 height
void lower_main_lifter ()
Lowers the main lifter.
void lower_secondary_lifter ()
Lowers the secondary lifter.
void raise_main_lifter ()
Raises the main lifter.
void raise_secondary_lifter ()
Raises the main lifter.
void set_lifter_pos (int pos)
Sets the lifter positions to the given value.
void set_main_lifter_motors (const int v)
Sets the main lifter motors to the given value.
void set_secondary_lifter_motors (const int v)
Sets the secondary lifter motors to the given value.
void update_lifter ()
Updates the lifter in teleop.
Detailed Description
Declarations and macros for controlling and manipulating the lifter.
Author
Chris Jerrett, Christian Desimone
Date
8/27/2017
Definition in file lifter.h.
Macro Definition Documentation
HEIGHT
#define HEIGHT 19.1 - 3.8
The integral constant for the lifter PID.
Definition at line 48 of file lifter.h.
INIT_ROTATION
#define INIT_ROTATION 680
The initial rotation of the lifter potentiometer at height zero.
Definition at line 22 of file lifter.h.
Referenced by lifterPotentiometerToDegree().
LIFTER_D
#define LIFTER_D 0
The derivative constant for the lifter PID.
Definition at line 32 of file lifter.h.
LIFTER_DOWN
#define LIFTER_DOWN MASTER, 5, JOY_DOWN
The lifter down controller params.
Definition at line 58 of file lifter.h.
Referenced by update_lifter().
LIFTER_DOWN_PARTNER
#define LIFTER_DOWN_PARTNER PARTNER, 5, JOY_DOWN
The lifter down controller params for the partner.
Definition at line 73 of file lifter.h.
LIFTER_DRIVER_LOAD
#define LIFTER_DRIVER_LOAD MASTER, RIGHT_BUTTONS, JOY_RIGHT
Height to raise lifter to driver preload height.
Definition at line 63 of file lifter.h.
LIFTER_I
#define LIFTER_I 0
The integral constant for the lifter PID.
Definition at line 42 of file lifter.h.
LIFTER_P
#define LIFTER_P .15
The proportional constant for the lifter PID.
Definition at line 27 of file lifter.h.
LIFTER_UP
#define LIFTER_UP MASTER, 5, JOY_UP
The lifter up controller params.
Definition at line 53 of file lifter.h.
Referenced by update_lifter().
LIFTER_UP_PARTNER
#define LIFTER_UP_PARTNER PARTNER, 5, JOY_UP
The lifter up controller params for the partner.
Definition at line 68 of file lifter.h.
MAIN_LIFTER_MIN_HEIGHT
#define MAIN_LIFTER_MIN_HEIGHT 1700
Definition at line 83 of file lifter.h.
Referenced by update_lifter().
MAIN_LIFTER_POT
#define MAIN_LIFTER_POT 1
Definition at line 81 of file lifter.h.
Referenced by update_lifter().
SECONDARY_LIFTER_MAX_HEIGHT
#define SECONDARY_LIFTER_MAX_HEIGHT 2500
Definition at line 77 of file lifter.h.
Referenced by update_lifter().
SECONDARY_LIFTER_MIN_HEIGHT
#define SECONDARY_LIFTER_MIN_HEIGHT 1300
Definition at line 79 of file lifter.h.
SECONDARY_LIFTER_POT_PORT
#define SECONDARY_LIFTER_POT_PORT 2
Definition at line 75 of file lifter.h.
Referenced by update_lifter().
THRESHOLD
#define THRESHOLD 10
The threshold of a signficant speed for the lifter.
Definition at line 37 of file lifter.h.
Function Documentation
getLifterHeight()
double getLifterHeight ()
Gets the height of the lifter in inches.
Returns
the height of the lifter.
Author
Chris Jerrett
Date
9/17/2017
Definition at line 133 of file lifter.c.
References getLifterTicks().
                         {
  unsigned int ticks = getLifterTicks();
  return (-2 * pow(10, (-9 * ticks)) + 6 * (pow(10, (-6 * ticks * ticks))) + 0.0198 * ticks + 2.3033);
}
getLifterTicks()
int getLifterTicks ()
Gets the value of the lifter pot.
Returns
the value of the pot.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 122 of file lifter.c.
References LIFTER.
Referenced by getLifterHeight().
                     {
  return analogRead(LIFTER);
}
lifterPotentiometerToDegree()
float lifterPotentiometerToDegree (int x)
height of the lifter in degrees from 0 height
Parameters
x the pot value
Returns
the positions in degrees
Author
Chris Jerrett
Date
10/13/2017
Definition at line 111 of file lifter.c.
References DEG_MAX, INIT_ROTATION, and TICK_MAX.
                                        {
  return (x - INIT_ROTATION) / TICK_MAX * DEG_MAX;
}
lower_main_lifter()
void lower_main_lifter ()
Lowers the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 53 of file lifter.c.
References MIN_SPEED, and set_main_lifter_motors().
                        {
  set_main_lifter_motors(MIN_SPEED);
}
lower_secondary_lifter()
void lower_secondary_lifter ()
Lowers the secondary lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 73 of file lifter.c.
References MIN_SPEED, and set_secondary_lifter_motors().
                             {
  set_secondary_lifter_motors(MIN_SPEED);
}
raise_main_lifter()
void raise_main_lifter ()
Raises the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 43 of file lifter.c.
References MAX_SPEED, and set_main_lifter_motors().
                        {
  set_main_lifter_motors(MAX_SPEED);
}
raise_secondary_lifter()
void raise_secondary_lifter ()
Raises the main lifter.
Author
Christian DeSimone
Date
9/12/2017
Definition at line 63 of file lifter.c.
References MAX_SPEED, and set_secondary_lifter_motors().
                             {
  set_secondary_lifter_motors(MAX_SPEED);
}
set_lifter_pos()
void set_lifter_pos (int pos)
Sets the lifter positions to the given value.
Parameters
pos The height in inches
Author
Chris Jerrett
Date
9/12/2017
Definition at line 33 of file lifter.c.
                             {
}
set_main_lifter_motors()
void set_main_lifter_motors (const int v)
Sets the main lifter motors to the given value.
Parameters
v value for the lifter motor. Between -128 - 127, any values outside are clamped.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 22 of file lifter.c.
References MOTOR_LIFT, and set_motor_immediate().
Referenced by lower_main_lifter(), raise_main_lifter(), and update_lifter().
                                         {
  set_motor_immediate(MOTOR_LIFT, v);
}
set_secondary_lifter_motors()
void set_secondary_lifter_motors (const int v)
Sets the secondary lifter motors to the given value.
Parameters
v value for the lifter motor. Between -128 - 127, any values outside are clamped.
Author
Chris Jerrett
Date
1/6/2018
Definition at line 11 of file lifter.c.
References MOTOR_SECONDARY_LIFTER, and set_motor_immediate().
Referenced by lower_secondary_lifter(), raise_secondary_lifter(), and update_lifter().
                                              {
  set_motor_immediate(MOTOR_SECONDARY_LIFTER, v);
}
update_lifter()
void update_lifter ()
Updates the lifter in teleop.
Author
Chris Jerrett
Date
9/9/2017
Definition at line 83 of file lifter.c.
References LIFTER_DOWN, LIFTER_UP, MAIN_LIFTER_MIN_HEIGHT, MAIN_LIFTER_POT, MAX_SPEED, MIN_SPEED, SECONDARY_LIFTER_MAX_HEIGHT, SECONDARY_LIFTER_POT_PORT, set_main_lifter_motors(), and set_secondary_lifter_motors().
Referenced by operatorControl().
                     {
  printf("%d\n", analogRead(1));
  if(joystickGetDigital(LIFTER_DOWN) && analogRead(MAIN_LIFTER_POT) <
      MAIN_LIFTER_MIN_HEIGHT) {
    set_secondary_lifter_motors(MAX_SPEED);
    set_main_lifter_motors(MIN_SPEED);
  } else if(joystickGetDigital(LIFTER_DOWN) && analogRead(MAIN_LIFTER_POT) >=
      MAIN_LIFTER_MIN_HEIGHT) {
    set_secondary_lifter_motors(MAX_SPEED);
    set_main_lifter_motors(0);
  } else if(joystickGetDigital(LIFTER_UP) && analogRead(
      SECONDARY_LIFTER_POT_PORT) < SECONDARY_LIFTER_MAX_HEIGHT) {
    set_secondary_lifter_motors(MIN_SPEED);
    set_main_lifter_motors(0);
  } else if(joystickGetDigital(LIFTER_UP) && analogRead(
      SECONDARY_LIFTER_POT_PORT) >= SECONDARY_LIFTER_MAX_HEIGHT) {
    set_main_lifter_motors(MAX_SPEED);
    set_secondary_lifter_motors(MIN_SPEED);
  } else {
    set_secondary_lifter_motors(0);
    set_main_lifter_motors(0);
  }
}