include/list.h File Reference
A doubly linked list implementation.
Data Structures
struct list_iterator_t
A iterator representation Allows automatic iteration through linked list.
struct list_node
A node in a list.
struct list_t
A struct representing a linked list.
Typedefs
typedef struct list_node list_node_t
A node in a list.
Enumerations
enum list_direction_t { LIST_HEAD,
 LIST_TAIL
 }
list_t iterator direction.
Functions
 list_node_t * list_at (list_t *self, int index)
Finds a node a given index.
void list_destroy (list_t *self)
Deallocates a list.
 list_node_t * list_find (list_t *self, void *val)
Finds a node in a list with a given value.
void list_iterator_destroy (list_iterator_t *self)
Destroys the iterator.
 list_iterator_t * list_iterator_new (list_t *list, list_direction_t direction)
Creates a new iterator.
 list_iterator_t * list_iterator_new_from_node (list_node_t *node, list_direction_t direction)
Creates a new iterator by using the node to start at.
 list_node_t * list_iterator_next (list_iterator_t *self)
The next node in the iterator and advances the iterator.
 list_node_t * list_lpop (list_t *self)
removes and returns the start node
 list_node_t * list_lpush (list_t *self, list_node_t *node)
Pushed a node to the start of a list.
 list_t * list_new ()
Allocated a new list.
 list_node_t * list_node_new (void *val)
Allocates a new node.
void list_remove (list_t *self, list_node_t *node)
removes and returns the a given node from the list
 list_node_t * list_rpop (list_t *self)
removes and returns the end node
 list_node_t * list_rpush (list_t *self, list_node_t *node)
Pushed a node to the end of a list.
Detailed Description
A doubly linked list implementation.
A linked list is a linear data structure where each element is a separate object.
Each element (we will call it a node) of a list is comprising of two items - the data and a reference to the next node. The last node has a reference to null. The entry point into a linked list is called the head of the list. It should be noted that head is not a separate node, but the reference to the first node. If the list is empty then the head is a null reference. A linked list is a dynamic data structure. The number of nodes in a list is not fixed and can grow and shrink on demand. Any application which has to deal with an unknown number of objects will need to use a linked list.
A Doubly Linked List is a variation of Linked list in which navigation is possible in both ways, either forward and backward easily as compared to Single Linked List.
Author
Chris Jerrett
Date
1/3/18
Definition in file list.h.
Typedef Documentation
list_node_t
typedef struct list_node list_node_t
A node in a list.
Author
Chris Jerrett
Date
1/3/18
Enumeration Type Documentation
list_direction_t
enum list_direction_t
list_t iterator direction.
Tells a iterator what direction to traverse the linked list in.
Author
Chris Jerrett
Date
1/3/18
Enumerator
LIST_HEAD start at head start at tail
LIST_TAIL
Definition at line 36 of file list.h.
             {
            LIST_HEAD
    ,
    LIST_TAIL
} list_direction_t;
Function Documentation
list_at()
 list_node_t* list_at (list_t * self, int index)
Finds a node a given index.
Parameters
self the list
index the index
Returns
the node
Author
Chris Jerrett
Date
1/3/18
Definition at line 202 of file list.c.
References LIST_HEAD, list_iterator_destroy(), list_iterator_new(), list_iterator_next(), and LIST_TAIL.
                                              {
  list_direction_t direction = LIST_HEAD;
  if (index < 0) {
    direction = LIST_TAIL;
    index = ~index;
  }
  if ((unsigned)index < self->len) {
    list_iterator_t *it = list_iterator_new(self, direction);
    list_node_t *node = list_iterator_next(it);
    while (index--)
      node = list_iterator_next(it);
    list_iterator_destroy(it);
    return node;
  }
  return NULL;
}
list_destroy()
void list_destroy (list_t * self)
Deallocates a list.
Parameters
self the list
Author
Chris Jerrett
Date
1/3/18
Definition at line 50 of file list.c.
References list_node::next, and list_node::val.
Referenced by deinit_routines().
                                {
  unsigned int len = self->len;
  list_node_t *next;
  list_node_t *curr = self->head;
  while (len--) {
    next = curr->next;
    if (self->free)
      self->free(curr->val);
    free(curr);
    curr = next;
  }
  free(self);
}
list_find()
 list_node_t* list_find (list_t * self, void * val)
Finds a node in a list with a given value.
Parameters
self the list
val the value
Returns
the node
Author
Chris Jerrett
Date
1/3/18
Definition at line 172 of file list.c.
References LIST_HEAD, list_iterator_destroy(), list_iterator_new(), list_iterator_next(), and list_node::val.
                                                {
  list_iterator_t *it = list_iterator_new(self, LIST_HEAD);
  list_node_t *node;
  while ((node = list_iterator_next(it))) {
    if (self->match) {
      if (self->match(val, node->val)) {
        list_iterator_destroy(it);
        return node;
      }
    } else {
      if (val == node->val) {
        list_iterator_destroy(it);
        return node;
      }
    }
  }
  list_iterator_destroy(it);
  return NULL;
}
list_iterator_destroy()
void list_iterator_destroy (list_iterator_t * self)
Destroys the iterator.
Parameters
self the iterator
Author
Chris Jerrett
Date
1/3/17
Definition at line 56 of file list_iterator.c.
Referenced by list_at(), list_find(), and routine_task().
                                                  {
  free(self);
  self = NULL;
}
list_iterator_new()
 list_iterator_t* list_iterator_new (list_t * list, list_direction_t direction)
Creates a new iterator.
Parameters
list the list
direction direction the iterator should progress in
Returns
the iterator created
Author
Chris Jerrett
Date
1/3/18
Definition at line 11 of file list_iterator.c.
References list_t::head, LIST_HEAD, list_iterator_new_from_node(), and list_t::tail.
Referenced by list_at(), list_find(), and routine_task().
                                                                             {
  list_node_t *node = direction == LIST_HEAD ? list->head : list->tail;
  return list_iterator_new_from_node(node, direction);
}
list_iterator_new_from_node()
 list_iterator_t* list_iterator_new_from_node (list_node_t * node, list_direction_t direction)
Creates a new iterator by using the node to start at.
Parameters
node the start node
direction direction the iterator should progress in
Returns
the iterator created
Author
Chris Jerrett
Date
1/3/18
Definition at line 24 of file list_iterator.c.
References list_iterator_t::next.
Referenced by list_iterator_new().
                                                                         {
  list_iterator_t *self;
  if (!(self = (list_iterator_t *)malloc(sizeof(list_iterator_t))))
    return NULL;
  self->next = node;
  self->direction = direction;
  return self;
}
list_iterator_next()
 list_node_t* list_iterator_next (list_iterator_t * self)
The next node in the iterator and advances the iterator.
Returns NULL when done.
Parameters
self the iterator
Returns
the next node.
Author
Chris Jerrett
Date
1/3/17
Definition at line 42 of file list_iterator.c.
References LIST_HEAD, list_node::next, and list_node::prev.
Referenced by list_at(), list_find(), and routine_task().
                                                       {
  list_node_t *curr = self->next;
  if (curr) {
    self->next = self->direction == LIST_HEAD ? curr->next : curr->prev;
  }
  return curr;
}
list_lpop()
 list_node_t* list_lpop (list_t * self)
removes and returns the start node
Parameters
self the list
Returns
the node removed
Author
Chris Jerrett
Date
1/3/18
Definition at line 122 of file list.c.
References list_node::next, and list_node::prev.
                                     {
  if (!self->len)
    return NULL;
  list_node_t *node = self->head;
  if (--self->len) {
    (self->head = node->next)->prev = NULL;
  } else {
    self->head = self->tail = NULL;
  }
  node->next = node->prev = NULL;
  return node;
}
list_lpush()
 list_node_t* list_lpush (list_t * self, list_node_t * node)
Pushed a node to the start of a list.
Parameters
self the list
node the node
Returns
the node added
Author
Chris Jerrett
Date
1/3/18
Definition at line 146 of file list.c.
References list_node::next, and list_node::prev.
                                                         {
  if (!node)
    return NULL;
  if (self->len) {
    node->next = self->head;
    node->prev = NULL;
    self->head->prev = node;
    self->head = node;
  } else {
    self->head = self->tail = node;
    node->prev = node->next = NULL;
  }
  ++self->len;
  return node;
}
list_new()
 list_t* list_new ()
Allocated a new list.
Returns
the new list
Author
Chris Jerrett
Date
1/3/18
Definition at line 34 of file list.c.
References list_t::head.
Referenced by init_routine().
                   {
  list_t *self;
  if (!(self = (list_t *)malloc(sizeof(list_t))))
    return NULL;
  self->head = NULL;
  self->tail = NULL;
  self->free = NULL;
  self->match = NULL;
  self->len = 0;
  return self;
}
list_node_new()
 list_node_t* list_node_new (void * val)
Allocates a new node.
Parameters
val The value the node contains.
Returns
The newly allocated node.
Author
Chris Jerrett
Date
1/3/18 Node must be freed
Definition at line 12 of file list_node.c.
References list_node::next, list_node::prev, and list_node::val.
Referenced by register_routine().
                                      {
  list_node_t *self;
  if (!(self = (list_node_t *)malloc(sizeof(list_node_t))))
    return NULL;
  self->prev = NULL;
  self->next = NULL;
  self->val = val;
  return self;
}
list_remove()
void list_remove (list_t * self, list_node_t * node)
removes and returns the a given node from the list
Parameters
self the list
Returns
the node removed
Author
Chris Jerrett
Date
1/3/18
Definition at line 229 of file list.c.
References list_node::next, list_node::prev, and list_node::val.
                                                  {
  node->prev ? (node->prev->next = node->next) : (self->head = node->next);
  node->next ? (node->next->prev = node->prev) : (self->tail = node->prev);
  if (self->free)
    self->free(node->val);
  free(node);
  --self->len;
}
list_rpop()
 list_node_t* list_rpop (list_t * self)
removes and returns the end node
Parameters
self the list
Returns
the node removed
Author
Chris Jerrett
Date
1/3/18
Definition at line 99 of file list.c.
References list_node::next, and list_node::prev.
                                     {
  if (!self->len)
    return NULL;
  list_node_t *node = self->tail;
  if (--self->len) {
    (self->tail = node->prev)->next = NULL;
  } else {
    self->tail = self->head = NULL;
  }
  node->next = node->prev = NULL;
  return node;
}
list_rpush()
 list_node_t* list_rpush (list_t * self, list_node_t * node)
Pushed a node to the end of a list.
Parameters
self the list
node the node
Returns
the node added
Author
Chris Jerrett
Date
1/3/18
Definition at line 74 of file list.c.
References list_node::next, and list_node::prev.
Referenced by register_routine().
                                                         {
  if (!node)
    return NULL;
  if (self->len) {
    node->prev = self->tail;
    node->next = NULL;
    self->tail->next = node;
    self->tail = node;
  } else {
    self->head = self->tail = node;
    node->prev = node->next = NULL;
  }
  ++self->len;
  return node;
}