src/list.c File Reference
Functions
 list_node_t * list_at (list_t *self, int index)
Finds a node a given index.
void list_destroy (list_t *self)
Deallocates a list.
 list_node_t * list_find (list_t *self, void *val)
Finds a node in a list with a given value.
 list_node_t * list_lpop (list_t *self)
removes and returns the start node
 list_node_t * list_lpush (list_t *self, list_node_t *node)
Pushed a node to the start of a list.
 list_t * list_new ()
Allocated a new list.
void list_remove (list_t *self, list_node_t *node)
removes and returns the a given node from the list
 list_node_t * list_rpop (list_t *self)
removes and returns the end node
 list_node_t * list_rpush (list_t *self, list_node_t *node)
Pushed a node to the end of a list.
Function Documentation
list_at()
 list_node_t* list_at (list_t * self, int index)
Finds a node a given index.
Parameters
self the list
index the index
Returns
the node
Author
Chris Jerrett
Date
1/3/18
Definition at line 202 of file list.c.
References LIST_HEAD, list_iterator_destroy(), list_iterator_new(), list_iterator_next(), and LIST_TAIL.
                                              {
  list_direction_t direction = LIST_HEAD;
  if (index < 0) {
    direction = LIST_TAIL;
    index = ~index;
  }
  if ((unsigned)index < self->len) {
    list_iterator_t *it = list_iterator_new(self, direction);
    list_node_t *node = list_iterator_next(it);
    while (index--)
      node = list_iterator_next(it);
    list_iterator_destroy(it);
    return node;
  }
  return NULL;
}
list_destroy()
void list_destroy (list_t * self)
Deallocates a list.
Parameters
self the list
Author
Chris Jerrett
Date
1/3/18
Definition at line 50 of file list.c.
References list_node::next, and list_node::val.
Referenced by deinit_routines().
                                {
  unsigned int len = self->len;
  list_node_t *next;
  list_node_t *curr = self->head;
  while (len--) {
    next = curr->next;
    if (self->free)
      self->free(curr->val);
    free(curr);
    curr = next;
  }
  free(self);
}
list_find()
 list_node_t* list_find (list_t * self, void * val)
Finds a node in a list with a given value.
Parameters
self the list
val the value
Returns
the node
Author
Chris Jerrett
Date
1/3/18
Definition at line 172 of file list.c.
References LIST_HEAD, list_iterator_destroy(), list_iterator_new(), list_iterator_next(), and list_node::val.
                                                {
  list_iterator_t *it = list_iterator_new(self, LIST_HEAD);
  list_node_t *node;
  while ((node = list_iterator_next(it))) {
    if (self->match) {
      if (self->match(val, node->val)) {
        list_iterator_destroy(it);
        return node;
      }
    } else {
      if (val == node->val) {
        list_iterator_destroy(it);
        return node;
      }
    }
  }
  list_iterator_destroy(it);
  return NULL;
}
list_lpop()
 list_node_t* list_lpop (list_t * self)
removes and returns the start node
Parameters
self the list
Returns
the node removed
Author
Chris Jerrett
Date
1/3/18
Definition at line 122 of file list.c.
References list_node::next, and list_node::prev.
                                     {
  if (!self->len)
    return NULL;
  list_node_t *node = self->head;
  if (--self->len) {
    (self->head = node->next)->prev = NULL;
  } else {
    self->head = self->tail = NULL;
  }
  node->next = node->prev = NULL;
  return node;
}
list_lpush()
 list_node_t* list_lpush (list_t * self, list_node_t * node)
Pushed a node to the start of a list.
Parameters
self the list
node the node
Returns
the node added
Author
Chris Jerrett
Date
1/3/18
Definition at line 146 of file list.c.
References list_node::next, and list_node::prev.
                                                         {
  if (!node)
    return NULL;
  if (self->len) {
    node->next = self->head;
    node->prev = NULL;
    self->head->prev = node;
    self->head = node;
  } else {
    self->head = self->tail = node;
    node->prev = node->next = NULL;
  }
  ++self->len;
  return node;
}
list_new()
 list_t* list_new ()
Allocated a new list.
Returns
the new list
Author
Chris Jerrett
Date
1/3/18
Definition at line 34 of file list.c.
References list_t::head.
Referenced by init_routine().
                   {
  list_t *self;
  if (!(self = (list_t *)malloc(sizeof(list_t))))
    return NULL;
  self->head = NULL;
  self->tail = NULL;
  self->free = NULL;
  self->match = NULL;
  self->len = 0;
  return self;
}
list_remove()
void list_remove (list_t * self, list_node_t * node)
removes and returns the a given node from the list
Parameters
self the list
Returns
the node removed
Author
Chris Jerrett
Date
1/3/18
Definition at line 229 of file list.c.
References list_node::next, list_node::prev, and list_node::val.
                                                  {
  node->prev ? (node->prev->next = node->next) : (self->head = node->next);
  node->next ? (node->next->prev = node->prev) : (self->tail = node->prev);
  if (self->free)
    self->free(node->val);
  free(node);
  --self->len;
}
list_rpop()
 list_node_t* list_rpop (list_t * self)
removes and returns the end node
Parameters
self the list
Returns
the node removed
Author
Chris Jerrett
Date
1/3/18
Definition at line 99 of file list.c.
References list_node::next, and list_node::prev.
                                     {
  if (!self->len)
    return NULL;
  list_node_t *node = self->tail;
  if (--self->len) {
    (self->tail = node->prev)->next = NULL;
  } else {
    self->tail = self->head = NULL;
  }
  node->next = node->prev = NULL;
  return node;
}
list_rpush()
 list_node_t* list_rpush (list_t * self, list_node_t * node)
Pushed a node to the end of a list.
Parameters
self the list
node the node
Returns
the node added
Author
Chris Jerrett
Date
1/3/18
Definition at line 74 of file list.c.
References list_node::next, and list_node::prev.
Referenced by register_routine().
                                                         {
  if (!node)
    return NULL;
  if (self->len) {
    node->prev = self->tail;
    node->next = NULL;
    self->tail->next = node;
    self->tail = node;
  } else {
    self->head = self->tail = node;
    node->prev = node->next = NULL;
  }
  ++self->len;
  return node;
}