src/list_iterator.c File Reference
Functions
void list_iterator_destroy (list_iterator_t *self)
Destroys the iterator.
 list_iterator_t * list_iterator_new (list_t *list, list_direction_t direction)
Creates a new iterator.
 list_iterator_t * list_iterator_new_from_node (list_node_t *node, list_direction_t direction)
Creates a new iterator by using the node to start at.
 list_node_t * list_iterator_next (list_iterator_t *self)
The next node in the iterator and advances the iterator.
Function Documentation
list_iterator_destroy()
void list_iterator_destroy (list_iterator_t * self)
Destroys the iterator.
Parameters
self the iterator
Author
Chris Jerrett
Date
1/3/17
Definition at line 56 of file list_iterator.c.
Referenced by list_at(), list_find(), and routine_task().
                                                  {
  free(self);
  self = NULL;
}
list_iterator_new()
 list_iterator_t* list_iterator_new (list_t * list, list_direction_t direction)
Creates a new iterator.
Parameters
list the list
direction direction the iterator should progress in
Returns
the iterator created
Author
Chris Jerrett
Date
1/3/18
Definition at line 11 of file list_iterator.c.
References list_t::head, LIST_HEAD, list_iterator_new_from_node(), and list_t::tail.
Referenced by list_at(), list_find(), and routine_task().
                                                                             {
  list_node_t *node = direction == LIST_HEAD ? list->head : list->tail;
  return list_iterator_new_from_node(node, direction);
}
list_iterator_new_from_node()
 list_iterator_t* list_iterator_new_from_node (list_node_t * node, list_direction_t direction)
Creates a new iterator by using the node to start at.
Parameters
node the start node
direction direction the iterator should progress in
Returns
the iterator created
Author
Chris Jerrett
Date
1/3/18
Definition at line 24 of file list_iterator.c.
References list_iterator_t::next.
Referenced by list_iterator_new().
                                                                         {
  list_iterator_t *self;
  if (!(self = (list_iterator_t *)malloc(sizeof(list_iterator_t))))
    return NULL;
  self->next = node;
  self->direction = direction;
  return self;
}
list_iterator_next()
 list_node_t* list_iterator_next (list_iterator_t * self)
The next node in the iterator and advances the iterator.
Returns NULL when done.
Parameters
self the iterator
Returns
the next node.
Author
Chris Jerrett
Date
1/3/17
Definition at line 42 of file list_iterator.c.
References LIST_HEAD, list_node::next, and list_node::prev.
Referenced by list_at(), list_find(), and routine_task().
                                                       {
  list_node_t *curr = self->next;
  if (curr) {
    self->next = self->direction == LIST_HEAD ? curr->next : curr->prev;
  }
  return curr;
}