include/localization.h File Reference
Declarations and macros for determining the location of the robot. [WIP].
Data Structures
struct location
Vector storing the cartesian cords and an angle.
Functions
int calculate_encoder_angle ()
Calculates the angle using the encoders.
struct location get_position ()
Gets the current posituion of the robot.
bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)
Starts the localization process.
void update_position ()
Updates the position from the localization.
Detailed Description
Declarations and macros for determining the location of the robot. [WIP].
Author
Chris Jerrett, Christian Desimone
Date
9/27/2017
Definition in file localization.h.
Function Documentation
calculate_encoder_angle()
int calculate_encoder_angle ()
Calculates the angle using the encoders.
Returns
the angle
Calculates the angle using the encoders.
Returns
the angle of rotation
Author
Chris Jerrett, Christian DeSimone
Definition at line 129 of file localization.c.
References get_encoder_ticks().
Referenced by auton_turn_180().
                              {
#define WIDTH 13.5
#define CPR 392.0
#define WHEEL_RADIUS 2
  int dist_r = get_encoder_ticks(0) / CPR;
  int dist_l = get_encoder_ticks(1) / CPR;
  return ((dist_r - dist_l) / WIDTH);
}
get_position()
struct location get_position ()
Gets the current posituion of the robot.
Parameters
gyro1 The first gyro
Returns
the loacation of the robot as a struct.
Author
Chris Jerrett
Parameters
gyro1 The first gyro
Returns
the loacation of the robot as a struct.
Definition at line 38 of file localization.c.
{}
init_localization()
bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)
Starts the localization process.
Author
Chris Jerrett
Parameters
gyro1 The first gyro The multiplier parameter can tune the gyro to adapt to specific sensors. The default value at this time is 196; higher values will increase the number of degrees reported for a fixed actual rotation, while lower values will decrease the number of degrees reported. If your robot is consistently turning too far, increase the multiplier, and if it is not turning far enough, decrease the multiplier.
Starts the localization process.
Author
Chris Jerrett
Returns
returns true when initialization is complete.
Definition at line 160 of file localization.c.
References g1, gyroInit(), last_call, localization_task, makeMatrix(), millis(), taskRunLoop(), and update_position().
                                                                  {
  g1 = gyroInit(gyro1, multiplier);
  // init state matrix
  // one dimensional vector with x, y, theta, acceleration in x and y
  state_matrix = makeMatrix(1, 5);
  localization_task =
      taskRunLoop(update_position, LOCALIZATION_UPDATE_FREQUENCY * 1000);
  last_call = millis();
  return true;
}
update_position()
void update_position ()
Updates the position from the localization.
Author
Chris Jerrett
Chris Jerrett, Christian DeSimone
Definition at line 45 of file localization.c.
References calculate_accelerometer_odemetry(), last_call, and millis().
Referenced by init_localization().
                       {
  // int curr_theta = calculate_angle();
  struct accelerometer_odometry oddem = calculate_accelerometer_odemetry();
  // printf("x: %d y: %d T: %d\n", a.x, a.y, 0);
  /*int l = 1;
  int vr = get_encoder_velocity(1);
  int vl = get_encoder_velocity(2);
  int theta_dot = (vr - vl) / l;
  int curr_theta = theta + theta_dot;
  double dt = LOCALIZATION_UPDATE_FREQUENCY;
  double v_tot = (vr+vl)/2.0;
  int x_curr = x - v_tot*dt*sin(curr_theta);
  int y_curr = y + v_tot*dt*cos(curr_theta);
  x = x_curr;
  y = y_curr;*/
  last_call = millis();
}