src/localization.c File Reference
Data Structures
struct accelerometer_odometry
Structure for holding an xy position from the accelerometer.
struct encoder_odemtry
Structure for holding an xy position and an angle theta from the IMEs.
Functions
static struct accelerometer_odometry calculate_accelerometer_odemetry ()
calculats the robot's position using the accelerometer
static double calculate_angle ()
int calculate_encoder_angle ()
calculates the current angle using the IMEs
static void calculate_encoder_odemetry ()
calculates the x y posistion of the robot based upon the IMEs
static double calculate_gryo_anglular_velocity ()
calculates the angular velocity using the gyro positions
struct location get_position ()
Gets the current posituion of the robot.
bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)
initializes the localization
static double integrate_gyro_w (int new_w)
Increases the stored angle based upon the update frequency and the current angular velocity.
void update_position ()
Updates the position from the localization.
Variables
static Gyro g1
static int last_call = 0
static TaskHandle localization_task
 matrix * state_matrix
Function Documentation
calculate_accelerometer_odemetry()
static struct accelerometer_odometry calculate_accelerometer_odemetry () [static]
calculats the robot's position using the accelerometer
Author
Chris Jerrett, Christian DeSimone
Returns
the xy position of the robot
See also
accelerometer_odometry
Definition at line 70 of file localization.c.
References analogReadCalibratedHR(), last_call, millis(), and printf().
Referenced by update_position().
                                                                        {
  static double vel_acumm_x = 0;
  static double vel_acumm_y = 0;
  int32_t accel_x_rel = (int32_t)analogReadCalibratedHR(2);
  int32_t accel_y_rel = (int32_t)analogReadCalibratedHR(3);
  // Ignore atom format string errors
  printf("x: %+" PRId32 " y: %+" PRId32 "\n", accel_x_rel, accel_y_rel);
  double delta_time = ((millis() - last_call) / 1000.0);
  // double accel_x_abs = (accel_x_rel * cos(theta) + accel_y_rel * sin(theta))
  // * delta_time; double accel_y_abs = (accel_y_rel * cos(theta) +
  // accel_x_rel
  // * sin(theta)) * delta_time;
  // vel_acumm_x += accel_x_abs;
  // vel_acumm_y += accel_y_abs;
  // double new_x = x + vel_acumm_x * delta_time;
  // double new_y = y + vel_acumm_y * delta_time;
  struct accelerometer_odometry od;
  // od.x = new_x;
  // od.y = new_y;
  return od;
}
calculate_angle()
static double calculate_angle () [static]
calculate_encoder_angle()
int calculate_encoder_angle ()
calculates the current angle using the IMEs
Calculates the angle using the encoders.
Returns
the angle of rotation
Author
Chris Jerrett, Christian DeSimone
Definition at line 129 of file localization.c.
References get_encoder_ticks().
Referenced by auton_turn_180().
                              {
#define WIDTH 13.5
#define CPR 392.0
#define WHEEL_RADIUS 2
  int dist_r = get_encoder_ticks(0) / CPR;
  int dist_l = get_encoder_ticks(1) / CPR;
  return ((dist_r - dist_l) / WIDTH);
}
calculate_encoder_odemetry()
static void calculate_encoder_odemetry () [static]
calculates the x y posistion of the robot based upon the IMEs
Author
Chris Jerrett, Christian DeSimone
Definition at line 142 of file localization.c.
References get_encoder_ticks(), printf(), and encoder_odemtry::theta.
                                         {
#define WIDTH 13.5
#define CPR 392.0
#define WHEEL_RADIUS 2
  int dist_r = get_encoder_ticks(0) / CPR;
  int dist_l = get_encoder_ticks(1) / CPR;
  printf("dist_r: %d dist_l: %d\n", dist_r, dist_l);
  int theta = (dist_l - dist_r) / WIDTH;
  printf("theta: %d\n", theta);
  int arc_length = ((M_PI * theta) * (WIDTH * WIDTH) / (8));
}
calculate_gryo_anglular_velocity()
static double calculate_gryo_anglular_velocity () [static]
calculates the angular velocity using the gyro positions
Author
Chris Jerrett, Christian DeSimone
Returns
the angular velocity of the robot.
Definition at line 116 of file localization.c.
References g1, and gyroGet().
                                                 {
  static int last_gyro = 0;
  int current = gyroGet(g1);
  // Calculate w (angluar velocity in degrees per second)
  double w = (current - last_gyro) / (LOCALIZATION_UPDATE_FREQUENCY / 1000.0);
  return w;
}
get_position()
struct location get_position ()
Gets the current posituion of the robot.
Author
Chris Jerrett
Parameters
gyro1 The first gyro
Returns
the loacation of the robot as a struct.
Definition at line 38 of file localization.c.
{}
init_localization()
bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)
initializes the localization
Starts the localization process.
Author
Chris Jerrett
Returns
returns true when initialization is complete.
Definition at line 160 of file localization.c.
References g1, gyroInit(), last_call, localization_task, makeMatrix(), millis(), taskRunLoop(), and update_position().
                                                                  {
  g1 = gyroInit(gyro1, multiplier);
  // init state matrix
  // one dimensional vector with x, y, theta, acceleration in x and y
  state_matrix = makeMatrix(1, 5);
  localization_task =
      taskRunLoop(update_position, LOCALIZATION_UPDATE_FREQUENCY * 1000);
  last_call = millis();
  return true;
}
integrate_gyro_w()
static double integrate_gyro_w (int new_w) [static]
Increases the stored angle based upon the update frequency and the current angular velocity.
Author
Chris Jerrett
Returns
returns the angle theta of the robot
Definition at line 104 of file localization.c.
References encoder_odemtry::theta.
                                          {
  static double theta = 0;
  double delta_theta = new_w * LOCALIZATION_UPDATE_FREQUENCY;
  theta += delta_theta;
  return theta;
}
update_position()
void update_position ()
Updates the position from the localization.
Author
Chris Jerrett, Christian DeSimone
Definition at line 45 of file localization.c.
References calculate_accelerometer_odemetry(), last_call, and millis().
Referenced by init_localization().
                       {
  // int curr_theta = calculate_angle();
  struct accelerometer_odometry oddem = calculate_accelerometer_odemetry();
  // printf("x: %d y: %d T: %d\n", a.x, a.y, 0);
  /*int l = 1;
  int vr = get_encoder_velocity(1);
  int vl = get_encoder_velocity(2);
  int theta_dot = (vr - vl) / l;
  int curr_theta = theta + theta_dot;
  double dt = LOCALIZATION_UPDATE_FREQUENCY;
  double v_tot = (vr+vl)/2.0;
  int x_curr = x - v_tot*dt*sin(curr_theta);
  int y_curr = y + v_tot*dt*cos(curr_theta);
  x = x_curr;
  y = y_curr;*/
  last_call = millis();
}
Variable Documentation
g1
 Gyro g1 [static]
Definition at line 5 of file localization.c.
Referenced by calculate_gryo_anglular_velocity(), and init_localization().
last_call
int last_call = 0 [static]
Definition at line 8 of file localization.c.
Referenced by calculate_accelerometer_odemetry(), init_localization(), and update_position().
localization_task
 TaskHandle localization_task [static]
Definition at line 6 of file localization.c.
Referenced by init_localization().
state_matrix
 matrix* state_matrix
Definition at line 10 of file localization.c.