src/log.c File Reference
Functions
void debug (const char *debug_message)
prints a info message
void error (const char *error_message)
prints a error message and displays on lcd.
void info (const char *info_message)
prints a info message
void init_error (bool use_lcd, FILE *lcd)
Initializes the error lcd system Only required if using lcd.
static void log_info (const char *s, const char *mess)
prints a log info message to the lcd
void warning (const char *warning_message)
prints a warning message and displays on lcd.
Variables
static FILE * log_lcd = NULL
unsigned int log_level = INFO
Function Documentation
debug()
void debug (const char * debug_message)
prints a info message
Only will print and display if log_level is greater than info
See also
log_level
Parameters
debug_message the message
Definition at line 83 of file log.c.
References log_level, and printf().
Referenced by set_motor_immediate(), and set_motor_slew().
                                      {
  if (log_level > ERROR) {
    printf("[INFO]: %s\n", debug_message);
  }
}
error()
void error (const char * error_message)
prints a error message and displays on lcd.
Only will print and display if log_level is greater than NONE
See also
log_level
Author
Chris Jerrett
Date
9/10/17
Parameters
error_message the message
Definition at line 45 of file log.c.
References log_info(), and log_level.
Referenced by assert(), create_menu(), init_encoders(), initialize(), main_lifter_update(), and routine_task().
                                      {
  if (log_level > NONE)
    log_info("ERROR", error_message);
}
info()
void info (const char * info_message)
prints a info message
Only will print and display if log_level is greater than ERROR
See also
log_level
Parameters
info_message the message
Definition at line 70 of file log.c.
References log_info(), and log_level.
Referenced by autonomous(), autostack_routine(), initialize(), interrupt_auto_stack(), and start_auton().
                                    {
  if (log_level > ERROR) {
    log_info("INFO", info_message);
  }
}
init_error()
void init_error (bool use_lcd, FILE * lcd)
Initializes the error lcd system Only required if using lcd.
Author
Chris Jerrett
Date
9/10/17
Parameters
use_lcd whether to use the lcd
lcd the lcd
Definition at line 14 of file log.c.
References lcdClear(), lcdInit(), log_lcd, and printf().
Referenced by initialize().
                                         {
  if (use_lcd) {
    lcdInit(lcd);
    log_lcd = lcd;
    lcdClear(log_lcd);
    printf("LCD Init\n");
  }
}
log_info()
static void log_info (const char * s, const char * mess) [static]
prints a log info message to the lcd
Author
Chris Jerrett
Date
9/10/17
Parameters
s the string on the top line
mess the string on the bottom line
Definition at line 29 of file log.c.
References lcdClear(), lcdPrint(), lcdSetBacklight(), log_lcd, and printf().
Referenced by error(), info(), and warning().
                                                      {
  printf("[%s]: %s\n", s, mess);
  lcdSetBacklight(log_lcd, false);
  lcdClear(log_lcd);
  lcdPrint(log_lcd, TOP_ROW, s);
  lcdPrint(log_lcd, BOTTOM_ROW, mess);
}
warning()
void warning (const char * warning_message)
prints a warning message and displays on lcd.
Only will print and display if log_level is greater than NONE
See also
log_level
Author
Chris Jerrett
Date
9/10/17
Parameters
warning_message the message
Definition at line 58 of file log.c.
References log_info(), and log_level.
Referenced by init_slew().
                                          {
  if (log_level > WARNING)
    log_info("WARNING", warning_message);
}
Variable Documentation
log_lcd
FILE* log_lcd = NULL [static]
Definition at line 4 of file log.c.
Referenced by init_error(), and log_info().
log_level
unsigned int log_level = INFO
Definition at line 3 of file log.c.
Referenced by debug(), error(), info(), and warning().