include/log.h File Reference
Contains logging functions.
#include <API.h>
#include `lcd.h`
Macros
#define DEBUG 4
logging only info debug. most verbose level
#define ERROR 1
logging only errors. Also displays error to lcd
#define INFO 3
logging only info messages and higher.
#define NONE 0
No logging. Should be used in competition to reduce serial communication.
#define WARNING 2
logs errors and warnings. Also displays error to lcd
Functions
void debug (const char *debug_message)
prints a info message
void error (const char *error_message)
prints a error message and displays on lcd. Only will print and display if log_level is greater than NONE
void info (const char *info_message)
prints a info message
void init_error (bool use_lcd, FILE *lcd)
Initializes the error lcd system Only required if using lcd.
void warning (const char *warning_message)
prints a warning message and displays on lcd. Only will print and display if log_level is greater than NONE
Detailed Description
Contains logging functions.
Author
Chris Jerrett
Date
9/16/2017
Definition in file log.h.
Macro Definition Documentation
DEBUG
#define DEBUG 4
logging only info debug. most verbose level
Author
Chris Jerrett
Date
9/10/17
Definition at line 50 of file log.h.
ERROR
#define ERROR 1
logging only errors. Also displays error to lcd
Author
Chris Jerrett
Date
9/10/17
Definition at line 27 of file log.h.
Referenced by debug(), and info().
INFO
#define INFO 3
logging only info messages and higher.
Author
Chris Jerrett
Date
9/10/17
Definition at line 42 of file log.h.
NONE
#define NONE 0
No logging. Should be used in competition to reduce serial communication.
Author
Chris Jerrett
Date
9/10/17
Definition at line 19 of file log.h.
Referenced by error().
WARNING
#define WARNING 2
logs errors and warnings. Also displays error to lcd
Author
Chris Jerrett
Date
9/10/17
Definition at line 35 of file log.h.
Referenced by warning().
Function Documentation
debug()
void debug (const char * debug_message)
prints a info message
Only will print and display if log_level is greater than info
See also
log_level
Parameters
debug_message the message
Definition at line 77 of file log.c.
References ERROR, and log_level.
Referenced by set_motor_immediate(), and set_motor_slew().
                                      {
  if(log_level>ERROR) {
    printf("[INFO]: %s\n", debug_message);
  }
}
error()
void error (const char * error_message)
prints a error message and displays on lcd. Only will print and display if log_level is greater than NONE
See also
log_level
Author
Chris Jerrett
Date
9/10/17
Parameters
error_message the message
Definition at line 39 of file log.c.
References log_info(), log_level, and NONE.
Referenced by create_menu().
                                      {
  if(log_level>NONE)
    log_info("ERROR", error_message);
}
info()
void info (const char * info_message)
prints a info message
Only will print and display if log_level is greater than ERROR
See also
log_level
Parameters
info_message the message
Definition at line 64 of file log.c.
References ERROR, log_info(), and log_level.
Referenced by init_slew(), and initialize().
                                    {
  if(log_level>ERROR) {
    log_info("INFO", info_message);
  }
}
init_error()
void init_error (bool use_lcd, FILE * lcd)
Initializes the error lcd system Only required if using lcd.
Author
Chris Jerrett
Date
9/10/17
Parameters
use_lcd whether to use the lcd
lcd the lcd
Definition at line 14 of file log.c.
References log_lcd.
Referenced by initialize().
                                         {
  if(use_lcd) {
    lcdInit(lcd);
    log_lcd = lcd;
    lcdClear(log_lcd);
    printf("LCD Init\n");
  }
}
warning()
void warning (const char * warning_message)
prints a warning message and displays on lcd. Only will print and display if log_level is greater than NONE
See also
log_level
Author
Chris Jerrett
Date
9/10/17
Parameters
warning_message the message
Definition at line 52 of file log.c.
References log_info(), log_level, and WARNING.
Referenced by init_slew().
                                          {
  if(log_level>WARNING)
    log_info("WARNING", warning_message);
}