include/main.h File Reference
Header file for global functions.
Functions
void autonomous ()
Runs the user autonomous code.
void initialize ()
Runs user initialization code.
void initializeIO ()
Runs pre-initialization code.
void operatorControl ()
Runs the user operator control code.
Detailed Description
Header file for global functions.
Any experienced C or C++ programmer knows the importance of header files. For those who do not, a header file allows multiple files to reference functions in other files without necessarily having to see the code (and therefore causing a multiple definition). To make a function in `opcontrol.c`, `auto.c`, `main.c`, or any other C file visible to the core implementation files, prototype it here.
This file is included by default in the predefined stubs in each VEX Cortex PROS Project.
Copyright (c) 2011-2014, Purdue University ACM SIG BOTS. All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of Purdue University ACM SIG BOTS nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS `AS IS` AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL PURDUE UNIVERSITY ACM SIG BOTS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Purdue Robotics OS contains FreeRTOS (http://www.freertos.org) whose source code may be obtained from http://sourceforge.net/projects/freertos/files/ or on request.
Definition in file main.h.
Function Documentation
autonomous()
void autonomous ()
Runs the user autonomous code.
This function will be started in its own task with the default priority and stack size whenever the robot is enabled via the Field Management System or the VEX Competition Switch in the autonomous mode. If the robot is disabled or communications is lost, the autonomous task will be stopped by the kernel. Re-enabling the robot will restart the task, not re-start it from where it left off.
Code running in the autonomous task cannot access information from the VEX Joystick. However, the autonomous function can be invoked from another task if a VEX Competition Switch is not available, and it can access joystick information if called in this way.
The autonomous task may exit, unlike operatorControl() which should never exit. If it does so, the robot will await a switch to another mode or disable/enable cycle.
Definition at line 125 of file auto.c.
References auton_drive_towards_mobile_goal(), auton_raise_sec_lifter_max(), auton_rasie_main_lifter(), auton_turn_180(), BOTH, claw_grab_cone(), deinitslew(), delay(), deploy_seoncdary_lifter(), imeGet(), info(), lower_intake(), raise_intake(), set_intake_motor(), set_secondary_lifter_motors(), set_side_speed(), setup_ime_auton(), and start_auton().
                  {
  start_auton();
  // How far the left wheels have gone
  int counts_drive_left;
  // How far the right wheels have gone
  int counts_drive_right;
  // The average distance traveled forward
  int counts_drive;
  // Reset the integrated motor controllers
  setup_ime_auton(&counts_drive_left, &counts_drive_right, &counts_drive);
  info("break 0");
  // Deploy claw
  deploy_seoncdary_lifter();
  info("break 1");
  info("break 2");
  set_secondary_lifter_motors(0);
  // Grab pre-load cone
  delay(300);
  auton_raise_sec_lifter_max();
  // Raise the lifter
  auton_rasie_main_lifter();
  // Drive towards the goal
  lower_intake();
  delay(300);
  set_intake_motor(0);
  auton_drive_towards_mobile_goal(counts_drive, counts_drive_left,
                                  counts_drive_right);
  // Stop moving
  set_side_speed(BOTH, 0);
  delay(1000);
  raise_intake();
  delay(300);
  set_intake_motor(0);
  // Drop the cone on the goal
  claw_grab_cone();
  delay(1000);
  auton_turn_180();
  counts_drive = 0;
  while (counts_drive < MOBILE_GOAL_DISTANCE + ZONE_DISTANCE) {
    set_side_speed(BOTH, 127);
    // Restablish the distance traveled
    imeGet(MID_LEFT_DRIVE, &counts_drive_left);
    imeGet(MID_RIGHT_DRIVE, &counts_drive_right);
    counts_drive = counts_drive_left + counts_drive_right;
    counts_drive /= 2;
  }
  lower_intake();
  delay(300);
  set_intake_motor(0);
  set_side_speed(BOTH, MIN_SPEED);
  delay(1000);
  set_side_speed(BOTH, 0);
  deinitslew();
}
initialize()
void initialize ()
Runs user initialization code.
This function will be started in its own task with the default priority and stack size once when the robot is starting up. It is possible that the VEXnet communication link may not be fully established at this time, so reading from the VEX Joystick may fail.
This function should initialize most sensors (gyro, encoders, ultrasonics), LCDs, global variables, and IMEs.
This function must exit relatively promptly, or the operatorControl() and autonomous() tasks will not start. An autonomous mode selection menu like the pre_auton() in other environments can be implemented in this task if desired.
Definition at line 52 of file init.c.
References battery_level_acceptable(), error(), info(), init_encoders(), init_error(), init_main_lcd(), init_menu_var(), lifter_ultrasonic, setTeamName(), STRING_TYPE, and ultrasonicInit().
                  {
  init_main_lcd(uart1);
  info("LCD Init");
  if (!battery_level_acceptable())
    error("Bad main/backup bat");
  menu_t *t =
      init_menu_var(STRING_TYPE, "TEST Menu", 5, "1", "2", "3", "4", "5");
  init_error(true, uart2);
  setTeamName("9228A");
  init_encoders();
  lifter_ultrasonic = ultrasonicInit(4, 5);
}
initializeIO()
void initializeIO ()
Runs pre-initialization code.
This function will be started in kernel mode one time while the VEX Cortex is starting up. As the scheduler is still paused, most API functions will fail.
The purpose of this function is solely to set the default pin modes (pinMode()) and port states (digitalWrite()) of limit switches, push buttons, and solenoids. It can also safely configure a UART port (usartOpen()) but cannot set up an LCD (lcdInit()).
Definition at line 36 of file init.c.
References watchdogInit().
{ watchdogInit(); }
operatorControl()
void operatorControl ()
Runs the user operator control code.
This function will be started in its own task with the default priority and stack size whenever the robot is enabled via the Field Management System or the VEX Competition Switch in the operator control mode. If the robot is disabled or communications is lost, the operator control task will be stopped by the kernel. Re-enabling the robot will restart the task, not resume it from where it left off.
If no VEX Competition Switch or Field Management system is plugged in, the VEX Cortex will run the operator control task. Be warned that this will also occur if the VEX Cortex is tethered directly to a computer via the USB A to A cable without any VEX Joystick attached.
Code running in this task can take almost any action, as the VEX Joystick is available and the scheduler is operational. However, proper use of delay() or taskDelayUntil() is highly recommended to give other tasks (including system tasks such as updating LCDs) time to run.
This task should never exit; it should end with some kind of infinite loop, even if empty.
This function will be started in its own task with the default priority and stack size whenever the robot is enabled via the Field Management System or the VEX Competition Switch in the operator control mode. If the robot is disabled or communications is lost, the operator control task will be stopped by the kernel. Re-enabling the robot will restart the task, not resume it from where it left off.
If no VEX Competition Switch or Field Management system is plugged in, the VEX Cortex will run the operator control task. Be warned that this will also occur if the VEX Cortex is tethered directly to a computer via the USB A to A cable without any VEX Joystick attached.
Code running in this task can take almost any action, as the VEX Joystick is available and the scheduler is operational. However, proper use of delay() or taskDelayUntil() is highly recommended to give other tasks (including system tasks such as updating LCDs) time to run.
This task should never exit; its should end with some kind of infinite loop, even if empty.
Definition at line 48 of file opcontrol.c.
References autostack_routine(), buttonInit(), delay(), init_routine(), init_slew(), interrupt_auto_stack(), JOY2_7D, JOY2_7R, register_routine(), update_claw(), update_drive_motors(), update_intake(), and update_lifter().
                       {
  buttonInit();
  init_routine();
  init_slew();
  register_routine(&autostack_routine, JOY2_7D, NULL);
  register_routine(&interrupt_auto_stack, JOY2_7R, NULL);
  while (1) {
    update_claw();
    update_intake();
    update_lifter();
    update_drive_motors();
    delay(20);
  }
}