src/matrix.c File Reference
#include `matrix.h`
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
void assert (int assertion, char *message)
matrix * copyMatrix (matrix *m)
matrix * covarianceMatrix (matrix *m)
matrix * dotDiagonalMatrix (matrix *a, matrix *b)
matrix * dotProductMatrix (matrix *a, matrix *b)
matrix * eyeMatrix (int n)
void freeMatrix (matrix *m)
matrix * makeMatrix (int width, int height)
matrix * meanMatrix (matrix *m)
matrix * multiplyMatrix (matrix *a, matrix *b)
void printMatrix (matrix *m)
void rowSwap (matrix *a, int p, int q)
matrix * scaleMatrix (matrix *m, double value)
double traceMatrix (matrix *m)
matrix * transposeMatrix (matrix *m)
Function Documentation
assert()
void assert (int assertion, char * message)
assert If the assertion is non-zero (i.e. true), then it returns. If the assertion is zero (i.e. false), then it display the string and aborts the program. This is ment to act like Python's assert keyword.
Definition at line 13 of file matrix.c.
References fprintf().
Referenced by covarianceMatrix(), dotDiagonalMatrix(), dotProductMatrix(), eyeMatrix(), makeMatrix(), meanMatrix(), multiplyMatrix(), and rowSwap().
                                          {
    if (assertion == 0) {
        fprintf(stderr, "%s\n", message);
        exit(1);
    }
}
copyMatrix()
matrix* copyMatrix (matrix * m)
copyMatrix Copies a matrix. This function uses scaleMatrix, because scaling matrix by 1 is the same as a copy.
Definition at line 47 of file matrix.c.
References scaleMatrix().
                              {
    return scaleMatrix(m, 1);
}
covarianceMatrix()
matrix* covarianceMatrix (matrix * m)
covarianceMatrix Given an `m rows by n columns` matrix, it returns a matrix with n row and n columns, where each element represents covariance of 2 columns.
Definition at line 164 of file matrix.c.
References assert(), _matrix::data, freeMatrix(), _matrix::height, makeMatrix(), meanMatrix(), and _matrix::width.
                                    {
    int i, j, k, L = 0;
    matrix* out;
    matrix* mean;
    double* ptrA;
    double* ptrB;
    double* ptrOut;
    assert(m->height > 1, "Height of matrix cannot be zero or one.");
    mean = meanMatrix(m);
    out = makeMatrix(m->width, m->width);
    ptrOut = out->data;
    for (i = 0; i < m->width; i++) {
        for (j = 0; j < m->width; j++) {
             ptrA = &m->data[i];
             ptrB = &m->data[j];
             *ptrOut = 0.0;
             for (k = 0; k < m->height; k++) {
                 *ptrOut += (*ptrA - mean->data[i]) * (*ptrB - mean->data[j]);
                 ptrA += m->width;
                 ptrB += m->width;
             }
             *ptrOut /= m->height - 1;
             ptrOut++;
        }
    }
    freeMatrix(mean);
    return out;
}
dotDiagonalMatrix()
matrix* dotDiagonalMatrix (matrix * a, matrix * b)
matrixDotDiagonal Given a two matrices (or the same matrix twice) with identical widths and heights, this method returns a 1 by a->height matrix of the cross product of each matrix along the diagonal.
Dot product is essentially the sum-of-squares of two vectors.
If the second paramter is NULL, it is assumed that we are performing a cross product with itself.
Definition at line 367 of file matrix.c.
References assert(), _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
                                                {
    matrix* out;
    double* ptrOut;
    double* ptrA;
    double* ptrB;
    int i, j;
    if (b != NULL) {
        assert(a->width == b->width && a->height == b->
      height, "Matrices must be of the same dimensionality.");
    }
    // Are we computing the sum of squares of the same matrix?
    if (a == b || b == NULL) {
        b = a; // May not appear safe, but we can do this without risk of losing b.
    }
    out = makeMatrix(1, a->height);
    ptrOut = out->data;
    ptrA = a->data;
    ptrB = b->data;
    for (i = 0; i < a->height; i++) {
        *ptrOut = 0;
        for (j = 0; j < a->width; j++) {
            *ptrOut += *ptrA * *ptrB;
            ptrA++;
            ptrB++;
        }
        ptrOut++;
    }
    return out;
}
dotProductMatrix()
matrix* dotProductMatrix (matrix * a, matrix * b)
dotProductMatrix Given a two matrices (or the same matrix twice) with identical widths and different heights, this method returns a a->height by b->height matrix of the cross product of each matrix.
Dot product is essentially the sum-of-squares of two vectors.
Also, if the second paramter is NULL, it is assumed that we are performing a cross product with itself.
Definition at line 318 of file matrix.c.
References assert(), _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
                                               {
    matrix* out;
    double* ptrOut;
    double* ptrA;
    double* ptrB;
    int i, j, k;
    if (b != NULL) {
        assert(a->width == b->width, "Matrices must be of the same dimensionality.");
    }
    // Are we computing the sum of squares of the same matrix?
    if (a == b || b == NULL) {
        b = a; // May not appear safe, but we can do this without risk of losing b.
    }
    out = makeMatrix(b->height, a->height);
    ptrOut = out->data;
    for (i = 0; i < a->height; i++) {
        ptrB = b->data;
        for (j = 0; j < b->height; j++) {
            ptrA = &a->data[ i * a->width ];
            *ptrOut = 0;
            for (k = 0; k < a->width; k++) {
                *ptrOut += *ptrA * *ptrB;
                ptrA++;
                ptrB++;
            }
            ptrOut++;
        }
    }
    return out;
}
eyeMatrix()
matrix* eyeMatrix (int n)
eyeMatrix Returns an identity matrix of size n by n, where n is the input parameter.
Definition at line 90 of file matrix.c.
References assert(), _matrix::data, and makeMatrix().
                         {
    int i;
    matrix *out;
    double* ptr;
    assert(n > 0, "Identity matrix must have value greater than zero.");
    out = makeMatrix(n, n);
    ptr = out->data;
    for (i = 0; i < n; i++) {
        *ptr = 1.0;
        ptr += n + 1;
    }
    return out;
}
freeMatrix()
void freeMatrix (matrix * m)
freeMatrix Frees the resources of a matrix
Definition at line 55 of file matrix.c.
References _matrix::data.
Referenced by covarianceMatrix().
                           {
    if (m != NULL) {
        if (m->data != NULL) {
            free(m->data);
            m->data = NULL;
        }
        free(m);
        m = NULL;
    }
    return;
}
makeMatrix()
matrix* makeMatrix (int width, int height)
makeMatrix Makes a matrix with a width and height parameters.
Definition at line 24 of file matrix.c.
References assert(), _matrix::data, _matrix::height, and _matrix::width.
Referenced by covarianceMatrix(), dotDiagonalMatrix(), dotProductMatrix(), eyeMatrix(), init_localization(), meanMatrix(), multiplyMatrix(), scaleMatrix(), and transposeMatrix().
                                          {
    matrix* out;
    assert(width > 0 && height > 0, "New matrix must be at least a 1 by 1");
    out = (matrix*) malloc(sizeof(matrix));
    assert(out != NULL, "Out of memory.");
    out->width = width;
    out->height = height;
    out->data = (double*) malloc(sizeof(double) * width * height);
    assert(out->data != NULL, "Out of memory.");
    memset(out->data, 0.0, width * height * sizeof(double));
    return out;
}
meanMatrix()
matrix* meanMatrix (matrix * m)
meanMatrix Given an `m rows by n columns` matrix, it returns a matrix with 1 row and n columns, where each element represents the mean of that full column.
Definition at line 138 of file matrix.c.
References assert(), _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
Referenced by covarianceMatrix().
                              {
    int i, j;
    double* ptr;
    matrix* out;
    assert(m->height > 0, "Height of matrix cannot be zero.");
    out = makeMatrix(m->width, 1);
    for (i = 0; i < m->width; i++) {
        out->data[i] = 0.0;
        ptr = &m->data[i];
        for (j = 0; j < m->height; j++) {
            out->data[i] += *ptr;
            ptr += out->width;
        }
        out->data[i] /= (double) m->height;
    }
    return out;
}
multiplyMatrix()
matrix* multiplyMatrix (matrix * a, matrix * b)
multiplyMatrix Given a two matrices, returns the multiplication of the two.
Definition at line 223 of file matrix.c.
References assert(), _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
                                             {
    int i, j, k;
    matrix* out;
    double* ptrOut;
    double* ptrA;
    double* ptrB;
    assert(a->width == b->height, "Matrices have incorrect dimensions. a->width !=
       b->height");
    out = makeMatrix(b->width, a->height);
    ptrOut = out->data;
    for (i = 0; i < a->height; i++) {
        for (j = 0; j < b->width; j++) {
            ptrA = &a->data[ i * a->width ];
            ptrB = &b->data[ j ];
            *ptrOut = 0;
            for (k = 0; k < a->width; k++) {
                *ptrOut += *ptrA * *ptrB;
                ptrA++;
                ptrB += b->width;
            }
            ptrOut++;
        }
    }
    return out;
}
printMatrix()
void printMatrix (matrix * m)
printMatrix Prints a matrix. Great for debugging.
Definition at line 72 of file matrix.c.
References _matrix::data, _matrix::height, printf(), and _matrix::width.
                            {
    int i, j;
    double* ptr = m->data;
    printf("%d %d\n", m->width, m->height);
    for (i = 0; i < m->height; i++) {
        for (j = 0; j < m->width; j++) {
            printf(" %9.6f", *(ptr++));
        }
        printf("\n");
    }
    return;
}
rowSwap()
void rowSwap (matrix * a, int p, int q)
rowSwap Given a matrix, this algorithm will swap rows p and q, provided that p and q are less than or equal to the height of matrix A and p and q are different values.
Definition at line 278 of file matrix.c.
References assert(), _matrix::data, _matrix::height, and _matrix::width.
                                      {
    int i;
    double temp;
    double* pRow;
    double* qRow;
    assert(a->height > 2, "Matrix must have at least two rows to swap.");
    assert(p < a->height && q < a->height, "Values p and q must be less than the height of the
       matrix.");
    // If p and q are equal, do nothing.
    if (p == q) {
        return;
    }
    pRow = a->data + (p * a->width);
    qRow = a->data + (q * a->width);
    // Swap!
    for (i = 0; i < a->width; i++) {
        temp = *pRow;
        *pRow = *qRow;
        *qRow = temp;
        pRow++;
        qRow++;
    }
    return;
}
scaleMatrix()
matrix* scaleMatrix (matrix * m, double value)
scaleMatrix Given a matrix and a double value, this returns a new matrix where each element in the input matrix is multiplied by the double value
Definition at line 259 of file matrix.c.
References _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
Referenced by copyMatrix().
                                             {
    int i, elements = m->width * m->height;
    matrix* out = makeMatrix(m->width, m->height);
    double* ptrM = m->data;
    double* ptrOut = out->data;
    for (i = 0; i < elements; i++) {
        *(ptrOut++) = *(ptrM++) * value;
    }
    return out;
}
traceMatrix()
double traceMatrix (matrix * m)
traceMatrix Given an `m rows by n columns` matrix, it returns the sum of the elements along the diagonal. This is know as the matrix 'trace'.
Definition at line 112 of file matrix.c.
References _matrix::data, _matrix::height, and _matrix::width.
                              {
    int i;
    int size;
    double* ptr = m->data;
    double sum = 0.0;
    if (m->height < m->width) {
        size = m->height;
    }
    else {
        size = m->width;
    }
    for (i = 0; i < size; i++) {
        sum += *ptr;
        ptr += m->width + 1;
    }
    return sum;
}
transposeMatrix()
matrix* transposeMatrix (matrix * m)
transposeMatrix Given an matrix, returns the transpose.
Definition at line 201 of file matrix.c.
References _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
                                   {
    matrix* out = makeMatrix(m->height, m->width);
    double* ptrOut;
    double* ptrM = m->data;
    int i, j;
    for (i = 0; i < m->height; i++) {
        ptrOut = &out->data[i];
        for (j = 0; j < m->width; j++) {
            *ptrOut = *ptrM;
            ptrM++;
            ptrOut += out->width;
        }
    }
    return out;
}