include/matrix.h File Reference
Various Matrix operations.
None of the matrix operations below change the input matrices if an input is required. They all return a new matrix with the new changes. Because memory issues are so prevelant, be sure to use the function to reclaim some of that memory.
Data Structures
struct _matrix
Typedefs
typedef struct _matrix matrix
Functions
void assert (int assertion, const char *message)
Asserts a condition is true.
 matrix * copyMatrix (matrix *m)
Copies a matrix. This function uses scaleMatrix, because scaling matrix by 1 is the same as a copy.
 matrix * covarianceMatrix (matrix *m)
returns the covariance of the matrix
 matrix * dotDiagonalMatrix (matrix *a, matrix *b)
performs a diagonial matrix dot product. Given a two matrices (or the same matrix twice) with identical widths and heights, this method returns a 1 by a->height matrix of the cross product of each matrix along the diagonal.
 matrix * dotProductMatrix (matrix *a, matrix *b)
returns the matrix dot product. Given a two matrices (or the same matrix twice) with identical widths and different heights, this method returns a a->height by b->height matrix of the cross product of each matrix.
void freeMatrix (matrix *m)
Frees the resources of a matrix.
 matrix * identityMatrix (int n)
Returns an identity matrix of size n by n.
 matrix * makeMatrix (int width, int height)
Makes a matrix with a width and height parameters.
 matrix * meanMatrix (matrix *m)
Given an `m rows by n columns` matrix, return a matrix where each element represents the mean of that full column. the matrix.
 matrix * multiplyMatrix (matrix *a, matrix *b)
Given a two matrices, returns the multiplication of the two.
void printMatrix (matrix *m)
Prints a matrix.
void rowSwap (matrix *a, int p, int q)
swaps the rows of a matrix. This method changes the input matrix. Given a matrix, this algorithm will swap rows p and q, provided that p and q are less than or equal to the height of matrix A and p and q are different values.
 matrix * scaleMatrix (matrix *m, double value)
scales a matrix.
double traceMatrix (matrix *m)
Given an `m rows by n columns` matrix.
 matrix * transposeMatrix (matrix *m)
returns the transpose matrix.
Detailed Description
Various Matrix operations.
None of the matrix operations below change the input matrices if an input is required. They all return a new matrix with the new changes. Because memory issues are so prevelant, be sure to use the function to reclaim some of that memory.
Definition in file matrix.h.
Typedef Documentation
matrix
typedef struct _matrix matrix
A struct representing a matrix
Function Documentation
assert()
void assert (int assertion, const char * message)
Asserts a condition is true.
If the assertion is non-zero (i.e. true), then it returns. If the assertion is zero (i.e. false), then it display the string and aborts the program. This is ment to act like Python's assert keyword.
Definition at line 14 of file matrix.c.
Referenced by covarianceMatrix(), dotDiagonalMatrix(), dotProductMatrix(), identityMatrix(), makeMatrix(), meanMatrix(), multiplyMatrix(), and rowSwap().
                                                {
    if (assertion == 0) {
        fprintf(stderr, "%s\n", message);
        exit(1);
    }
}
copyMatrix()
 matrix* copyMatrix (matrix * m)
Copies a matrix. This function uses scaleMatrix, because scaling matrix by 1 is the same as a copy.
Parameters
m a pointer to the matrix
Returns
a copied matrix
Definition at line 52 of file matrix.c.
References scaleMatrix().
                              {
    return scaleMatrix(m, 1);
}
covarianceMatrix()
 matrix* covarianceMatrix (matrix * m)
returns the covariance of the matrix
Parameters
the matrix
Returns
a matrix with n row and n columns, where each element represents covariance of 2 columns.
Definition at line 168 of file matrix.c.
References assert(), _matrix::data, freeMatrix(), _matrix::height, makeMatrix(), meanMatrix(), and _matrix::width.
                                    {
    int i, j, k = 0;
    matrix* out;
    matrix* mean;
    double* ptrA;
    double* ptrB;
    double* ptrOut;
    assert(m->height > 1, "Height of matrix cannot be zero or one.");
    mean = meanMatrix(m);
    out = makeMatrix(m->width, m->width);
    ptrOut = out->data;
    for (i = 0; i < m->width; i++) {
        for (j = 0; j < m->width; j++) {
             ptrA = &m->data[i];
             ptrB = &m->data[j];
             *ptrOut = 0.0;
             for (k = 0; k < m->height; k++) {
                 *ptrOut += (*ptrA - mean->data[i]) * (*ptrB - mean->data[j]);
                 ptrA += m->width;
                 ptrB += m->width;
             }
             *ptrOut /= m->height - 1;
             ptrOut++;
        }
    }
    freeMatrix(mean);
    return out;
}
dotDiagonalMatrix()
 matrix* dotDiagonalMatrix (matrix * a, matrix * b)
performs a diagonial matrix dot product. Given a two matrices (or the same matrix twice) with identical widths and heights, this method returns a 1 by a->height matrix of the cross product of each matrix along the diagonal.
Dot product is essentially the sum-of-squares of two vectors.
If the second paramter is NULL, it is assumed that we are performing a cross product with itself.
Parameters
a the first matrix
b the second matrix
Returns
the matrix result
Definition at line 385 of file matrix.c.
References assert(), _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
                                                {
    matrix* out;
    double* ptrOut;
    double* ptrA;
    double* ptrB;
    int i, j;
    if (b != NULL) {
        assert(a->width == b->width && a->height == b->height, "Matrices must be of the same
       dimensionality.");
    }
    // Are we computing the sum of squares of the same matrix?
    if (a == b || b == NULL) {
        b = a; // May not appear safe, but we can do this without risk of losing b.
    }
    out = makeMatrix(1, a->height);
    ptrOut = out->data;
    ptrA = a->data;
    ptrB = b->data;
    for (i = 0; i < a->height; i++) {
        *ptrOut = 0;
        for (j = 0; j < a->width; j++) {
            *ptrOut += *ptrA * *ptrB;
            ptrA++;
            ptrB++;
        }
        ptrOut++;
    }
    return out;
}
dotProductMatrix()
 matrix* dotProductMatrix (matrix * a, matrix * b)
returns the matrix dot product. Given a two matrices (or the same matrix twice) with identical widths and different heights, this method returns a a->height by b->height matrix of the cross product of each matrix.
Dot product is essentially the sum-of-squares of two vectors.
Also, if the second paramter is NULL, it is assumed that we are performing a cross product with itself.
Parameters
a the first matrix
the second matrix
Returns
the result of the dot product
Definition at line 333 of file matrix.c.
References assert(), _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
                                               {
    matrix* out;
    double* ptrOut;
    double* ptrA;
    double* ptrB;
    int i, j, k;
    if (b != NULL) {
        assert(a->width == b->width, "Matrices must be of the same dimensionality.");
    }
    // Are we computing the sum of squares of the same matrix?
    if (a == b || b == NULL) {
        b = a; // May not appear safe, but we can do this without risk of losing b.
    }
    out = makeMatrix(b->height, a->height);
    ptrOut = out->data;
    for (i = 0; i < a->height; i++) {
        ptrB = b->data;
        for (j = 0; j < b->height; j++) {
            ptrA = &a->data[ i * a->width ];
            *ptrOut = 0;
            for (k = 0; k < a->width; k++) {
                *ptrOut += *ptrA * *ptrB;
                ptrA++;
                ptrB++;
            }
            ptrOut++;
        }
    }
    return out;
}
freeMatrix()
void freeMatrix (matrix * m)
Frees the resources of a matrix.
Parameters
the matrix to free
Definition at line 60 of file matrix.c.
References _matrix::data.
Referenced by covarianceMatrix().
                           {
    if (m != NULL) {
        if (m->data != NULL) {
            free(m->data);
            m->data = NULL;
        }
        free(m);
    }
    return;
}
identityMatrix()
 matrix* identityMatrix (int n)
Returns an identity matrix of size n by n.
Parameters
n the input matrix. parameter.
n the input matrix.
Returns
the identity matrix parameter.
Definition at line 94 of file matrix.c.
References assert(), _matrix::data, and makeMatrix().
                              {
    int i;
    matrix *out;
    double* ptr;
    assert(n > 0, "Identity matrix must have value greater than zero.");
    out = makeMatrix(n, n);
    ptr = out->data;
    for (i = 0; i < n; i++) {
        *ptr = 1.0;
        ptr += n + 1;
    }
    return out;
}
makeMatrix()
 matrix* makeMatrix (int width, int height)
Makes a matrix with a width and height parameters.
Parameters
width The width of the matrix
height the height of the matrix
Returns
the new matrix
Definition at line 27 of file matrix.c.
References assert(), _matrix::data, _matrix::height, and _matrix::width.
Referenced by covarianceMatrix(), dotDiagonalMatrix(), dotProductMatrix(), identityMatrix(), init_localization(), meanMatrix(), multiplyMatrix(), scaleMatrix(), and transposeMatrix().
                                          {
    matrix* out;
    assert(width > 0 && height > 0, "New matrix must be at least a 1 by 1");
    out = (matrix*) malloc(sizeof(matrix));
    assert(out != NULL, "Out of memory.");
    out->width = width;
    out->height = height;
    out->data = (double*) malloc(sizeof(double) * width * height);
    assert(out->data != NULL, "Out of memory.");
    memset(out->data, 0.0, width * height * sizeof(double));
    return out;
}
meanMatrix()
 matrix* meanMatrix (matrix * m)
Given an `m rows by n columns` matrix, return a matrix where each element represents the mean of that full column. the matrix.
Returns
matrix with 1 row and n columns each element represents the mean of that full column.
Definition at line 142 of file matrix.c.
References assert(), _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
Referenced by covarianceMatrix().
                              {
    int i, j;
    matrix* out;
    assert(m->height > 0, "Height of matrix cannot be zero.");
    out = makeMatrix(m->width, 1);
    for (i = 0; i < m->width; i++) {
        double* ptr;
        out->data[i] = 0.0;
        ptr = &m->data[i];
        for (j = 0; j < m->height; j++) {
            out->data[i] += *ptr;
            ptr += out->width;
        }
        out->data[i] /= (double) m->height;
    }
    return out;
}
multiplyMatrix()
 matrix* multiplyMatrix (matrix * a, matrix * b)
Given a two matrices, returns the multiplication of the two.
Parameters
a the first matrix
b the seconf matrix return the result of the multiplication
Definition at line 230 of file matrix.c.
References assert(), _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
                                             {
    int i, j, k;
    matrix* out;
    double* ptrOut;
    double* ptrA;
    double* ptrB;
    assert(a->width == b->height, "Matrices have incorrect dimensions. a->width != b->height");
    out = makeMatrix(b->width, a->height);
    ptrOut = out->data;
    for (i = 0; i < a->height; i++) {
        for (j = 0; j < b->width; j++) {
            ptrA = &a->data[ i * a->width ];
            ptrB = &b->data[ j ];
            *ptrOut = 0;
            for (k = 0; k < a->width; k++) {
                *ptrOut += *ptrA * *ptrB;
                ptrA++;
                ptrB += b->width;
            }
            ptrOut++;
        }
    }
    return out;
}
printMatrix()
void printMatrix (matrix * m)
Prints a matrix.
Parameters
the matrix
Definition at line 75 of file matrix.c.
References _matrix::data, _matrix::height, and _matrix::width.
                            {
    int i, j;
    double* ptr = m->data;
    printf("%d %d\n", m->width, m->height);
    for (i = 0; i < m->height; i++) {
        for (j = 0; j < m->width; j++) {
            printf(" %9.6f", *(ptr++));
        }
        printf("\n");
    }
    return;
}
rowSwap()
void rowSwap (matrix * a, int p, int q)
swaps the rows of a matrix. This method changes the input matrix. Given a matrix, this algorithm will swap rows p and q, provided that p and q are less than or equal to the height of matrix A and p and q are different values.
Parameters
the matrix to swap. This method changes the input matrix.
the first row
the second row
Definition at line 290 of file matrix.c.
References assert(), _matrix::data, _matrix::height, and _matrix::width.
                                      {
    int i;
    double temp;
    double* pRow;
    double* qRow;
    assert(a->height > 2, "Matrix must have at least two rows to swap.");
    assert(p < a->height && q < a->height, "Values p and q must be less than the height of the matrix.");
    // If p and q are equal, do nothing.
    if (p == q) {
        return;
    }
    pRow = a->data + (p * a->width);
    qRow = a->data + (q * a->width);
    // Swap!
    for (i = 0; i < a->width; i++) {
        temp = *pRow;
        *pRow = *qRow;
        *qRow = temp;
        pRow++;
        qRow++;
    }
    return;
}
scaleMatrix()
 matrix* scaleMatrix (matrix * m, double value)
scales a matrix.
Parameters
m the matrix to scale
the value to scale by
Returns
a new matrix where each element in the input matrix is multiplied by the scalar value
Definition at line 268 of file matrix.c.
References _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
Referenced by copyMatrix().
                                             {
    int i, elements = m->width * m->height;
    matrix* out = makeMatrix(m->width, m->height);
    double* ptrM = m->data;
    double* ptrOut = out->data;
    for (i = 0; i < elements; i++) {
        *(ptrOut++) = *(ptrM++) * value;
    }
    return out;
}
traceMatrix()
double traceMatrix (matrix * m)
Given an `m rows by n columns` matrix.
Returns
the sum of the elements along the diagonal.
Given an `m rows by n columns` matrix.
Returns
the sum of the elements along the diagonal.
Definition at line 116 of file matrix.c.
References _matrix::data, _matrix::height, and _matrix::width.
                              {
    int i;
    int size;
    double* ptr = m->data;
    double sum = 0.0;
    if (m->height < m->width) {
        size = m->height;
    }
    else {
        size = m->width;
    }
    for (i = 0; i < size; i++) {
        sum += *ptr;
        ptr += m->width + 1;
    }
    return sum;
}
transposeMatrix()
 matrix* transposeMatrix (matrix * m)
returns the transpose matrix.
Parameters
the matrix to transpose.
Returns
the transposed matrix.
Definition at line 206 of file matrix.c.
References _matrix::data, _matrix::height, makeMatrix(), and _matrix::width.
                                   {
    matrix* out = makeMatrix(m->height, m->width);
    double* ptrM = m->data;
    int i, j;
    for (i = 0; i < m->height; i++) {
        double* ptrOut;
        ptrOut = &out->data[i];
        for (j = 0; j < m->width; j++) {
            *ptrOut = *ptrM;
            ptrM++;
            ptrOut += out->width;
        }
    }
    return out;
}