include/menu.h File Reference
Contains menu functionality and abstraction.
#include `lcd.h`
#include `API.h`
#include <string.h>
#include <limits.h>
#include <float.h>
#include <vlib.h>
#include `log.h`
Data Structures
struct menu_t
Represents a specific instance of a menu. Will cause a memory leak if not deinitialized via denint_menu.
Typedefs
typedef struct menu_t menu_t
Represents a specific instance of a menu. Will cause a memory leak if not deinitialized via denint_menu.
Enumerations
enum menu_type { INT_TYPE,
 FLOAT_TYPE,
 STRING_TYPE
 }
Represents the different types of menus.
Functions
static void calculate_current_display (char *rtn, menu_t *menu)
Static function that calculates the string from menu.
static menu_t * create_menu (enum menu_type type, const char *prompt)
Static function that handles creation of menu. Menu must be freed or will cause memory leak
void denint_menu (menu_t *menu)
Destroys a menu Menu must be freed or will cause memory leak
int display_menu (menu_t *menu)
Displays a menu contex. Menu must be freed or will cause memory leak! Will exit if robot is enabled. This prevents menu from locking up system in even of a reset.
 menu_t * init_menu_float (enum menu_type type, float min, float max, float step, const char *prompt)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak!
 menu_t * init_menu_int (enum menu_type type, int min, int max, int step, const char *prompt)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak
 menu_t * init_menu_var (enum menu_type type, const char *prompt, int nums,...)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak
Detailed Description
Contains menu functionality and abstraction.
Author
Chris Jerrett
Date
9/9/2017
Definition in file menu.h.
Typedef Documentation
menu_t
typedef struct menu_t menu_t
Represents a specific instance of a menu. Will cause a memory leak if not deinitialized via denint_menu.
Author
Chris Jerrett
Date
9/8/17
See also
menu.h
menu_t
create_menu
init_menu
display_menu
menu_type
denint_menu
Enumeration Type Documentation
menu_type
enum menu_type
Represents the different types of menus.
Author
Chris Jerrett
Date
9/8/17
See also
menu.h
menu_t
create_menu
init_menu
display_menu
menu_type
Enumerator
INT_TYPE Menu type allowing user to select a integer. The integer type menu has a max, min and a step value. Each step is calculated. Will return the index of the selected value. Example: User goes forwards twice then it will return 2.
FLOAT_TYPE Menu type allowing user to select a float The float type menu has a max, min and a step value. Each step is calculated. Will return the index of the selected value. Example: User goes forwards twice then it will return 2.
STRING_TYPE Menu type allowing user to select a string from a array of strings. Will return the index of the selected value. Example: User goes forwards twice then it will return 2.
Definition at line 31 of file menu.h.
               {
  INT_TYPE,
  FLOAT_TYPE,
  STRING_TYPE
};
Function Documentation
calculate_current_display()
static void calculate_current_display (char * rtn, menu_t * menu) [static]
Static function that calculates the string from menu.
Parameters
rtn the string to be written to
menu the menu for prompt to be calculated from
Author
Chris Jerrett
Date
9/8/17
create_menu()
static menu_t* create_menu (enum menu_type type, const char * prompt) [static]
Static function that handles creation of menu. Menu must be freed or will cause memory leak
Author
Chris Jerrett
Date
9/8/17
denint_menu()
void denint_menu (menu_t * menu)
Destroys a menu Menu must be freed or will cause memory leak
Parameters
menu the menu to free
See also
menu
Author
Chris Jerrett
Date
9/8/17
Definition at line 186 of file menu.c.
References menu_t::options, and menu_t::prompt.
                              {
  free(menu->prompt);
  if(menu->options != NULL) free(menu->options);
  free(menu);
}
display_menu()
int display_menu (menu_t * menu)
Displays a menu contex. Menu must be freed or will cause memory leak! Will exit if robot is enabled. This prevents menu from locking up system in even of a reset.
Parameters
menu the menu to display
See also
menu_type
Author
Chris Jerrett
Date
9/8/17
Definition at line 148 of file menu.c.
References calculate_current_display(), menu_t::current, lcd_clear(), lcd_get_pressed_buttons(), lcd_print(), PRESSED, menu_t::prompt, RELEASED, and TOP_ROW.
Referenced by initialize().
                              {
  lcd_print(TOP_ROW, menu->prompt);
  printf("printed prompt\n");
  //Will exit if teleop or autonomous begin. This is extremely important if robot disconnects or resets.
  char val[16];
  while(lcd_get_pressed_buttons().middle == RELEASED) {
    calculate_current_display(val, menu);
    if(lcd_get_pressed_buttons().right == PRESSED) {
      menu->current += 1;
    }
    if(lcd_get_pressed_buttons().left == PRESSED) {
      menu->current -= 1;
    }
    printf("%s\n", val);
    printf("%d\n",menu->current);
    lcd_print(2, val);
    delay(300);
  }
  printf("%d\n", menu->current);
  printf("return\n");
  lcd_clear();
  lcd_print(1, "Thk Cm Agn");
  lcd_print(2, val);
  delay(800);
  lcd_clear();
  return menu->current;
}
init_menu_float()
 menu_t* init_menu_float (enum menu_type type, float min, float max, float step, const char * prompt)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak!
Parameters
type the type of menu
See also
menu_type
Parameters
min the minimum value
max the maximum value
step the step value
prompt the prompt to display to user
Author
Chris Jerrett
Date
9/8/17
Definition at line 95 of file menu.c.
References create_menu(), max(), menu_t::max_f, min(), menu_t::min_f, and menu_t::step_f.
                                                                                                  {
  menu_t* menu = create_menu(type, prompt);
  menu->min_f = min;
  menu->max_f = max;
  menu->step_f = step;
  return menu;
}
init_menu_int()
 menu_t* init_menu_int (enum menu_type type, int min, int max, int step, const char * prompt)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak
Parameters
type the type of menu
See also
menu_type
Parameters
min the minimum value
max the maximum value
step the step value
prompt the prompt to display to user
Author
Chris Jerrett
Date
9/8/17
Definition at line 73 of file menu.c.
References create_menu(), menu_t::current, max(), menu_t::max, min(), menu_t::min, and menu_t::step.
                                                                                          {
  menu_t* menu = create_menu(type, prompt);
  menu->min = min;
  menu->max = max;
  menu->step = step;
  menu->current = 0;
  return menu;
}
init_menu_var()
 menu_t* init_menu_var (enum menu_type type, const char * prompt, int nums, ...)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak
Parameters
type the type of menu
See also
menu_type
Parameters
nums the number of elements passed to function
prompt the prompt to display to user
options the options to display for user
Author
Chris Jerrett
Date
9/8/17
Definition at line 45 of file menu.c.
References create_menu(), menu_t::length, and menu_t::options.
Referenced by initialize().
                                                                            {
  menu_t* menu = create_menu(type, prompt);
  va_list ap;
  char **options_array = (char**)calloc(sizeof(char*), nums);
  va_start(ap, nums);
  for(int i = 0; i < nums; i++){
    options_array[i] = (char*) va_arg(ap, char*);
    printf("%s\n", options_array[i]);
  }
  va_end(ap);
  menu->options = options_array;
  menu->length = nums;
  return menu;
}