src/menu.c File Reference
#include `menu.h`
Functions
static void calculate_current_display (char *rtn, menu_t *menu)
static menu_t * create_menu (enum menu_type type, const char *prompt)
Static function that handles creation of menu. Menu must be freed or will cause memory leak
void denint_menu (menu_t *menu)
Destroys a menu Menu must be freed or will cause memory leak
int display_menu (menu_t *menu)
Displays a menu contex. Menu must be freed or will cause memory leak! Will exit if robot is enabled. This prevents menu from locking up system in even of a reset.
 menu_t * init_menu_float (enum menu_type type, float min, float max, float step, const char *prompt)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak!
 menu_t * init_menu_int (enum menu_type type, int min, int max, int step, const char *prompt)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak
 menu_t * init_menu_var (enum menu_type type, const char *prompt, int nums,...)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak
Function Documentation
calculate_current_display()
static void calculate_current_display (char * rtn, menu_t * menu) [static]
Definition at line 103 of file menu.c.
References menu_t::current, FLOAT_TYPE, ftoaa(), INT_TYPE, menu_t::length, max(), menu_t::max, menu_t::max_f, min(), menu_t::min, menu_t::min_f, menu_t::options, menu_t::step, menu_t::step_f, STRING_TYPE, and menu_t::type.
Referenced by display_menu().
                                                               {
  if(menu->type == STRING_TYPE){
  int index = menu->current % menu->length;
  sprintf(rtn, "%s", menu->options[index]);
  printf("%s\n", rtn);
  return;
  }
  if(menu->type == INT_TYPE) {
    int step = (menu->step);
    int min = (menu->min);
    int max = (menu->max);
    int value = menu->current * step;
    if(value < min) {
      value = min;
      menu->current++;
    }
    if(value > max) {
      value = max;
      menu->current--;
    }
    sprintf(rtn, "%d", value);
  }
  if(menu->type == FLOAT_TYPE) {
    float step = (menu->step_f);
    float min = (menu->min_f);
    float max = (menu->max_f);
    float value = menu->current * step;
    value = value < min ? min : value;
    value = value > max ? max : value;
    ftoaa(value, rtn, 5);
  }
}
create_menu()
static menu_t * create_menu (enum menu_type type, const char * prompt) [static]
Static function that handles creation of menu. Menu must be freed or will cause memory leak
Author
Chris Jerrett
Date
9/8/17
Definition at line 12 of file menu.c.
References menu_t::current, error(), menu_t::max, menu_t::max_f, menu_t::min, menu_t::min_f, menu_t::prompt, menu_t::step, menu_t::step_f, and menu_t::type.
Referenced by init_menu_float(), init_menu_int(), and init_menu_var().
                                                                    {
  menu_t* menu = (menu_t*) malloc(sizeof(menu_t));
  if (!menu) {
    error("Menu Malloc");
  }
  menu->type = type;
  // Add one for null terminator
  size_t strlength = strlen(prompt) + 1;
  menu->prompt = (char*) malloc(strlength * sizeof(char));
  memcpy(menu->prompt, prompt, strlength);
  menu->max = INT_MAX;
  menu->min = INT_MIN;
  menu->step = 1;
  menu->min_f = FLT_MIN;
  menu->max_f = FLT_MAX;
  menu->step_f = 1;
  menu->current = 0;
  return menu;
}
denint_menu()
void denint_menu (menu_t * menu)
Destroys a menu Menu must be freed or will cause memory leak
Parameters
menu the menu to free
See also
menu
Author
Chris Jerrett
Date
9/8/17
Definition at line 186 of file menu.c.
References menu_t::options, and menu_t::prompt.
                              {
  free(menu->prompt);
  if(menu->options != NULL) free(menu->options);
  free(menu);
}
display_menu()
int display_menu (menu_t * menu)
Displays a menu contex. Menu must be freed or will cause memory leak! Will exit if robot is enabled. This prevents menu from locking up system in even of a reset.
Parameters
menu the menu to display
See also
menu_type
Author
Chris Jerrett
Date
9/8/17
Definition at line 148 of file menu.c.
References calculate_current_display(), menu_t::current, lcd_clear(), lcd_get_pressed_buttons(), lcd_print(), PRESSED, menu_t::prompt, RELEASED, and TOP_ROW.
Referenced by initialize().
                              {
  lcd_print(TOP_ROW, menu->prompt);
  printf("printed prompt\n");
  //Will exit if teleop or autonomous begin. This is extremely important if robot disconnects or resets.
  char val[16];
  while(lcd_get_pressed_buttons().middle == RELEASED) {
    calculate_current_display(val, menu);
    if(lcd_get_pressed_buttons().right == PRESSED) {
      menu->current += 1;
    }
    if(lcd_get_pressed_buttons().left == PRESSED) {
      menu->current -= 1;
    }
    printf("%s\n", val);
    printf("%d\n",menu->current);
    lcd_print(2, val);
    delay(300);
  }
  printf("%d\n", menu->current);
  printf("return\n");
  lcd_clear();
  lcd_print(1, "Thk Cm Agn");
  lcd_print(2, val);
  delay(800);
  lcd_clear();
  return menu->current;
}
init_menu_float()
 menu_t* init_menu_float (enum menu_type type, float min, float max, float step, const char * prompt)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak!
Parameters
type the type of menu
See also
menu_type
Parameters
min the minimum value
max the maximum value
step the step value
prompt the prompt to display to user
Author
Chris Jerrett
Date
9/8/17
Definition at line 95 of file menu.c.
References create_menu(), max(), menu_t::max_f, min(), menu_t::min_f, and menu_t::step_f.
                                                                                                  {
  menu_t* menu = create_menu(type, prompt);
  menu->min_f = min;
  menu->max_f = max;
  menu->step_f = step;
  return menu;
}
init_menu_int()
 menu_t* init_menu_int (enum menu_type type, int min, int max, int step, const char * prompt)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak
Parameters
type the type of menu
See also
menu_type
Parameters
min the minimum value
max the maximum value
step the step value
prompt the prompt to display to user
Author
Chris Jerrett
Date
9/8/17
Definition at line 73 of file menu.c.
References create_menu(), menu_t::current, max(), menu_t::max, min(), menu_t::min, and menu_t::step.
                                                                                          {
  menu_t* menu = create_menu(type, prompt);
  menu->min = min;
  menu->max = max;
  menu->step = step;
  menu->current = 0;
  return menu;
}
init_menu_var()
 menu_t* init_menu_var (enum menu_type type, const char * prompt, int nums, ...)
Creates a menu context, but does not display. Menu must be freed or will cause memory leak
Parameters
type the type of menu
See also
menu_type
Parameters
nums the number of elements passed to function
prompt the prompt to display to user
options the options to display for user
Author
Chris Jerrett
Date
9/8/17
Definition at line 45 of file menu.c.
References create_menu(), menu_t::length, and menu_t::options.
Referenced by initialize().
                                                                            {
  menu_t* menu = create_menu(type, prompt);
  va_list ap;
  char **options_array = (char**)calloc(sizeof(char*), nums);
  va_start(ap, nums);
  for(int i = 0; i < nums; i++){
    options_array[i] = (char*) va_arg(ap, char*);
    printf("%s\n", options_array[i]);
  }
  va_end(ap);
  menu->options = options_array;
  menu->length = nums;
  return menu;
}