src/mobile_goal_intake.c File Reference
#include `mobile_goal_intake.h`
#include `partner.h`
Functions
static void lower_intake ()
static void raise_intake ()
static void set_intake_motor (int n)
void updateIntake ()
updates the mobile goal intake in teleop.
Function Documentation
lower_intake()
static void lower_intake () [static]
Definition at line 8 of file mobile_goal_intake.c.
References set_intake_motor().
Referenced by updateIntake().
                           {
  set_intake_motor(100);
}
raise_intake()
static void raise_intake () [static]
Definition at line 12 of file mobile_goal_intake.c.
References set_intake_motor().
Referenced by updateIntake().
                           {
  set_intake_motor(-100);
}
set_intake_motor()
static void set_intake_motor (int n) [static]
Definition at line 4 of file mobile_goal_intake.c.
References INTAKE_MOTOR, and set_motor_immediate().
Referenced by lower_intake(), raise_intake(), and updateIntake().
                                    {
  set_motor_immediate(INTAKE_MOTOR, n);
}
updateIntake()
void updateIntake ()
updates the mobile goal intake in teleop.
Definition at line 16 of file mobile_goal_intake.c.
References get_mode(), JOY_DOWN, JOY_UP, joystickGetDigital(), lower_intake(), MAIN_CONTROLLER_MODE, MASTER, PARTNER, PARTNER_CONTROLLER_MODE, raise_intake(), and set_intake_motor().
Referenced by operatorControl().
                    {
  if(joystickGetDigital(MASTER, 7, JOY_UP) && (get_mode() ==
      MAIN_CONTROLLER_MODE)
  || joystickGetDigital(PARTNER, 6, JOY_UP) && get_mode() ==
      PARTNER_CONTROLLER_MODE) {
    raise_intake();
  }
  else if(joystickGetDigital(MASTER, 7, JOY_DOWN) && (get_mode() ==
      MAIN_CONTROLLER_MODE)
  || joystickGetDigital(PARTNER, 6, JOY_DOWN) && get_mode() ==
      PARTNER_CONTROLLER_MODE){
    lower_intake();
  }
  else set_intake_motor(0);
}