src/partner.c File Reference
#include `partner.h`
Functions
enum CONTROLL_MODE get_mode ()
void update_control ()
Updates the controller mode between Driver and Partner modes.
Variables
static enum CONTROLL_MODE mode = MAIN_CONTROLLER_MODE
Function Documentation
get_mode()
enum CONTROLL_MODE get_mode ()
Definition at line 5 of file partner.c.
References mode.
Referenced by update_drive_motors(), update_lifter(), and updateIntake().
                              {
  return mode;
}
update_control()
void update_control ()
Updates the controller mode between Driver and Partner modes.
Author
Chris Jerrett
Definition at line 9 of file partner.c.
References MAIN_CONTROLLER_MODE, mode, PARTNER, and PARTNER_CONTROLLER_MODE.
Referenced by operatorControl().
                      {
  if(joystickGetDigital(PARTNER, 7, JOY_LEFT)) {
    mode = MAIN_CONTROLLER_MODE;
  } else if(joystickGetDigital(PARTNER, 7, JOY_RIGHT)) {
    mode = PARTNER_CONTROLLER_MODE;
  }
}
Variable Documentation
mode
enum CONTROLL_MODE mode = MAIN_CONTROLLER_MODE [static]
Definition at line 3 of file partner.c.
Referenced by get_mode(), and update_control().