include/partner.h File Reference
#include `controller.h`
#include `API.h`
Enumerations
enum CONTROLL_MODE { MAIN_CONTROLLER_MODE,
PARTNER_CONTROLLER_MODE
 }
Functions
enum CONTROLL_MODE get_mode ()
void update_control ()
Enumeration Type Documentation
CONTROLL_MODE
enum CONTROLL_MODE
Enumerator
MAIN_CONTROLLER_MODE
PARTNER_CONTROLLER_MODE
Definition at line 7 of file partner.h.
                   {
  MAIN_CONTROLLER_MODE,
  PARTNER_CONTROLLER_MODE
};
Function Documentation
get_mode()
enum CONTROLL_MODE get_mode ()
Definition at line 5 of file partner.c.
References mode.
Referenced by update_drive_motors(), update_lifter(), and updateIntake().
                              {
  return mode;
}
update_control()
void update_control ()
Definition at line 9 of file partner.c.
References delay(), JOY_LEFT, JOY_RIGHT, joystickGetDigital(), MAIN_CONTROLLER_MODE, mode, PARTNER, and PARTNER_CONTROLLER_MODE.
Referenced by operatorControl().
                      {
  delay(10);
  if(joystickGetDigital(PARTNER, 7, JOY_LEFT)) {
    mode = MAIN_CONTROLLER_MODE;
  } else if(joystickGetDigital(PARTNER, 7, JOY_RIGHT)) {
    mode = PARTNER_CONTROLLER_MODE;
  }
}