include/routines.h File Reference
Data Structures
struct routine_t
Routine system that allows mapping buttons to actions.
Typedefs
typedef struct routine_t routine_t
Routine system that allows mapping buttons to actions.
Functions
void deinit_routines ()
Stops the routine system.
void init_routine ()
Starts the routine system.
void register_routine (void(*routine)(void *), button_t on_buttons, button_t *prohibited_buttons)
Registers a routine for the system to use.
void routine_task ()
Task that manages routines.
Typedef Documentation
routine_t
typedef struct routine_t routine_t
Routine system that allows mapping buttons to actions.
Author
Chris Jerrett
Date
1/8/17 Struct representing a routine
Function Documentation
deinit_routines()
void deinit_routines ()
Stops the routine system.
Author
Chris Jerrett
Definition at line 47 of file routines.c.
References list_destroy().
{ list_destroy(routine_list); }
init_routine()
void init_routine ()
Starts the routine system.
Author
Chris Jerrett
Definition at line 38 of file routines.c.
References list_new(), routine_task(), routine_task_var, and taskRunLoop().
Referenced by operatorControl().
                    {
  routine_list = list_new();
  routine_task_var = taskRunLoop(routine_task, 20);
}
register_routine()
void register_routine (void(*)(void *) routine, button_t on_buttons, button_t * prohibited_buttons)
Registers a routine for the system to use.
Parameters
routine The routine to register
on_buttons the trigger button
prohibited_buttons the buttons it blocks
Todo
 Todo
Parameters
routine The routine to register
on_buttons the trigger button
prohibited_buttons the buttons it blocks
Todo
 Todo
Author
Chris Jerrett
Definition at line 56 of file routines.c.
References routine_t::blocked_buttons, list_node_new(), list_rpush(), routine_t::on_button, routine_t::routine, and list_node::val.
Referenced by operatorControl().
                                                    {
  struct routine_t *r = (struct routine_t *)malloc(sizeof(routine_t));
  r->blocked_buttons = prohibited_buttons;
  r->routine = routine;
  r->on_button = on_buttons;
  list_node_t *node = list_node_new(r);
  node->val = r;
  list_rpush(routine_list, node);
}
routine_task()
void routine_task ()
Task that manages routines.
Author
Chris Jerrett
Definition at line 14 of file routines.c.
References buttonIsNewPress(), error(), LIST_HEAD, list_iterator_destroy(), list_iterator_new(), list_iterator_next(), routine_t::on_button, routine_t::routine, taskCreate(), and list_node::val.
Referenced by init_routine().
                    {
  list_node_t *node;
  list_iterator_t *it = list_iterator_new(routine_list, LIST_HEAD);
  if (it != NULL) {
    while (node = list_iterator_next(it)) {
      if (node->val != NULL) {
        routine_t *routine = (routine_t *)(node->val);
        if (buttonIsNewPress(routine->on_button)) {
          TaskHandle task =
              taskCreate(routine->routine, TASK_DEFAULT_STACK_SIZE, NULL,
                         TASK_PRIORITY_DEFAULT);
        }
      }
    }
  } else {
    error("List iterator was null");
  }
  list_iterator_destroy(it);
}