include/slew.h File Reference
Contains the slew rate controller wrapper for the motors.
#include <API.h>
#include <math.h>
#include <vlib.h>
Macros
#define MOTOR_PORTS 12
The number of motor ports on the robot.
#define RAMP_PROPORTION 1
proportion defining how quickly the motor should converge on the correct value. higher value leads to slower convergence
#define UPDATE_PERIOD_MS 25
How frequently to update the motors, in milliseconds.
Functions
void deinitslew ()
Deinitializes the slew rate controller and frees memory.
void init_slew ()
Initializes the slew rate controller.
void set_motor_immediate (int motor, int speed)
Sets the motor speed ignoring the slew controller.
void set_motor_slew (int motor, int speed)
Sets motor speed wrapped inside the slew rate controller.
void updateMotors ()
Closes the distance between the desired motor value and the current motor value by half for each motor.
Detailed Description
Contains the slew rate controller wrapper for the motors.
Author
Chris Jerrett
Date
9/14/17
Definition in file slew.h.
Macro Definition Documentation
MOTOR_PORTS
#define MOTOR_PORTS 12
The number of motor ports on the robot.
Author
Christian DeSimone
Date
9/14/17
Definition at line 27 of file slew.h.
RAMP_PROPORTION
#define RAMP_PROPORTION 1
proportion defining how quickly the motor should converge on the correct value. higher value leads to slower convergence
Author
Chris Jerrett
Date
9/14/17
Definition at line 34 of file slew.h.
UPDATE_PERIOD_MS
#define UPDATE_PERIOD_MS 25
How frequently to update the motors, in milliseconds.
Author
Chris Jerrett
Date
9/14/17
Definition at line 20 of file slew.h.
Function Documentation
deinitslew()
void deinitslew ()
Deinitializes the slew rate controller and frees memory.
Author
Chris Jerrett
Date
9/14/17
Definition at line 58 of file slew.c.
References initialized, motors_curr_speeds, motors_set_speeds, and slew.
Referenced by autonomous().
                 {
  taskDelete(slew);
  memset(motors_set_speeds, 0, sizeof(int) * 10);
  memset(motors_curr_speeds, 0, sizeof(int) * 10);
  initialized = false;
}
init_slew()
void init_slew ()
Initializes the slew rate controller.
Author
Chris Jerrett, Christian DeSimone
Date
9/14/17
Definition at line 40 of file slew.c.
References info(), initialized, motors_curr_speeds, motors_set_speeds, slew, speeds_mutex, updateMotors(), and warning().
Referenced by autonomous(), operatorControl(), set_motor_immediate(), and set_motor_slew().
                {
  if(initialized) {
    warning("Trying to init already init slew");
  }
  memset(motors_set_speeds, 0, sizeof(int) * 10);
  memset(motors_curr_speeds, 0, sizeof(int) * 10);
  motorStopAll();
  info("Did Init Slew");
  speeds_mutex = mutexCreate();
  slew = taskRunLoop(updateMotors, 100);
  initialized = true;
}
set_motor_immediate()
void set_motor_immediate (int motor, int speed)
Sets the motor speed ignoring the slew controller.
Parameters
motor the motor port to use
speed the speed to use, between -127 and 127
Author
Chris Jerrett
Date
9/14/17
Definition at line 89 of file slew.c.
References debug(), init_slew(), initialized, motors_curr_speeds, motors_set_speeds, and speeds_mutex.
Referenced by close_claw(), open_claw(), set_claw_motor(), set_intake_motor(), set_main_lifter_motors(), and set_secondary_lifter_motors().
                                               {
  if(!initialized) {
    debug("Slew Not Initialized! Initializing");
    init_slew();
  }
  motorSet(motor, speed);
  mutexTake(speeds_mutex, 10);
  motors_curr_speeds[motor-1] = speed;
  motors_set_speeds[motor-1] = speed;
  mutexGive(speeds_mutex);
}
set_motor_slew()
void set_motor_slew (int motor, int speed)
Sets motor speed wrapped inside the slew rate controller.
Parameters
motor the motor port to use
speed the speed to use, between -127 and 127
Author
Chris Jerrett
Date
9/14/17
Definition at line 72 of file slew.c.
References debug(), init_slew(), initialized, motors_set_speeds, and speeds_mutex.
Referenced by set_side_speed().
                                         {
  if(!initialized) {
    debug("Slew Not Initialized! Initializing");
    init_slew();
  }
  mutexTake(speeds_mutex, 10);
  motors_set_speeds[motor-1] = speed;
  mutexGive(speeds_mutex);
}
updateMotors()
void updateMotors ()
Closes the distance between the desired motor value and the current motor value by half for each motor.
Author
Chris Jerrett
Date
9/14/17
Definition at line 18 of file slew.c.
References motors_curr_speeds, motors_set_speeds, and speeds_mutex.
Referenced by init_slew().
                   {
  //Take back half approach
  //Not linear but equal to setSpeed(1-(1/2)^x)
  for(unsigned int i = 0; i < 9; i++) {
    if(motors_set_speeds[i] == motors_curr_speeds[i]) continue;
    mutexTake(speeds_mutex, 10);
    int set_speed = (motors_set_speeds[i]);
    int curr_speed = motors_curr_speeds[i];
    mutexGive(speeds_mutex);
    int diff = set_speed - curr_speed;
    int offset = diff;
    int n = curr_speed + offset;
    motors_curr_speeds[i] = n;
    motorSet(i+1, n);
  }
}