src/slew.c File Reference
Functions
void deinitslew ()
Deinitializes the slew rate controller and frees memory.
void init_slew ()
Initializes the slew rate controller.
void set_motor_immediate (int motor, int speed)
Sets the motor speed ignoring the slew controller.
void set_motor_slew (int motor, int speed)
Sets motor speed wrapped inside the slew rate controller.
void updateMotors ()
Closes the distance between the desired motor value and the current motor value by half for each motor.
Variables
static bool initialized = false
static int motors_curr_speeds [10]
static int motors_set_speeds [10]
static TaskHandle slew = NULL
static Mutex speeds_mutex
Function Documentation
deinitslew()
void deinitslew ()
Deinitializes the slew rate controller and frees memory.
Author
Chris Jerrett
Date
9/14/17
Definition at line 59 of file slew.c.
References initialized, motors_curr_speeds, motors_set_speeds, slew, and taskDelete().
Referenced by autonomous().
                  {
  taskDelete(slew);
  memset(motors_set_speeds, 0, sizeof(int) * 10);
  memset(motors_curr_speeds, 0, sizeof(int) * 10);
  initialized = false;
}
init_slew()
void init_slew ()
Initializes the slew rate controller.
Author
Chris Jerrett, Christian DeSimone
Date
9/14/17
Definition at line 42 of file slew.c.
References initialized, motors_curr_speeds, motors_set_speeds, motorStopAll(), mutexCreate(), slew, speeds_mutex, taskRunLoop(), updateMotors(), and warning().
Referenced by operatorControl(), set_motor_immediate(), set_motor_slew(), and start_auton().
                 {
  if (initialized) {
    warning("Trying to init already init slew");
  }
  memset(motors_set_speeds, 0, sizeof(int) * 10);
  memset(motors_curr_speeds, 0, sizeof(int) * 10);
  motorStopAll();
  speeds_mutex = mutexCreate();
  slew = taskRunLoop(updateMotors, 100);
  initialized = true;
}
set_motor_immediate()
void set_motor_immediate (int motor, int speed)
Sets the motor speed ignoring the slew controller.
Parameters
motor the motor port to use
speed the speed to use, between -127 and 127
Author
Chris Jerrett
Date
9/14/17
Definition at line 90 of file slew.c.
References debug(), init_slew(), initialized, motors_curr_speeds, motors_set_speeds, motorSet(), mutexGive(), mutexTake(), and speeds_mutex.
Referenced by claw_grab_cone(), claw_release_cone(), set_claw_motor(), set_intake_motor(), and set_secondary_lifter_motors().
                                               {
  if (!initialized) {
    debug("Slew Not Initialized! Initializing");
    init_slew();
  }
  motorSet(motor, speed);
  mutexTake(speeds_mutex, 10);
  motors_curr_speeds[motor - 1] = speed;
  motors_set_speeds[motor - 1] = speed;
  mutexGive(speeds_mutex);
}
set_motor_slew()
void set_motor_slew (int motor, int speed)
Sets motor speed wrapped inside the slew rate controller.
Parameters
motor the motor port to use
speed the speed to use, between -127 and 127
Author
Chris Jerrett
Date
9/14/17
Definition at line 73 of file slew.c.
References debug(), init_slew(), initialized, motors_set_speeds, mutexGive(), mutexTake(), and speeds_mutex.
Referenced by set_main_lifter_motors(), and set_side_speed().
                                          {
  if (!initialized) {
    debug("Slew Not Initialized! Initializing");
    init_slew();
  }
  mutexTake(speeds_mutex, 10);
  motors_set_speeds[motor - 1] = speed;
  mutexGive(speeds_mutex);
}
updateMotors()
void updateMotors ()
Closes the distance between the desired motor value and the current motor value by half for each motor.
Author
Chris Jerrett
Date
9/14/17
Definition at line 19 of file slew.c.
References motors_curr_speeds, motors_set_speeds, motorSet(), mutexGive(), mutexTake(), and speeds_mutex.
Referenced by init_slew().
                    {
  // Take back half approach
  // Not linear but equal to setSpeed(1-(1/2)^x)
  for (unsigned int i = 0; i < 9; i++) {
    if (motors_set_speeds[i] == motors_curr_speeds[i])
      continue;
    mutexTake(speeds_mutex, 10);
    int set_speed = (motors_set_speeds[i]);
    int curr_speed = motors_curr_speeds[i];
    mutexGive(speeds_mutex);
    int diff = set_speed - curr_speed;
    int offset = diff;
    int n = curr_speed + offset;
    motors_curr_speeds[i] = n;
    motorSet(i + 1, n);
  }
}
Variable Documentation
initialized
bool initialized = false [static]
Definition at line 11 of file slew.c.
Referenced by deinitslew(), init_slew(), set_motor_immediate(), and set_motor_slew().
motors_curr_speeds
int motors_curr_speeds[10] [static]
Definition at line 7 of file slew.c.
Referenced by deinitslew(), init_slew(), set_motor_immediate(), and updateMotors().
motors_set_speeds
int motors_set_speeds[10] [static]
Definition at line 6 of file slew.c.
Referenced by deinitslew(), init_slew(), set_motor_immediate(), set_motor_slew(), and updateMotors().
slew
 TaskHandle slew = NULL [static]
Definition at line 9 of file slew.c.
Referenced by deinitslew(), and init_slew().
speeds_mutex
 Mutex speeds_mutex [static]
Definition at line 4 of file slew.c.
Referenced by init_slew(), set_motor_immediate(), set_motor_slew(), and updateMotors().