include/toggle.h File Reference
#include <API.h>
Enumerations
enum button_t {
JOY1_5D = 0,
JOY1_5U = 1,
JOY1_6D = 2,
JOY1_6U = 3,
JOY1_7U = 4,
JOY1_7L = 5,
JOY1_7R = 6,
JOY1_7D = 7,
JOY1_8U = 8,
JOY1_8L = 9,
JOY1_8R = 10,
JOY1_8D = 11,
JOY2_5D = 12,
JOY2_5U = 13,
JOY2_6D = 14,
JOY2_6U = 15,
JOY2_7U = 16,
JOY2_7L = 17,
JOY2_7R = 18,
JOY2_7D = 19,
JOY2_8U = 20,
JOY2_8L = 21,
JOY2_8R = 22,
JOY2_8D = 23,
LCD_LEFT = 24,
LCD_CENT = 25,
LCD_RIGHT = 26
 }
Functions
bool buttonGetState (button_t)
Returns the current status of a button (pressed or not pressed)
void buttonInit ()
Initializes the buttons.
bool buttonIsNewPress (button_t)
Detects if button is a new press from most recent check by comparing previous value to current value.
Enumeration Type Documentation
button_t
enum button_t
Renames the input channels
Enumerator
JOY1_5D
JOY1_5U
JOY1_6D
JOY1_6U
JOY1_7U
JOY1_7L
JOY1_7R
JOY1_7D
JOY1_8U
JOY1_8L
JOY1_8R
JOY1_8D
JOY2_5D
JOY2_5U
JOY2_6D
JOY2_6U
JOY2_7U
JOY2_7L
JOY2_7R
JOY2_7D
JOY2_8U
JOY2_8L
JOY2_8R
JOY2_8D
LCD_LEFT
LCD_CENT
LCD_RIGHT
Definition at line 20 of file toggle.h.
             {
    JOY1_5D = 0,
    JOY1_5U = 1,
    JOY1_6D = 2,
    JOY1_6U = 3,
    JOY1_7U = 4,
    JOY1_7L = 5,
    JOY1_7R = 6,
    JOY1_7D = 7,
    JOY1_8U = 8,
    JOY1_8L = 9,
    JOY1_8R = 10,
    JOY1_8D = 11,
    JOY2_5D = 12,
    JOY2_5U = 13,
    JOY2_6D = 14,
    JOY2_6U = 15,
    JOY2_7U = 16,
    JOY2_7L = 17,
    JOY2_7R = 18,
    JOY2_7D = 19,
    JOY2_8U = 20,
    JOY2_8L = 21,
    JOY2_8R = 22,
    JOY2_8D = 23,
    LCD_LEFT = 24,
    LCD_CENT = 25,
    LCD_RIGHT = 26
} button_t;
Function Documentation
buttonGetState()
bool buttonGetState (button_t)
Returns the current status of a button (pressed or not pressed)
Parameters
button The button to detect from the Buttons enumeration.
Returns
true (pressed) or false (not pressed)
Definition at line 25 of file toggle.c.
References JOY_DOWN, JOY_LEFT, JOY_RIGHT, JOY_UP, joystickGetDigital(), LCD_BTN_CENTER, LCD_BTN_LEFT, LCD_BTN_RIGHT, LCD_CENT, LCD_LEFT, LCD_RIGHT, lcdReadButtons(), and uart1.
Referenced by buttonIsNewPress().
                                     {
    bool currentButton = false;
    // Determine how to get the current button value (from what function) and where it
    // is, then get it.
    if (button < LCD_LEFT) {
        // button is a joystick button
        unsigned char joystick;
        unsigned char buttonGroup;
        unsigned char buttonLocation;
        button_t newButton;
        if (button <= 11) {
            // button is on joystick 1
            joystick = 1;
            newButton = button;
        }
        else {
            // button is on joystick 2
            joystick = 2;
            // shift button down to joystick 1 buttons in order to
            // detect which button on joystick is queried
            newButton = (button_t)(button - 12);
        }
        switch (newButton) {
        case 0:
            buttonGroup = 5;
            buttonLocation = JOY_DOWN;
            break;
        case 1:
            buttonGroup = 5;
            buttonLocation = JOY_UP;
            break;
        case 2:
            buttonGroup = 6;
            buttonLocation = JOY_DOWN;
            break;
        case 3:
            buttonGroup = 6;
            buttonLocation = JOY_UP;
            break;
        case 4:
            buttonGroup = 7;
            buttonLocation = JOY_UP;
            break;
        case 5:
            buttonGroup = 7;
            buttonLocation = JOY_LEFT;
            break;
        case 6:
            buttonGroup = 7;
            buttonLocation = JOY_RIGHT;
            break;
        case 7:
            buttonGroup = 7;
            buttonLocation = JOY_DOWN;
            break;
        case 8:
            buttonGroup = 8;
            buttonLocation = JOY_UP;
            break;
        case 9:
            buttonGroup = 8;
            buttonLocation = JOY_LEFT;
            break;
        case 10:
            buttonGroup = 8;
            buttonLocation = JOY_RIGHT;
            break;
        case 11:
            buttonGroup = 8;
            buttonLocation = JOY_DOWN;
            break;
        default:
            break;
        }
        currentButton = joystickGetDigital(joystick, buttonGroup, buttonLocation);
    }
    else {
        // button is on LCD
        if (button == LCD_LEFT)
            currentButton = (lcdReadButtons(uart1) ==
      LCD_BTN_LEFT);
        if (button == LCD_CENT)
            currentButton = (lcdReadButtons(uart1) ==
      LCD_BTN_CENTER);
        if (button == LCD_RIGHT)
            currentButton = (lcdReadButtons(uart1) ==
      LCD_BTN_RIGHT);
    }
    return currentButton;
}
buttonInit()
void buttonInit ()
Initializes the buttons.
Initializes the buttons.
Definition at line 20 of file toggle.c.
References buttonPressed.
                  {
    for (int i = 0; i < 27; i++)
        buttonPressed[i] = false;
}
buttonIsNewPress()
bool buttonIsNewPress (button_t button)
Detects if button is a new press from most recent check by comparing previous value to current value.
Parameters
button The button to detect from the Buttons enumeration (see include/buttons.h).
Returns
true or false depending on if there was a change in button state.
Parameters
button The button to detect from the Buttons enumeration (see include/buttons.h).
Returns
true or false depending on if there was a change in button state.
Example code:
...
if(buttonIsNewPress(JOY1_8D))
    digitalWrite(1, !digitalRead(1));
...
Definition at line 135 of file toggle.c.
References buttonGetState(), and buttonPressed.
                                       {
    bool currentButton = buttonGetState(button);
    if (!currentButton) // buttons is not currently pressed
        buttonPressed[button] = false;
    if (currentButton && !buttonPressed[button]) {
        // button is currently pressed and was not detected as being pressed during last check
        buttonPressed[button] = true;
        return true;
    }
    else return false; // button is not pressed or was already detected
}