src/vlib.c File Reference
#include `vlib.h`
Functions
void ftoa (float a, char *buffer, int precision)
converts a float to string.
int itoa_bad (int a, char *buffer, int digits)
converts a int to string.
void reverse (char *str, int len)
reverses a string 'str' of length 'len'
Function Documentation
ftoa()
void ftoa (float a, char * buffer, int precision)
converts a float to string.
Parameters
a the float
buffer the string the float will be written to.
precision digits after the decimal to write
Author
Christian DeSimone
Date
9/26/2017
Definition at line 54 of file vlib.c.
References itoa_bad().
                                                {
  // Extract integer part
  int ipart = (int)a;
  // Extract floating part
  float fpart = a - (float)ipart;
  // convert integer part to string
  int i = itoa_bad(ipart, buffer, 0);
  // check for display option after point
  if(precision != 0) {
    buffer[i] = '.'; // add dot
    // Get the value of fraction part up to given num.
    // of points after dot. The third parameter is needed
    // to handle cases like 233.007
    fpart = fpart * pow(10, precision);
    itoa_bad((int)fpart, buffer + i + 1, precision);
  }
}
itoa_bad()
int itoa_bad (int a, char * buffer, int digits)
converts a int to string.
Parameters
a the integer
buffer the string the int will be written to.
digits the number of digits to be written
Returns
the digits
Author
Chris Jerrett, Christian DeSimone
Date
9/9/2017
Definition at line 29 of file vlib.c.
References reverse().
Referenced by calculate_current_display(), and ftoa().
                                              {
  int i = 0;
   while (a) {
       buffer[i++] = (a%10) + '0';
       a = a/10;
   }
   // If number of digits required is more, then
   // add 0s at the beginning
   while (i < digits)
       buffer[i++] = '0';
   reverse(buffer, i);
   buffer[i] = '\0';
   return i;
}
reverse()
void reverse (char * str, int len)
reverses a string 'str' of length 'len'
Author
Chris Jerrett
Date
9/9/2017
Parameters
str the string to reverse
len the length
Definition at line 10 of file vlib.c.
Referenced by itoa_bad().
                                 {
    int i=0, j=len-1, temp;
    while (i<j) {
        temp = str[i];
        str[i] = str[j];
        str[j] = temp;
        i++; j--;
    }
}