include/vlib.h File Reference
Contains misc helpful functions.
#include <math.h>
#include <API.h>
#include <string.h>
Functions
void * calloc_real (size_t elements, size_t size)
void ftoa (float a, char *buffer, int precision)
converts a float to string.
int itoa (int a, char *buffer, int digits)
converts a int to string.
void reverse (char *str, int len)
reverses a string 'str' of length 'len'
Detailed Description
Contains misc helpful functions.
Author
Chris Jerrett
Date
9/9/2017
Function Documentation
calloc_real()
void* calloc_real (size_t elements, size_t size)
Definition at line 53 of file vlib.c.
Referenced by init_slew().
                                               {
  void *mem = malloc(elements * size);
  //This is not a error. Bad ATOM!
  memset(mem, 0, elements * size);
  return mem;
}
ftoa()
void ftoa (float a, char * buffer, int precision)
converts a float to string.
Parameters
a the float
buffer the string the float will be written to.
precision digits after the decimal to write
Definition at line 30 of file vlib.c.
References itoa().
Referenced by calculate_current_display().
                                                {
  // Extract integer part
  int ipart = (int)a;
  // Extract floating part
  float fpart = a - (float)ipart;
  // convert integer part to string
  int i = itoa(ipart, buffer, 0);
  // check for display option after point
  if(precision != 0) {
    buffer[i] = '.'; // add dot
    // Get the value of fraction part up to given num.
    // of points after dot. The third parameter is needed
    // to handle cases like 233.007
    fpart = fpart * pow(10, precision);
    itoa((int)fpart, buffer + i + 1, precision);
  }
}
itoa()
int itoa (int a, char * buffer, int digits)
converts a int to string.
Parameters
a the integer
buffer the string the int will be written to.
digits the number of digits to be written
Returns
the digits
Author
Chris Jerrett
Date
9/9/2017
Definition at line 13 of file vlib.c.
References reverse().
Referenced by calculate_current_display(), and ftoa().
                                          {
  int i = 0;
   while (a) {
       buffer[i++] = (a%10) + '0';
       a = a/10;
   }
   // If number of digits required is more, then
   // add 0s at the beginning
   while (i < digits)
       buffer[i++] = '0';
   reverse(buffer, i);
   buffer[i] = '\0';
   return i;
}
reverse()
void reverse (char * str, int len)
reverses a string 'str' of length 'len'
Author
Chris Jerrett
Date
9/9/2017
Parameters
str the string to reverse
len the length
Definition at line 3 of file vlib.c.
Referenced by itoa().
                                 {
    int i=0, j=len-1, temp;
    while (i<j) {
        temp = str[i];
        str[i] = str[j];
        str[j] = temp;
        i++; j--;
    }
}