include/vmath.h File Reference
Vex Specific Math Functions, includes: Cartesian to polar cordinates.
#include <math.h>
Data Structures
struct cord
A struct that contains cartesian coordinates.
struct polar_cord
A struct that contains polar coordinates.
Macros
#define M_PI 3.14159265358979323846
Functions
struct polar_cord cartesian_cord_to_polar (struct cord cords)
Function to convert x and y 2 dimensional cartesian cordinated to polar coordinates.
struct polar_cord cartesian_to_polar (float x, float y)
Function to convert x and y 2 dimensional cartesian coordinated to polar coordinates.
int max (int a, int b)
the min of two values
int min (int a, int b)
the min of two values
double sind (double angle)
sine of a angle in degrees
Detailed Description
Vex Specific Math Functions, includes: Cartesian to polar cordinates.
Author
Christian Desimone
Chris Jerrett
Date
9/9/2017
Definition in file vmath.h.
Macro Definition Documentation
M_PI
#define M_PI 3.14159265358979323846
Definition at line 13 of file vmath.h.
Referenced by sind().
Function Documentation
cartesian_cord_to_polar()
struct polar_cord cartesian_cord_to_polar (struct cord cords)
Function to convert x and y 2 dimensional cartesian cordinated to polar coordinates.
Author
Christian Desimone
Date
9/8/2017
Parameters
cords the cartesian cords
Returns
a struct containing the angle and magnitude.
See also
polar_cord
cord
Definition at line 55 of file vmath.c.
References cartesian_to_polar().
                                                             {
  return cartesian_to_polar(cords.x, cords.y);
}
cartesian_to_polar()
struct polar_cord cartesian_to_polar (float x, float y)
Function to convert x and y 2 dimensional cartesian coordinated to polar coordinates.
Author
Christian Desimone
Date
9/8/2017
Parameters
x float value of the x cartesian coordinate.
y float value of the y cartesian coordinate.
Returns
a struct containing the angle and magnitude.
See also
polar_cord
Definition at line 14 of file vmath.c.
References polar_cord::angle, and polar_cord::magnitue.
Referenced by cartesian_cord_to_polar().
                                                       {
  float degree = 0;
  double magnitude = sqrt((fabs(x) * fabs(x)) + (fabs(y) * fabs(y)));
  if(x < 0){
    degree += 180.0;
  }
  else if(x > 0 && y < 0){
    degree += 360.0;
  }
  if(x != 0 && y != 0){
    degree += atan((float)y / (float)x);
  }
  else if(x == 0 && y > 0){
    degree = 90.0;
  }
  else if(y == 0 && x < 0){
    degree = 180.0;
  }
  else if(x == 0 && y < 0){
    degree = 270.0;
  }
  struct polar_cord p;
  p.angle = degree;
  p.magnitue = magnitude;
  return p;
}
max()
int max (int a, int b)
the min of two values
Parameters
a the first
b the second
Returns
the smaller of a and b
Definition at line 84 of file vmath.c.
Referenced by calculate_current_display(), init_menu_float(), and init_menu_int().
                      {
  if(a > b) return a;
  return b;
}
min()
int min (int a, int b)
the min of two values
Parameters
a the first
b the second
Returns
the smaller of a and b
Definition at line 73 of file vmath.c.
Referenced by calculate_current_display(), init_menu_float(), and init_menu_int().
                      {
  if(a < b) return a;
  return b;
}
sind()
double sind (double angle)
sine of a angle in degrees
Definition at line 62 of file vmath.c.
References M_PI.
                          {
    double angleradians = angle * M_PI / 180.0f;
    return sin(angleradians);
}