src/vmath.c File Reference
#include `vmath.h`
Functions
struct polar_cord cartesian_cord_to_polar (struct cord cords)
Function to convert x and y 2 dimensional cartesian cordinated to polar coordinates.
struct polar_cord cartesian_to_polar (float x, float y)
Function to convert x and y 2 dimensional cartesian coordinated to polar coordinates.
int max (int a, int b)
int min (int a, int b)
double sind (double angle)
Function Documentation
cartesian_cord_to_polar()
struct polar_cord cartesian_cord_to_polar (struct cord cords)
Function to convert x and y 2 dimensional cartesian cordinated to polar coordinates.
Author
Christian Desimone
Date
9/8/2017
Parameters
cords the cartesian cords
Returns
a struct containing the angle and magnitude.
See also
polar_cord
cord
Definition at line 33 of file vmath.c.
References cartesian_to_polar().
                                                             {
  return cartesian_to_polar(cords.x, cords.y);
}
cartesian_to_polar()
struct polar_cord cartesian_to_polar (float x, float y)
Function to convert x and y 2 dimensional cartesian coordinated to polar coordinates.
Author
Christian Desimone
Date
9/8/2017
Parameters
x float value of the x cartesian coordinate.
y float value of the y cartesian coordinate.
Returns
a struct containing the angle and magnitude.
See also
polar_cord
Definition at line 3 of file vmath.c.
References polar_cord::angle, and polar_cord::magnitue.
Referenced by cartesian_cord_to_polar().
                                                       {
  float degree = 0;
  double magnitude = sqrt((fabs(x) * fabs(x)) + (fabs(y) * fabs(y)));
  if(x < 0){
    degree += 180.0;
  }
  else if(x > 0 && y < 0){
    degree += 360.0;
  }
  if(x != 0 && y != 0){
    degree += atan((float)y / (float)x);
  }
  else if(x == 0 && y > 0){
    degree = 90.0;
  }
  else if(y == 0 && x < 0){
    degree = 180.0;
  }
  else if(x == 0 && y < 0){
    degree = 270.0;
  }
  struct polar_cord p;
  p.angle = degree;
  p.magnitue = magnitude;
  return p;
}
max()
int max (int a, int b)
Definition at line 48 of file vmath.c.
Referenced by calculate_current_display(), init_menu_float(), and init_menu_int().
                      {
  if(a > b) return a;
  return b;
}
min()
int min (int a, int b)
Definition at line 42 of file vmath.c.
Referenced by calculate_current_display(), init_menu_float(), and init_menu_int().
                      {
  if(a < b) return a;
  return b;
}
sind()
double sind (double angle)
Definition at line 37 of file vmath.c.
References M_PI.
                          {
    double angleradians = angle * M_PI / 180.0f;
    return sin(angleradians);
}