.TH "src Directory Reference" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauto\&.c\fP"
.br
.RI "File for autonomous code\&. "
.ti -1c
.RI "file \fBbattery\&.c\fP"
.br
.ti -1c
.RI "file \fBclaw\&.c\fP"
.br
.ti -1c
.RI "file \fBcontroller\&.c\fP"
.br
.ti -1c
.RI "file \fBdrive\&.c\fP"
.br
.ti -1c
.RI "file \fBencoders\&.c\fP"
.br
.ti -1c
.RI "file \fBinit\&.c\fP"
.br
.RI "File for initialization code\&. "
.ti -1c
.RI "file \fBlcd\&.c\fP"
.br
.ti -1c
.RI "file \fBlifter\&.c\fP"
.br
.ti -1c
.RI "file \fBlocalization\&.c\fP"
.br
.ti -1c
.RI "file \fBlog\&.c\fP"
.br
.ti -1c
.RI "file \fBmatrix\&.c\fP"
.br
.ti -1c
.RI "file \fBmenu\&.c\fP"
.br
.ti -1c
.RI "file \fBmobile_goal_intake\&.c\fP"
.br
.ti -1c
.RI "file \fBopcontrol\&.c\fP"
.br
.RI "File for operator control code\&. "
.ti -1c
.RI "file \fBpartner\&.c\fP"
.br
.ti -1c
.RI "file \fBslew\&.c\fP"
.br
.ti -1c
.RI "file \fBtoggle\&.c\fP"
.br
.ti -1c
.RI "file \fBvlib\&.c\fP"
.br
.ti -1c
.RI "file \fBvmath\&.c\fP"
.br
.in -1c
