.TH "include Directory Reference" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAPI\&.h\fP"
.br
.RI "Provides the high-level user functionality intended for use by typical VEX Cortex programmers\&. "
.ti -1c
.RI "file \fBauto\&.h\fP"
.br
.RI "Autonomous declarations and macros\&. "
.ti -1c
.RI "file \fBbattery\&.h\fP"
.br
.RI "Battery management related functions\&. "
.ti -1c
.RI "file \fBclaw\&.h\fP"
.br
.RI "Code for controlling the claw that grabs the cones\&. "
.ti -1c
.RI "file \fBcontroller\&.h\fP"
.br
.RI "controller definitions, macros and functions to assist with usig the vex controllers\&. "
.ti -1c
.RI "file \fBdrive\&.h\fP"
.br
.RI "Drive base definitions and enumerations\&. "
.ti -1c
.RI "file \fBencoders\&.h\fP"
.br
.RI "wrapper around encoder functions "
.ti -1c
.RI "file \fBlcd\&.h\fP"
.br
.RI "LCD wrapper functions and macros\&. "
.ti -1c
.RI "file \fBlifter\&.h\fP"
.br
.RI "Declarations and macros for controlling and manipulating the lifter\&. "
.ti -1c
.RI "file \fBlocalization\&.h\fP"
.br
.RI "Declarations and macros for determining the location of the robot\&. [WIP]\&. "
.ti -1c
.RI "file \fBlog\&.h\fP"
.br
.RI "Contains logging functions\&. "
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.RI "Header file for global functions\&. "
.ti -1c
.RI "file \fBmatrix\&.h\fP"
.br
.RI "Various Matrix operations\&.
.PP
None of the matrix operations below change the input matrices if an input is required\&. They all return a new matrix with the new changes\&. Because memory issues are so prevelant, be sure to use the  function to reclaim some of that memory\&. "
.ti -1c
.RI "file \fBmenu\&.h\fP"
.br
.RI "Contains menu functionality and abstraction\&. "
.ti -1c
.RI "file \fBmobile_goal_intake\&.h\fP"
.br
.ti -1c
.RI "file \fBmotor_ports\&.h\fP"
.br
.RI "The motor port definitions
.PP
Macros for the different motors ports\&. "
.ti -1c
.RI "file \fBpartner\&.h\fP"
.br
.ti -1c
.RI "file \fBpotentiometer\&.h\fP"
.br
.ti -1c
.RI "file \fBsensor_ports\&.h\fP"
.br
.ti -1c
.RI "file \fBslew\&.h\fP"
.br
.RI "Contains the slew rate controller wrapper for the motors\&. "
.ti -1c
.RI "file \fBtoggle\&.h\fP"
.br
.ti -1c
.RI "file \fBvlib\&.h\fP"
.br
.RI "Contains misc helpful functions\&. "
.ti -1c
.RI "file \fBvmath\&.h\fP"
.br
.RI "Vex Specific Math Functions, includes: Cartesian to polar cordinates\&. "
.in -1c
