.TH "include Directory Reference" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAPI\&.h\fP"
.br
.RI "Provides the high-level user functionality intended for use by typical VEX Cortex programmers\&. "
.ti -1c
.RI "file \fBcontroller\&.h\fP"
.br
.RI "controller definitions, macros "
.ti -1c
.RI "file \fBdrive\&.h\fP"
.br
.RI "Drive base definitions and eumerations\&. "
.ti -1c
.RI "file \fBencoders\&.h\fP"
.br
.ti -1c
.RI "file \fBlcd\&.h\fP"
.br
.RI "LCD wrapper functions and macros\&. "
.ti -1c
.RI "file \fBmain\&.h\fP"
.br
.RI "Header file for global functions\&. "
.ti -1c
.RI "file \fBmenu\&.h\fP"
.br
.ti -1c
.RI "file \fBports\&.h\fP"
.br
.ti -1c
.RI "file \fBvmath\&.h\fP"
.br
.RI "Vex Specific Math Functions, includes: Cartesian to polar cordinates\&. "
.in -1c
