.TH "src Directory Reference" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauto\&.c\fP"
.br
.RI "File for autonomous code\&. "
.ti -1c
.RI "file \fBdrive\&.c\fP"
.br
.ti -1c
.RI "file \fBinit\&.c\fP"
.br
.RI "File for initialization code\&. "
.ti -1c
.RI "file \fBopcontrol\&.c\fP"
.br
.RI "File for operator control code\&. "
.in -1c
