.TH "accelerometer_odometry" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
accelerometer_odometry
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file localization\&.c\&.
.SH "Field Documentation"
.PP 
.SS "double accelerometer_odometry::x"

.PP
Definition at line 18 of file localization\&.c\&.
.SS "double accelerometer_odometry::y"

.PP
Definition at line 19 of file localization\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
