.TH "include/API.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/API.h \- Provides the high-level user functionality intended for use by typical VEX Cortex programmers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBACCEL_X\fP   5"
.br
.ti -1c
.RI "#define \fBACCEL_Y\fP   6"
.br
.ti -1c
.RI "#define \fBBOARD_NR_ADC_PINS\fP   8"
.br
.ti -1c
.RI "#define \fBBOARD_NR_GPIO_PINS\fP   27"
.br
.ti -1c
.RI "#define \fBEOF\fP   ((int)\-1)"
.br
.ti -1c
.RI "#define \fBFILE\fP   \fBPROS_FILE\fP"
.br
.ti -1c
.RI "#define \fBHIGH\fP   1"
.br
.ti -1c
.RI "#define \fBIME_ADDR_MAX\fP   0x1F"
.br
.ti -1c
.RI "#define \fBINPUT\fP   0x0A"
.br
.ti -1c
.RI "#define \fBINPUT_ANALOG\fP   0x00"
.br
.ti -1c
.RI "#define \fBINPUT_FLOATING\fP   0x04"
.br
.ti -1c
.RI "#define \fBINTERRUPT_EDGE_BOTH\fP   3"
.br
.ti -1c
.RI "#define \fBINTERRUPT_EDGE_FALLING\fP   2"
.br
.ti -1c
.RI "#define \fBINTERRUPT_EDGE_RISING\fP   1"
.br
.ti -1c
.RI "#define \fBJOY_DOWN\fP   1"
.br
.ti -1c
.RI "#define \fBJOY_LEFT\fP   2"
.br
.ti -1c
.RI "#define \fBJOY_RIGHT\fP   8"
.br
.ti -1c
.RI "#define \fBJOY_UP\fP   4"
.br
.ti -1c
.RI "#define \fBLCD_BTN_CENTER\fP   2"
.br
.ti -1c
.RI "#define \fBLCD_BTN_LEFT\fP   1"
.br
.ti -1c
.RI "#define \fBLCD_BTN_RIGHT\fP   4"
.br
.ti -1c
.RI "#define \fBLOW\fP   0"
.br
.ti -1c
.RI "#define \fBOUTPUT\fP   0x01"
.br
.ti -1c
.RI "#define \fBOUTPUT_OD\fP   0x05"
.br
.ti -1c
.RI "#define \fBSEEK_CUR\fP   1"
.br
.ti -1c
.RI "#define \fBSEEK_END\fP   2"
.br
.ti -1c
.RI "#define \fBSEEK_SET\fP   0"
.br
.ti -1c
.RI "#define \fBSERIAL_8N1\fP   0x0000"
.br
.ti -1c
.RI "#define \fBSERIAL_DATABITS_8\fP   0x0000"
.br
.ti -1c
.RI "#define \fBSERIAL_DATABITS_9\fP   0x1000"
.br
.ti -1c
.RI "#define \fBSERIAL_PARITY_EVEN\fP   0x0400"
.br
.ti -1c
.RI "#define \fBSERIAL_PARITY_NONE\fP   0x0000"
.br
.ti -1c
.RI "#define \fBSERIAL_PARITY_ODD\fP   0x0600"
.br
.ti -1c
.RI "#define \fBSERIAL_STOPBITS_1\fP   0x0000"
.br
.ti -1c
.RI "#define \fBSERIAL_STOPBITS_2\fP   0x2000"
.br
.ti -1c
.RI "#define \fBstdin\fP   ((\fBPROS_FILE\fP *)3)"
.br
.ti -1c
.RI "#define \fBstdout\fP   ((\fBPROS_FILE\fP *)3)"
.br
.ti -1c
.RI "#define \fBTASK_DEAD\fP   0"
.br
.ti -1c
.RI "#define \fBTASK_DEFAULT_STACK_SIZE\fP   512"
.br
.ti -1c
.RI "#define \fBTASK_MAX\fP   16"
.br
.ti -1c
.RI "#define \fBTASK_MAX_PRIORITIES\fP   6"
.br
.ti -1c
.RI "#define \fBTASK_MINIMAL_STACK_SIZE\fP   64"
.br
.ti -1c
.RI "#define \fBTASK_PRIORITY_DEFAULT\fP   2"
.br
.ti -1c
.RI "#define \fBTASK_PRIORITY_HIGHEST\fP   (\fBTASK_MAX_PRIORITIES\fP \- 1)"
.br
.ti -1c
.RI "#define \fBTASK_PRIORITY_LOWEST\fP   0"
.br
.ti -1c
.RI "#define \fBTASK_RUNNABLE\fP   2"
.br
.ti -1c
.RI "#define \fBTASK_RUNNING\fP   1"
.br
.ti -1c
.RI "#define \fBTASK_SLEEPING\fP   3"
.br
.ti -1c
.RI "#define \fBTASK_SUSPENDED\fP   4"
.br
.ti -1c
.RI "#define \fBuart1\fP   ((\fBPROS_FILE\fP *)1)"
.br
.ti -1c
.RI "#define \fBuart2\fP   ((\fBPROS_FILE\fP *)2)"
.br
.ti -1c
.RI "#define \fBULTRA_BAD_RESPONSE\fP   \-1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void * \fBEncoder\fP"
.br
.ti -1c
.RI "typedef void * \fBGyro\fP"
.br
.ti -1c
.RI "typedef void(* \fBInterruptHandler\fP) (unsigned char pin)"
.br
.ti -1c
.RI "typedef void * \fBMutex\fP"
.br
.ti -1c
.RI "typedef int \fBPROS_FILE\fP"
.br
.ti -1c
.RI "typedef void * \fBSemaphore\fP"
.br
.ti -1c
.RI "typedef void(* \fBTaskCode\fP) (void *)"
.br
.ti -1c
.RI "typedef void * \fBTaskHandle\fP"
.br
.ti -1c
.RI "typedef void * \fBUltrasonic\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB__attribute__\fP ((format(\fBprintf\fP, 3, 4))) lcdPrint(\fBPROS_FILE\fP *lcdPort"
.br
.ti -1c
.RI "int \fBanalogCalibrate\fP (unsigned char channel)"
.br
.ti -1c
.RI "int \fBanalogRead\fP (unsigned char channel)"
.br
.ti -1c
.RI "int \fBanalogReadCalibrated\fP (unsigned char channel)"
.br
.ti -1c
.RI "int \fBanalogReadCalibratedHR\fP (unsigned char channel)"
.br
.ti -1c
.RI "void \fBdelay\fP (const unsigned long time)"
.br
.ti -1c
.RI "void \fBdelayMicroseconds\fP (const unsigned long us)"
.br
.ti -1c
.RI "bool \fBdigitalRead\fP (unsigned char pin)"
.br
.ti -1c
.RI "void \fBdigitalWrite\fP (unsigned char pin, bool value)"
.br
.ti -1c
.RI "int \fBencoderGet\fP (\fBEncoder\fP enc)"
.br
.ti -1c
.RI "\fBEncoder\fP \fBencoderInit\fP (unsigned char portTop, unsigned char portBottom, bool \fBreverse\fP)"
.br
.ti -1c
.RI "void \fBencoderReset\fP (\fBEncoder\fP enc)"
.br
.ti -1c
.RI "void \fBencoderShutdown\fP (\fBEncoder\fP enc)"
.br
.ti -1c
.RI "void \fBfclose\fP (\fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "int \fBfcount\fP (\fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "int \fBfdelete\fP (const char *file)"
.br
.ti -1c
.RI "int \fBfeof\fP (\fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "int \fBfflush\fP (\fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "int \fBfgetc\fP (\fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "char * \fBfgets\fP (char *str, int num, \fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "\fBPROS_FILE\fP * \fBfopen\fP (const char *file, const char *\fBmode\fP)"
.br
.ti -1c
.RI "void \fBfprint\fP (const char *string, \fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "int \fBfprintf\fP (\fBPROS_FILE\fP *stream, const char *\fBformatString\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "int \fBfputc\fP (int value, \fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "int \fBfputs\fP (const char *string, \fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "size_t \fBfread\fP (void *ptr, size_t size, size_t count, \fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "int \fBfseek\fP (\fBPROS_FILE\fP *stream, long int offset, int origin)"
.br
.ti -1c
.RI "long int \fBftell\fP (\fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "size_t \fBfwrite\fP (const void *ptr, size_t size, size_t count, \fBPROS_FILE\fP *stream)"
.br
.ti -1c
.RI "int \fBgetchar\fP ()"
.br
.ti -1c
.RI "int \fBgyroGet\fP (\fBGyro\fP gyro)"
.br
.ti -1c
.RI "\fBGyro\fP \fBgyroInit\fP (unsigned char port, unsigned short multiplier)"
.br
.ti -1c
.RI "void \fBgyroReset\fP (\fBGyro\fP gyro)"
.br
.ti -1c
.RI "void \fBgyroShutdown\fP (\fBGyro\fP gyro)"
.br
.ti -1c
.RI "bool \fBi2cRead\fP (uint8_t addr, uint8_t *data, uint16_t count)"
.br
.ti -1c
.RI "bool \fBi2cReadRegister\fP (uint8_t addr, uint8_t reg, uint8_t *value, uint16_t count)"
.br
.ti -1c
.RI "bool \fBi2cWrite\fP (uint8_t addr, uint8_t *data, uint16_t count)"
.br
.ti -1c
.RI "bool \fBi2cWriteRegister\fP (uint8_t addr, uint8_t reg, uint16_t value)"
.br
.ti -1c
.RI "bool \fBimeGet\fP (unsigned char address, int *value)"
.br
.ti -1c
.RI "bool \fBimeGetVelocity\fP (unsigned char address, int *value)"
.br
.ti -1c
.RI "unsigned int \fBimeInitializeAll\fP ()"
.br
.ti -1c
.RI "bool \fBimeReset\fP (unsigned char address)"
.br
.ti -1c
.RI "void \fBimeShutdown\fP ()"
.br
.ti -1c
.RI "void \fBioClearInterrupt\fP (unsigned char pin)"
.br
.ti -1c
.RI "void \fBioSetInterrupt\fP (unsigned char pin, unsigned char edges, \fBInterruptHandler\fP handler)"
.br
.ti -1c
.RI "bool \fBisAutonomous\fP ()"
.br
.ti -1c
.RI "bool \fBisEnabled\fP ()"
.br
.ti -1c
.RI "bool \fBisJoystickConnected\fP (unsigned char \fBjoystick\fP)"
.br
.ti -1c
.RI "bool \fBisOnline\fP ()"
.br
.ti -1c
.RI "int \fBjoystickGetAnalog\fP (unsigned char \fBjoystick\fP, unsigned char axis)"
.br
.ti -1c
.RI "bool \fBjoystickGetDigital\fP (unsigned char \fBjoystick\fP, unsigned char buttonGroup, unsigned char button)"
.br
.ti -1c
.RI "void \fBlcdClear\fP (\fBPROS_FILE\fP *lcdPort)"
.br
.ti -1c
.RI "void \fBlcdInit\fP (\fBPROS_FILE\fP *lcdPort)"
.br
.ti -1c
.RI "void unsigned char const char unsigned int \fBlcdReadButtons\fP (\fBPROS_FILE\fP *lcdPort)"
.br
.ti -1c
.RI "void \fBlcdSetBacklight\fP (\fBPROS_FILE\fP *lcdPort, bool backlight)"
.br
.ti -1c
.RI "void \fBlcdSetText\fP (\fBPROS_FILE\fP *lcdPort, unsigned char \fBline\fP, const char *buffer)"
.br
.ti -1c
.RI "void \fBlcdShutdown\fP (\fBPROS_FILE\fP *lcdPort)"
.br
.ti -1c
.RI "unsigned long \fBmicros\fP ()"
.br
.ti -1c
.RI "unsigned long \fBmillis\fP ()"
.br
.ti -1c
.RI "int \fBmotorGet\fP (unsigned char channel)"
.br
.ti -1c
.RI "void \fBmotorSet\fP (unsigned char channel, int speed)"
.br
.ti -1c
.RI "void \fBmotorStop\fP (unsigned char channel)"
.br
.ti -1c
.RI "void \fBmotorStopAll\fP ()"
.br
.ti -1c
.RI "\fBMutex\fP \fBmutexCreate\fP ()"
.br
.ti -1c
.RI "void \fBmutexDelete\fP (\fBMutex\fP mutex)"
.br
.ti -1c
.RI "bool \fBmutexGive\fP (\fBMutex\fP mutex)"
.br
.ti -1c
.RI "bool \fBmutexTake\fP (\fBMutex\fP mutex, const unsigned long blockTime)"
.br
.ti -1c
.RI "void \fBpinMode\fP (unsigned char pin, unsigned char \fBmode\fP)"
.br
.ti -1c
.RI "unsigned int \fBpowerLevelBackup\fP ()"
.br
.ti -1c
.RI "unsigned int \fBpowerLevelMain\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP (const char *string)"
.br
.ti -1c
.RI "int \fBprintf\fP (const char *\fBformatString\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "int \fBputchar\fP (int value)"
.br
.ti -1c
.RI "int \fBputs\fP (const char *string)"
.br
.ti -1c
.RI "\fBSemaphore\fP \fBsemaphoreCreate\fP ()"
.br
.ti -1c
.RI "void \fBsemaphoreDelete\fP (\fBSemaphore\fP semaphore)"
.br
.ti -1c
.RI "bool \fBsemaphoreGive\fP (\fBSemaphore\fP semaphore)"
.br
.ti -1c
.RI "bool \fBsemaphoreTake\fP (\fBSemaphore\fP semaphore, const unsigned long blockTime)"
.br
.ti -1c
.RI "void \fBsetTeamName\fP (const char *name)"
.br
.ti -1c
.RI "int \fBsnprintf\fP (char *buffer, size_t limit, const char *\fBformatString\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBspeakerInit\fP ()"
.br
.ti -1c
.RI "void \fBspeakerPlayArray\fP (const char **songs)"
.br
.ti -1c
.RI "void \fBspeakerPlayRtttl\fP (const char *song)"
.br
.ti -1c
.RI "void \fBspeakerShutdown\fP ()"
.br
.ti -1c
.RI "int \fBsprintf\fP (char *buffer, const char *\fBformatString\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "void \fBstandaloneModeEnable\fP ()"
.br
.ti -1c
.RI "\fBTaskHandle\fP \fBtaskCreate\fP (\fBTaskCode\fP taskCode, const unsigned int stackDepth, void *parameters, const unsigned int priority)"
.br
.ti -1c
.RI "void \fBtaskDelay\fP (const unsigned long msToDelay)"
.br
.ti -1c
.RI "void \fBtaskDelayUntil\fP (unsigned long *previousWakeTime, const unsigned long cycleTime)"
.br
.ti -1c
.RI "void \fBtaskDelete\fP (\fBTaskHandle\fP taskToDelete)"
.br
.ti -1c
.RI "unsigned int \fBtaskGetCount\fP ()"
.br
.ti -1c
.RI "unsigned int \fBtaskGetState\fP (\fBTaskHandle\fP task)"
.br
.ti -1c
.RI "unsigned int \fBtaskPriorityGet\fP (const \fBTaskHandle\fP task)"
.br
.ti -1c
.RI "void \fBtaskPrioritySet\fP (\fBTaskHandle\fP task, const unsigned int newPriority)"
.br
.ti -1c
.RI "void \fBtaskResume\fP (\fBTaskHandle\fP taskToResume)"
.br
.ti -1c
.RI "\fBTaskHandle\fP \fBtaskRunLoop\fP (void(*fn)(void), const unsigned long increment)"
.br
.ti -1c
.RI "void \fBtaskSuspend\fP (\fBTaskHandle\fP taskToSuspend)"
.br
.ti -1c
.RI "int \fBultrasonicGet\fP (\fBUltrasonic\fP ult)"
.br
.ti -1c
.RI "\fBUltrasonic\fP \fBultrasonicInit\fP (unsigned char portEcho, unsigned char portPing)"
.br
.ti -1c
.RI "void \fBultrasonicShutdown\fP (\fBUltrasonic\fP ult)"
.br
.ti -1c
.RI "void \fBusartInit\fP (\fBPROS_FILE\fP *usart, unsigned int baud, unsigned int flags)"
.br
.ti -1c
.RI "void \fBusartShutdown\fP (\fBPROS_FILE\fP *usart)"
.br
.ti -1c
.RI "void \fBwait\fP (const unsigned long time)"
.br
.ti -1c
.RI "void \fBwaitUntil\fP (unsigned long *previousWakeTime, const unsigned long time)"
.br
.ti -1c
.RI "void \fBwatchdogInit\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "void unsigned char const char * \fBformatString\fP"
.br
.ti -1c
.RI "void unsigned char \fBline\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides the high-level user functionality intended for use by typical VEX Cortex programmers\&. 

This file should be included for you in the predefined stubs in each new VEX Cortex PROS project through the inclusion of 'main\&.h'\&. In any new C source file, it is advisable to include \fBmain\&.h\fP instead of referencing \fBAPI\&.h\fP by name, to better handle any nomenclature changes to this file or its contents\&.
.PP
Copyright (c) 2011-2016, Purdue University ACM SIGBots\&. All rights reserved\&.
.PP
This Source Code Form is subject to the terms of the Mozilla Public License, v\&. 2\&.0\&. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/\&.
.PP
PROS contains FreeRTOS (http://www.freertos.org) whose source code may be obtained from http://sourceforge.net/projects/freertos/files/ or on request\&. 
.PP
Definition in file \fBAPI\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ACCEL_X   5"
Analog axis for the X acceleration from the VEX Joystick\&. 
.PP
Definition at line 56 of file API\&.h\&.
.SS "#define ACCEL_Y   6"
Analog axis for the Y acceleration from the VEX Joystick\&. 
.PP
Definition at line 60 of file API\&.h\&.
.SS "#define BOARD_NR_ADC_PINS   8"
There are 8 available analog I/O on the Cortex\&. 
.PP
Definition at line 141 of file API\&.h\&.
.SS "#define BOARD_NR_GPIO_PINS   27"
There are 27 available I/O on the Cortex that can be used for digital communication\&.
.PP
This excludes the crystal ports but includes the Communications, Speaker, and Analog ports\&.
.PP
The motor ports are not on the Cortex and are thus excluded from this count\&. Pin 0 is the Speaker port, pins 1-12 are the standard Digital I/O, 13-20 are the Analog I/O, 21+22 are UART1, 23+24 are UART2, and 25+26 are the I2C port\&. 
.PP
Definition at line 151 of file API\&.h\&.
.SS "#define EOF   ((int)\-1)"
EOF is a value evaluating to -1\&. 
.PP
Definition at line 846 of file API\&.h\&.
.SS "#define FILE   \fBPROS_FILE\fP"
For convenience, FILE is defined as PROS_FILE if it wasn't already defined\&. This provides backwards compatability with PROS, but also allows libraries such as newlib to be incorporated into PROS projects\&. If you're not using C++/newlib, you can disregard this and just use FILE\&. 
.PP
Definition at line 759 of file API\&.h\&.
.SS "#define HIGH   1"
Used for \fBdigitalWrite()\fP to specify a logic HIGH state to output\&.
.PP
In reality, using any non-zero expression or 'true' will work to set a pin to HIGH\&. 
.PP
Definition at line 157 of file API\&.h\&.
.SS "#define IME_ADDR_MAX   0x1F"
IME addresses end at 0x1F\&. Actually using more than 10 (address 0x1A) encoders will cause unreliable communications\&. 
.PP
Definition at line 458 of file API\&.h\&.
.SS "#define INPUT   0x0A"
\fBpinMode()\fP state for digital input, with pullup\&.
.PP
This is the default state for the 12 Digital pins\&. The pullup causes the input to read as 'HIGH' when unplugged, but is fairly weak and can safely be driven by most sources\&. Many VEX digital sensors rely on this behavior and cannot be used with INPUT_FLOATING\&. 
.PP
Definition at line 172 of file API\&.h\&.
.SS "#define INPUT_ANALOG   0x00"
\fBpinMode()\fP state for analog inputs\&.
.PP
This is the default state for the 8 Analog pins and the Speaker port\&. This only works on pins with analog input capabilities; use anywhere else results in undefined behavior\&. 
.PP
Definition at line 179 of file API\&.h\&.
.SS "#define INPUT_FLOATING   0x04"
\fBpinMode()\fP state for digital input, without pullup\&.
.PP
Beware of power consumption, as digital inputs left 'floating' may switch back and forth and cause spurious interrupts\&. 
.PP
Definition at line 186 of file API\&.h\&.
.SS "#define INTERRUPT_EDGE_BOTH   3"
When used in \fBioSetInterrupt()\fP, triggers an interrupt on both rising and falling edges (LOW to HIGH or HIGH to LOW)\&. 
.PP
Definition at line 327 of file API\&.h\&.
.SS "#define INTERRUPT_EDGE_FALLING   2"
When used in \fBioSetInterrupt()\fP, triggers an interrupt on falling edges (HIGH to LOW)\&. 
.PP
Definition at line 322 of file API\&.h\&.
.SS "#define INTERRUPT_EDGE_RISING   1"
When used in \fBioSetInterrupt()\fP, triggers an interrupt on rising edges (LOW to HIGH)\&. 
.PP
Definition at line 318 of file API\&.h\&.
.SS "#define JOY_DOWN   1"
DOWN button (valid on channels 5, 6, 7, 8) 
.PP
Definition at line 40 of file API\&.h\&.
.PP
Referenced by buttonGetState(), and updateIntake()\&.
.SS "#define JOY_LEFT   2"
LEFT button (valid on channels 7, 8) 
.PP
Definition at line 44 of file API\&.h\&.
.PP
Referenced by buttonGetState(), and update_control()\&.
.SS "#define JOY_RIGHT   8"
RIGHT button (valid on channels 7, 8) 
.PP
Definition at line 52 of file API\&.h\&.
.PP
Referenced by buttonGetState(), and update_control()\&.
.SS "#define JOY_UP   4"
UP button (valid on channels 5, 6, 7, 8) 
.PP
Definition at line 48 of file API\&.h\&.
.PP
Referenced by buttonGetState(), and updateIntake()\&.
.SS "#define LCD_BTN_CENTER   2"
CENTER button on LCD for use with \fBlcdReadButtons()\fP 
.PP
Definition at line 1144 of file API\&.h\&.
.PP
Referenced by buttonGetState()\&.
.SS "#define LCD_BTN_LEFT   1"
LEFT button on LCD for use with \fBlcdReadButtons()\fP 
.PP
Definition at line 1140 of file API\&.h\&.
.PP
Referenced by buttonGetState()\&.
.SS "#define LCD_BTN_RIGHT   4"
RIGHT button on LCD for use with \fBlcdReadButtons()\fP 
.PP
Definition at line 1148 of file API\&.h\&.
.PP
Referenced by buttonGetState()\&.
.SS "#define LOW   0"
Used for \fBdigitalWrite()\fP to specify a logic LOW state to output\&.
.PP
In reality, using a zero expression or 'false' will work to set a pin to LOW\&. 
.PP
Definition at line 163 of file API\&.h\&.
.SS "#define OUTPUT   0x01"
\fBpinMode()\fP state for digital output, push-pull\&.
.PP
This is the mode which should be used to output a digital HIGH or LOW value from the Cortex\&. This mode is useful for pneumatic solenoid valves and VEX LEDs\&. 
.PP
Definition at line 193 of file API\&.h\&.
.SS "#define OUTPUT_OD   0x05"
\fBpinMode()\fP state for open-drain outputs\&.
.PP
This is useful in a few cases for external electronics and should not be used for the VEX solenoid or LEDs\&. 
.PP
Definition at line 200 of file API\&.h\&.
.SS "#define SEEK_CUR   1"
SEEK_CUR is used in \fBfseek()\fP to denote an relative position in bytes from the current file location\&. 
.PP
Definition at line 861 of file API\&.h\&.
.SS "#define SEEK_END   2"
SEEK_END is used in \fBfseek()\fP to denote an absolute position in bytes from the end of the file\&. The offset will most likely be negative in this case\&. 
.PP
Definition at line 868 of file API\&.h\&.
.SS "#define SEEK_SET   0"
SEEK_SET is used in \fBfseek()\fP to denote an absolute position in bytes from the start of the file\&. 
.PP
Definition at line 854 of file API\&.h\&.
.SS "#define SERIAL_8N1   0x0000"
Specifies the default serial settings when used in \fBusartInit()\fP 
.PP
Definition at line 793 of file API\&.h\&.
.SS "#define SERIAL_DATABITS_8   0x0000"
Bit mask for \fBusartInit()\fP for 8 data bits (typical) 
.PP
Definition at line 765 of file API\&.h\&.
.SS "#define SERIAL_DATABITS_9   0x1000"
Bit mask for \fBusartInit()\fP for 9 data bits 
.PP
Definition at line 769 of file API\&.h\&.
.SS "#define SERIAL_PARITY_EVEN   0x0400"
Bit mask for \fBusartInit()\fP for Even parity 
.PP
Definition at line 785 of file API\&.h\&.
.SS "#define SERIAL_PARITY_NONE   0x0000"
Bit mask for \fBusartInit()\fP for No parity (typical) 
.PP
Definition at line 781 of file API\&.h\&.
.SS "#define SERIAL_PARITY_ODD   0x0600"
Bit mask for \fBusartInit()\fP for Odd parity 
.PP
Definition at line 789 of file API\&.h\&.
.SS "#define SERIAL_STOPBITS_1   0x0000"
Bit mask for \fBusartInit()\fP for 1 stop bit (typical) 
.PP
Definition at line 773 of file API\&.h\&.
.SS "#define SERIAL_STOPBITS_2   0x2000"
Bit mask for \fBusartInit()\fP for 2 stop bits 
.PP
Definition at line 777 of file API\&.h\&.
.SS "#define stdin   ((\fBPROS_FILE\fP *)3)"
The standard input stream uses the PC debug terminal\&. 
.PP
Definition at line 832 of file API\&.h\&.
.SS "#define stdout   ((\fBPROS_FILE\fP *)3)"
The standard output stream uses the PC debug terminal\&. 
.PP
Definition at line 828 of file API\&.h\&.
.SS "#define TASK_DEAD   0"
Constant returned from \fBtaskGetState()\fP when the task is dead or nonexistant\&. 
.PP
Definition at line 1275 of file API\&.h\&.
.SS "#define TASK_DEFAULT_STACK_SIZE   512"
The recommended stack size for a new task that does an average amount of work\&. This stack size is used for default tasks such as \fBautonomous()\fP\&.
.PP
This is probably OK for 4-5 levels of function calls and the use of \fBprintf()\fP with several arguments\&. Tasks requiring deep recursion or large local buffers will need a bigger stack\&. 
.PP
Definition at line 1262 of file API\&.h\&.
.SS "#define TASK_MAX   16"
Only this many tasks can exist at once\&. Attempts to create further tasks will not succeed until tasks end or are destroyed, AND the idle task cleans them up\&.
.PP
Changing this value will not change the limit without a kernel recompile\&. The idle task and VEX daemon task count against the limit\&. The user \fBautonomous()\fP or teleop() also counts against the limit, so 12 tasks usually remain for other uses\&. 
.PP
Definition at line 1232 of file API\&.h\&.
.SS "#define TASK_MAX_PRIORITIES   6"
The maximum number of available task priorities, which run from 0 to 5\&.
.PP
Changing this value will not change the priority count without a kernel recompile\&. 
.PP
Definition at line 1238 of file API\&.h\&.
.SS "#define TASK_MINIMAL_STACK_SIZE   64"
The minimum stack depth for a task\&. Scheduler state is stored on the stack, so even if the task never uses the stack, at least this much space must be allocated\&.
.PP
Function calls and other seemingly innocent constructs may place information on the stack\&. Err on the side of a larger stack when possible\&. 
.PP
Definition at line 1270 of file API\&.h\&.
.SS "#define TASK_PRIORITY_DEFAULT   2"
The default task priority, which should be used for most tasks\&.
.PP
Default tasks such as \fBautonomous()\fP inherit this priority\&. 
.PP
Definition at line 1249 of file API\&.h\&.
.SS "#define TASK_PRIORITY_HIGHEST   (\fBTASK_MAX_PRIORITIES\fP \- 1)"
The highest priority that can be assigned to a task\&. Unlike the lowest priority, this priority can be safely used without hampering interrupts\&. Beware of deadlock\&. 
.PP
Definition at line 1254 of file API\&.h\&.
.SS "#define TASK_PRIORITY_LOWEST   0"
The lowest priority that can be assigned to a task, which puts it on a level with the idle task\&. This may cause severe performance problems and is generally not recommended\&. 
.PP
Definition at line 1243 of file API\&.h\&.
.SS "#define TASK_RUNNABLE   2"
Constant returned from \fBtaskGetState()\fP when the task is exists and is available to run, but not currently running\&. 
.PP
Definition at line 1284 of file API\&.h\&.
.SS "#define TASK_RUNNING   1"
Constant returned from \fBtaskGetState()\fP when the task is actively executing\&. 
.PP
Definition at line 1279 of file API\&.h\&.
.SS "#define TASK_SLEEPING   3"
Constant returned from \fBtaskGetState()\fP when the task is delayed or blocked waiting for a semaphore, mutex, or I/O operation\&. 
.PP
Definition at line 1289 of file API\&.h\&.
.SS "#define TASK_SUSPENDED   4"
Constant returned from \fBtaskGetState()\fP when the task is suspended using \fBtaskSuspend()\fP\&. 
.PP
Definition at line 1293 of file API\&.h\&.
.SS "#define uart1   ((\fBPROS_FILE\fP *)1)"
UART 1 on the Cortex; must be opened first using \fBusartInit()\fP\&. 
.PP
Definition at line 836 of file API\&.h\&.
.PP
Referenced by buttonGetState()\&.
.SS "#define uart2   ((\fBPROS_FILE\fP *)2)"
UART 2 on the Cortex; must be opened first using \fBusartInit()\fP\&. 
.PP
Definition at line 840 of file API\&.h\&.
.SS "#define ULTRA_BAD_RESPONSE   \-1"
This value is returned if the sensor cannot find a reasonable value to return\&. 
.PP
Definition at line 650 of file API\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef void* \fBEncoder\fP"
Reference type for an initialized encoder\&.
.PP
Encoder information is stored as an opaque pointer to a structure in memory; as this is a pointer type, it can be safely passed or stored by value\&. 
.PP
Definition at line 605 of file API\&.h\&.
.SS "typedef void* \fBGyro\fP"
Reference type for an initialized gyro\&.
.PP
Gyro information is stored as an opaque pointer to a structure in memory; as this is a pointer type, it can be safely passed or stored by value\&. 
.PP
Definition at line 548 of file API\&.h\&.
.SS "typedef void(* InterruptHandler) (unsigned char pin)"
Type definition for interrupt handlers\&. Such functions must accept one argument indicating the pin which changed\&. 
.PP
Definition at line 332 of file API\&.h\&.
.SS "typedef void* \fBMutex\fP"
Type by which mutexes are referenced\&.
.PP
As this is a pointer type, it can be safely passed or stored by value\&. 
.PP
Definition at line 1306 of file API\&.h\&.
.SS "typedef int \fBPROS_FILE\fP"
PROS_FILE is an integer referring to a stream for the standard I/O functions\&.
.PP
PROS_FILE * is the standard library method of referring to a file pointer, even though there is actually nothing there\&. 
.PP
Definition at line 750 of file API\&.h\&.
.SS "typedef void* \fBSemaphore\fP"
Type by which semaphores are referenced\&.
.PP
As this is a pointer type, it can be safely passed or stored by value\&. 
.PP
Definition at line 1312 of file API\&.h\&.
.SS "typedef void(* TaskCode) (void *)"
Type for defining task functions\&. Task functions must accept one parameter of type 'void *'; they need not use it\&.
.PP
For example:
.PP
void MyTask(void *ignore) { while (1); } 
.PP
Definition at line 1323 of file API\&.h\&.
.SS "typedef void* \fBTaskHandle\fP"
Type by which tasks are referenced\&.
.PP
As this is a pointer type, it can be safely passed or stored by value\&. 
.PP
Definition at line 1300 of file API\&.h\&.
.SS "typedef void* \fBUltrasonic\fP"
Reference type for an initialized ultrasonic sensor\&.
.PP
Ultrasonic information is stored as an opaque pointer to a structure in memory; as this is a pointer type, it can be safely passed or stored by value\&. 
.PP
Definition at line 658 of file API\&.h\&.
.SH "Function Documentation"
.PP 
.SS "void __attribute__ ((format(\fBprintf\fP, 3, 4)))"
Prints the formatted string to the attached LCD\&.
.PP
The output string will be truncated as necessary to fit on the LCD screen, 16 characters wide\&. It is probably better to generate the string in a local buffer and use \fBlcdSetText()\fP but this method is provided for convenience\&.
.PP
\fBParameters:\fP
.RS 4
\fIlcdPort\fP the LCD to write, either uart1 or uart2 
.br
\fIline\fP the LCD line to write, either 1 or 2 
.br
\fIformatString\fP the format string as specified in \fBfprintf()\fP 
.RE
.PP

.SS "int analogCalibrate (unsigned char channel)"
Calibrates the analog sensor on the specified channel\&.
.PP
This method assumes that the true sensor value is not actively changing at this time and computes an average from approximately 500 samples, 1 ms apart, for a 0\&.5 s period of calibration\&. The average value thus calculated is returned and stored for later calls to the \fBanalogReadCalibrated()\fP and \fBanalogReadCalibratedHR()\fP functions\&. These functions will return the difference between this value and the current sensor value when called\&.
.PP
Do not use this function in \fBinitializeIO()\fP, or when the sensor value might be unstable (gyro rotation, accelerometer movement)\&.
.PP
This function may not work properly if the VEX Cortex is tethered to a PC using the orange USB A to A cable and has no VEX 7\&.2V Battery connected and powered on, as the VEX Battery provides power to sensors\&.
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP the channel to calibrate from 1-8 
.RE
.PP
\fBReturns:\fP
.RS 4
the average sensor value computed by this function 
.RE
.PP

.SS "int analogRead (unsigned char channel)"
Reads an analog input channel and returns the 12-bit value\&.
.PP
The value returned is undefined if the analog pin has been switched to a different mode\&. This function is Wiring-compatible with the exception of the larger output range\&. The meaning of the returned value varies depending on the sensor attached\&.
.PP
This function may not work properly if the VEX Cortex is tethered to a PC using the orange USB A to A cable and has no VEX 7\&.2V Battery connected and powered on, as the VEX Battery provides power to sensors\&.
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP the channel to read from 1-8 
.RE
.PP
\fBReturns:\fP
.RS 4
the analog sensor value, where a value of 0 reflects an input voltage of nearly 0 V and a value of 4095 reflects an input voltage of nearly 5 V 
.RE
.PP

.PP
Referenced by autonomous(), getClawTicks(), and getLifterTicks()\&.
.SS "int analogReadCalibrated (unsigned char channel)"
Reads the calibrated value of an analog input channel\&.
.PP
The \fBanalogCalibrate()\fP function must be run first on that channel\&. This function is inappropriate for sensor values intended for integration, as round-off error can accumulate causing drift over time\&. Use \fBanalogReadCalibratedHR()\fP instead\&.
.PP
This function may not work properly if the VEX Cortex is tethered to a PC using the orange USB A to A cable and has no VEX 7\&.2V Battery connected and powered on, as the VEX Battery provides power to sensors\&.
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP the channel to read from 1-8 
.RE
.PP
\fBReturns:\fP
.RS 4
the difference of the sensor value from its calibrated default from -4095 to 4095 
.RE
.PP

.SS "int analogReadCalibratedHR (unsigned char channel)"
Reads the calibrated value of an analog input channel 1-8 with enhanced precision\&.
.PP
The \fBanalogCalibrate()\fP function must be run first\&. This is intended for integrated sensor values such as gyros and accelerometers to reduce drift due to round-off, and should not be used on a sensor such as a line tracker or potentiometer\&.
.PP
The value returned actually has 16 bits of 'precision', even though the ADC only reads 12 bits, so that errors induced by the average value being between two values come out in the wash when integrated over time\&. Think of the value as the true value times 16\&.
.PP
This function may not work properly if the VEX Cortex is tethered to a PC using the orange USB A to A cable and has no VEX 7\&.2V Battery connected and powered on, as the VEX Battery provides power to sensors\&.
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP the channel to read from 1-8 
.RE
.PP
\fBReturns:\fP
.RS 4
the difference of the sensor value from its calibrated default from -16384 to 16384 
.RE
.PP

.PP
Referenced by calculate_accelerometer_odemetry()\&.
.SS "void delay (const unsigned long time)"
Wiring-compatible alias of \fBtaskDelay()\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fItime\fP the duration of the delay in milliseconds (1 000 milliseconds per second) 
.RE
.PP

.PP
Referenced by autonomous(), display_menu(), operatorControl(), and promt_confirmation()\&.
.SS "void delayMicroseconds (const unsigned long us)"
Wait for approximately the given number of microseconds\&.
.PP
The method used for delaying this length of time may vary depending on the argument\&. The current task will always be delayed by at least the specified period, but possibly much more depending on CPU load\&. In general, this function is less reliable than \fBdelay()\fP\&. Using this function in a loop may hog processing time from other tasks\&.
.PP
\fBParameters:\fP
.RS 4
\fIus\fP the duration of the delay in microseconds (1 000 000 microseconds per second) 
.RE
.PP

.SS "bool digitalRead (unsigned char pin)"
Gets the digital value (1 or 0) of a pin configured as a digital input\&.
.PP
If the pin is configured as some other mode, the digital value which reflects the current state of the pin is returned, which may or may not differ from the currently set value\&. The return value is undefined for pins configured as Analog inputs, or for ports in use by a Communications interface\&. This function is Wiring-compatible\&.
.PP
This function may not work properly if the VEX Cortex is tethered to a PC using the orange USB A to A cable and has no VEX 7\&.2V Battery connected and powered on, as the VEX Battery provides power to sensors\&.
.PP
\fBParameters:\fP
.RS 4
\fIpin\fP the pin to read from 1-26 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the pin is HIGH, or false if it is LOW 
.RE
.PP

.SS "void digitalWrite (unsigned char pin, bool value)"
Sets the digital value (1 or 0) of a pin configured as a digital output\&.
.PP
If the pin is configured as some other mode, behavior is undefined\&. This function is Wiring-compatible\&.
.PP
\fBParameters:\fP
.RS 4
\fIpin\fP the pin to write from 1-26 
.br
\fIvalue\fP an expression evaluating to 'true' or 'false' to set the output to HIGH or LOW respectively, or the constants HIGH or LOW themselves 
.RE
.PP

.SS "int encoderGet (\fBEncoder\fP enc)"
Gets the number of ticks recorded by the encoder\&.
.PP
There are 360 ticks in one revolution\&.
.PP
\fBParameters:\fP
.RS 4
\fIenc\fP the Encoder object from \fBencoderInit()\fP to read 
.RE
.PP
\fBReturns:\fP
.RS 4
the signed and cumulative number of counts since the last start or reset 
.RE
.PP

.SS "\fBEncoder\fP encoderInit (unsigned char portTop, unsigned char portBottom, bool reverse)"
Initializes and enables a quadrature encoder on two digital ports\&.
.PP
Neither the top port nor the bottom port can be digital port 10\&. NULL will be returned if either port is invalid or the encoder is already in use\&. Initializing an encoder implicitly resets its count\&.
.PP
\fBParameters:\fP
.RS 4
\fIportTop\fP the 'top' wire from the encoder sensor with the removable cover side UP 
.br
\fIportBottom\fP the 'bottom' wire from the encoder sensor 
.br
\fIreverse\fP if 'true', the sensor will count in the opposite direction 
.RE
.PP
\fBReturns:\fP
.RS 4
an Encoder object to be stored and used for later calls to encoder functions 
.RE
.PP

.SS "void encoderReset (\fBEncoder\fP enc)"
Resets the encoder to zero\&.
.PP
It is safe to use this method while an encoder is enabled\&. It is not necessary to call this method before stopping or starting an encoder\&.
.PP
\fBParameters:\fP
.RS 4
\fIenc\fP the Encoder object from \fBencoderInit()\fP to reset 
.RE
.PP

.SS "void encoderShutdown (\fBEncoder\fP enc)"
Stops and disables the encoder\&.
.PP
Encoders use processing power, so disabling unused encoders increases code performance\&. The encoder's count will be retained\&.
.PP
\fBParameters:\fP
.RS 4
\fIenc\fP the Encoder object from \fBencoderInit()\fP to stop 
.RE
.PP

.SS "void fclose (\fBPROS_FILE\fP * stream)"
Closes the specified file descriptor\&. This function does not work on communication ports; use \fBusartShutdown()\fP instead\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP the file descriptor to close from \fBfopen()\fP 
.RE
.PP

.SS "int fcount (\fBPROS_FILE\fP * stream)"
Returns the number of characters that can be read without blocking (the number of characters available) from the specified stream\&. This only works for communication ports and files in Read mode; for files in Write mode, 0 is always returned\&.
.PP
This function may underestimate, but will not overestimate, the number of characters which meet this criterion\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP the stream to read (stdin, uart1, uart2, or an open file in Read mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of characters which meet this criterion; if this number cannot be determined, returns 0 
.RE
.PP

.SS "int fdelete (const char * file)"
Delete the specified file if it exists and is not currently open\&.
.PP
The file will actually be erased from memory on the next re-boot\&. A physical power cycle is required to purge deleted files and free their allocated space for new files to be written\&. Deleted files are still considered inaccessible to \fBfopen()\fP in Read mode\&.
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP the file name to erase 
.RE
.PP
\fBReturns:\fP
.RS 4
0 if the file was deleted, or 1 if the file could not be found 
.RE
.PP

.SS "int feof (\fBPROS_FILE\fP * stream)"
Checks to see if the specified stream is at its end\&. This only works for communication ports and files in Read mode; for files in Write mode, 1 is always returned\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP the channel to check (stdin, uart1, uart2, or an open file in Read mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
0 if the stream is not at EOF, or 1 otherwise\&. 
.RE
.PP

.SS "int fflush (\fBPROS_FILE\fP * stream)"
Flushes the data on the specified file channel open in Write mode\&. This function has no effect on a communication port or a file in Read mode, as these streams are always flushed as quickly as possible by the kernel\&.
.PP
Successful completion of an fflush function on a file in Write mode cannot guarantee that the file is vaild until \fBfclose()\fP is used on that file descriptor\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP the channel to flush (an open file in Write mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
0 if the data was successfully flushed, EOF otherwise 
.RE
.PP

.SS "int fgetc (\fBPROS_FILE\fP * stream)"
Reads and returns one character from the specified stream, blocking until complete\&.
.PP
Do not use \fBfgetc()\fP on a VEX LCD port; deadlock may occur\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP the stream to read (stdin, uart1, uart2, or an open file in Read mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
the next character from 0 to 255, or -1 if no character can be read 
.RE
.PP

.SS "char* fgets (char * str, int num, \fBPROS_FILE\fP * stream)"
Reads a string from the specified stream, storing the characters into the memory at str\&. Characters will be read until the specified limit is reached, a new line is found, or the end of file is reached\&.
.PP
If the stream is already at end of file (for files in Read mode), NULL will be returned; otherwise, at least one character will be read and stored into str\&.
.PP
\fBParameters:\fP
.RS 4
\fIstr\fP the location where the characters read will be stored 
.br
\fInum\fP the maximum number of characters to store; at most (num - 1) characters will be read, with a null terminator ('\\0') automatically appended 
.br
\fIstream\fP the channel to read (stdin, uart1, uart2, or an open file in Read mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
str, or NULL if zero characters could be read 
.RE
.PP

.SS "\fBPROS_FILE\fP* fopen (const char * file, const char * mode)"
Opens the given file in the specified mode\&. The file name is truncated to eight characters\&. Only four files can be in use simultaneously in any given time, with at most one of those files in Write mode\&. This function does not work on communication ports; use \fBusartInit()\fP instead\&.
.PP
mode can be 'r' or 'w'\&. Due to the nature of the VEX Cortex memory, the 'r+', 'w+', and 'a' modes are not supported by the file system\&.
.PP
Opening a file that does not exist in Read mode will fail and return NULL, but opening a new file in Write mode will create it if there is space\&. Opening a file that already exists in Write mode will destroy the contents and create a new blank file if space is available\&.
.PP
There are important considerations when using of the file system on the VEX Cortex\&. Reading from files is safe, but writing to files should only be performed when robot actuators have been stopped\&. PROS will attempt to continue to handle events during file writes, but most user tasks cannot execute during file writing\&. Powering down the VEX Cortex mid-write may cause file system corruption\&.
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP the file name 
.br
\fImode\fP the file mode 
.RE
.PP
\fBReturns:\fP
.RS 4
a file descriptor pointing to the new file, or NULL if the file could not be opened 
.RE
.PP

.SS "void fprint (const char * string, \fBPROS_FILE\fP * stream)"
Prints the simple string to the specified stream\&.
.PP
This method is much, much faster than \fBfprintf()\fP and does not add a new line like \fBfputs()\fP\&. Do not use \fBfprint()\fP on a VEX LCD port\&. Use \fBlcdSetText()\fP instead\&.
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP the string to write 
.br
\fIstream\fP the stream to write (stdout, uart1, uart2, or an open file in Write mode) 
.RE
.PP

.SS "int fprintf (\fBPROS_FILE\fP * stream, const char * formatString,  \&.\&.\&.)"
Prints the formatted string to the specified output stream\&.
.PP
The specifiers supported by this minimalistic \fBprintf()\fP function are:
.IP "\(bu" 2
\fC%d:\fP Signed integer in base 10 (int)
.IP "\(bu" 2
\fC%u:\fP Unsigned integer in base 10 (unsigned int)
.IP "\(bu" 2
\fC%x\fP, \fC%X:\fP Integer in base 16 (unsigned int, int)
.IP "\(bu" 2
\fC%p:\fP Pointer (void *, int *, \&.\&.\&.)
.IP "\(bu" 2
\fC%c:\fP Character (char)
.IP "\(bu" 2
\fC%s:\fP Null-terminated string (char *)
.IP "\(bu" 2
\fC%%\fP: Single literal percent sign
.IP "\(bu" 2
\fC%f:\fP Floating-point number
.PP
.PP
Specifiers can be modified with:
.IP "\(bu" 2
\fC0\fP: Zero-pad, instead of space-pad
.IP "\(bu" 2
\fCa\&.b:\fP Make the field at least 'a' characters wide\&. If 'b' is specified for '%f', changes the number of digits after the decimal point
.IP "\(bu" 2
\fC-\fP: Left-align, instead of right-align
.IP "\(bu" 2
\fC+\fP: Always display the sign character (displays a leading '+' for positive numbers)
.IP "\(bu" 2
\fCl:\fP Ignored for compatibility
.PP
.PP
Invalid format specifiers, or mismatched parameters to specifiers, cause undefined behavior\&. Other characters are written out verbatim\&. Do not use \fBfprintf()\fP on a VEX LCD port\&. Use lcdPrint() instead\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP the stream to write (stdout, uart1, or uart2) 
.br
\fIformatString\fP the format string as specified above 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of characters written 
.RE
.PP

.PP
Referenced by assert()\&.
.SS "int fputc (int value, \fBPROS_FILE\fP * stream)"
Writes one character to the specified stream\&.
.PP
Do not use \fBfputc()\fP on a VEX LCD port\&. Use \fBlcdSetText()\fP instead\&.
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP the character to write (a value of type 'char' can be used) 
.br
\fIstream\fP the stream to write (stdout, uart1, uart2, or an open file in Write mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
the character written 
.RE
.PP

.SS "int fputs (const char * string, \fBPROS_FILE\fP * stream)"
Behaves the same as the 'fprint' function, and appends a trailing newline ('\\n')\&.
.PP
Do not use \fBfputs()\fP on a VEX LCD port\&. Use \fBlcdSetText()\fP instead\&.
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP the string to write 
.br
\fIstream\fP the stream to write (stdout, uart1, uart2, or an open file in Write mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of characters written, excluding the new line 
.RE
.PP

.SS "size_t fread (void * ptr, size_t size, size_t count, \fBPROS_FILE\fP * stream)"
Reads data from a stream into memory\&. Returns the number of bytes thus read\&.
.PP
If the memory at ptr cannot store (size * count) bytes, undefined behavior occurs\&.
.PP
\fBParameters:\fP
.RS 4
\fIptr\fP a pointer to where the data will be stored 
.br
\fIsize\fP the size of each data element to read in bytes 
.br
\fIcount\fP the number of data elements to read 
.br
\fIstream\fP the stream to read (stdout, uart1, uart2, or an open file in Read mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of bytes successfully read 
.RE
.PP

.SS "int fseek (\fBPROS_FILE\fP * stream, long int offset, int origin)"
Seeks within a file open in Read mode\&. This function will fail when used on a file in Write mode or on any communications port\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP the stream to seek within 
.br
\fIoffset\fP the location within the stream to seek 
.br
\fIorigin\fP the reference location for offset: SEEK_CUR, SEEK_SET, or SEEK_END 
.RE
.PP
\fBReturns:\fP
.RS 4
0 if the seek was successful, or 1 otherwise 
.RE
.PP

.SS "long int ftell (\fBPROS_FILE\fP * stream)"
Returns the current position of the stream\&. This function works on files in either Read or Write mode, but will fail on communications ports\&.
.PP
\fBParameters:\fP
.RS 4
\fIstream\fP the stream to check 
.RE
.PP
\fBReturns:\fP
.RS 4
the offset of the stream, or -1 if the offset could not be determined 
.RE
.PP

.SS "size_t fwrite (const void * ptr, size_t size, size_t count, \fBPROS_FILE\fP * stream)"
Writes data from memory to a stream\&. Returns the number of bytes thus written\&.
.PP
If the memory at ptr is not as long as (size * count) bytes, undefined behavior occurs\&.
.PP
\fBParameters:\fP
.RS 4
\fIptr\fP a pointer to the data to write 
.br
\fIsize\fP the size of each data element to write in bytes 
.br
\fIcount\fP the number of data elements to write 
.br
\fIstream\fP the stream to write (stdout, uart1, uart2, or an open file in Write mode) 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of bytes successfully written 
.RE
.PP

.SS "int getchar ()"
Reads and returns one character from 'stdin', which is the PC debug terminal\&.
.PP
\fBReturns:\fP
.RS 4
the next character from 0 to 255, or -1 if no character can be read 
.RE
.PP

.SS "int gyroGet (\fBGyro\fP gyro)"
Gets the current gyro angle in degrees, rounded to the nearest degree\&.
.PP
There are 360 degrees in a circle\&.
.PP
\fBParameters:\fP
.RS 4
\fIgyro\fP the Gyro object from \fBgyroInit()\fP to read 
.RE
.PP
\fBReturns:\fP
.RS 4
the signed and cumulative number of degrees rotated around the gyro's vertical axis since the last start or reset 
.RE
.PP

.PP
Referenced by calculate_gryo_anglular_velocity()\&.
.SS "\fBGyro\fP gyroInit (unsigned char port, unsigned short multiplier)"
Initializes and enables a gyro on an analog port\&.
.PP
NULL will be returned if the port is invalid or the gyro is already in use\&. Initializing a gyro implicitly calibrates it and resets its count\&. Do not move the robot while the gyro is being calibrated\&. It is suggested to call this function in \fBinitialize()\fP and to place the robot in its final position before powering it on\&.
.PP
The multiplier parameter can tune the gyro to adapt to specific sensors\&. The default value at this time is 196; higher values will increase the number of degrees reported for a fixed actual rotation, while lower values will decrease the number of degrees reported\&. If your robot is consistently turning too far, increase the multiplier, and if it is not turning far enough, decrease the multiplier\&.
.PP
\fBParameters:\fP
.RS 4
\fIport\fP the analog port to use from 1-8 
.br
\fImultiplier\fP an optional constant to tune the gyro readings; use 0 for the default value 
.RE
.PP
\fBReturns:\fP
.RS 4
a Gyro object to be stored and used for later calls to gyro functions 
.RE
.PP

.PP
Referenced by init_localization()\&.
.SS "void gyroReset (\fBGyro\fP gyro)"
Resets the gyro to zero\&.
.PP
It is safe to use this method while a gyro is enabled\&. It is not necessary to call this method before stopping or starting a gyro\&.
.PP
\fBParameters:\fP
.RS 4
\fIgyro\fP the Gyro object from \fBgyroInit()\fP to reset 
.RE
.PP

.SS "void gyroShutdown (\fBGyro\fP gyro)"
Stops and disables the gyro\&.
.PP
Gyros use processing power, so disabling unused gyros increases code performance\&. The gyro's position will be retained\&.
.PP
\fBParameters:\fP
.RS 4
\fIgyro\fP the Gyro object from \fBgyroInit()\fP to stop 
.RE
.PP

.SS "bool i2cRead (uint8_t addr, uint8_t * data, uint16_t count)"
i2cRead - Reads the specified number of data bytes from the specified 7-bit I2C address\&. The bytes will be stored at the specified location\&. Returns true if successful or false if failed\&. If only some bytes could be read, false is still returned\&.
.PP
The I2C address should be right-aligned; the R/W bit is automatically supplied\&.
.PP
Since most I2C devices use an 8-bit register architecture, this method has limited usefulness\&. Consider i2cReadRegister instead for the vast majority of applications\&. 
.SS "bool i2cReadRegister (uint8_t addr, uint8_t reg, uint8_t * value, uint16_t count)"
i2cReadRegister - Reads the specified amount of data from the given register address on the specified 7-bit I2C address\&. Returns true if successful or false if failed\&. If only some bytes could be read, false is still returned\&.
.PP
The I2C address should be right-aligned; the R/W bit is automatically supplied\&.
.PP
Most I2C devices support an auto-increment address feature, so using this method to read more than one byte will usually read a block of sequential registers\&. Try to merge reads to separate registers into a larger read using this function whenever possible to improve code reliability, even if a few intermediate values need to be thrown away\&. 
.SS "bool i2cWrite (uint8_t addr, uint8_t * data, uint16_t count)"
i2cWrite - Writes the specified number of data bytes to the specified 7-bit I2C address\&. Returns true if successful or false if failed\&. If only smoe bytes could be written, false is still returned\&.
.PP
The I2C address should be right-aligned; the R/W bit is automatically supplied\&.
.PP
Since most I2C devices use an 8-bit register architecture, this method is mostly useful for setting the register position (most devices remember the last-used address) or writing a sequence of bytes to one register address using an auto-increment feature\&. In these cases, the first byte written from the data buffer should have the register address to use\&. 
.SS "bool i2cWriteRegister (uint8_t addr, uint8_t reg, uint16_t value)"
i2cWriteRegister - Writes the specified data byte to a register address on the specified 7-bit I2C address\&. Returns true if successful or false if failed\&.
.PP
The I2C address should be right-aligned; the R/W bit is automatically supplied\&.
.PP
Only one byte can be written to each register address using this method\&. While useful for the vast majority of I2C operations, writing multiple bytes requires the i2cWrite method\&. 
.SS "bool imeGet (unsigned char address, int * value)"
Gets the current 32-bit count of the specified IME\&.
.PP
Much like the count for a quadrature encoder, the tick count is signed and cumulative\&. The value reflects total counts since the last reset\&. Different VEX Motor Encoders have a different number of counts per revolution:
.PP
.IP "\(bu" 2
\fC240\&.448\fP for the 269 IME
.IP "\(bu" 2
\fC627\&.2\fP for the 393 IME in high torque mode (factory default)
.IP "\(bu" 2
\fC392\fP for the 393 IME in high speed mode
.PP
.PP
If the IME address is invalid, or the IME has not been reset or initialized, the value stored in *value is undefined\&.
.PP
\fBParameters:\fP
.RS 4
\fIaddress\fP the IME address to fetch from 0 to IME_ADDR_MAX 
.br
\fIvalue\fP a pointer to the location where the value will be stored (obtained using the '&' operator on the target variable name e\&.g\&. \fCimeGet(2, &counts)\fP) 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the count was successfully read and the value stored in *value is valid; false otherwise 
.RE
.PP

.PP
Referenced by autonomous(), and get_encoder_ticks()\&.
.SS "bool imeGetVelocity (unsigned char address, int * value)"
Gets the current rotational velocity of the specified IME\&.
.PP
In this version of PROS, the velocity is positive if the IME count is increasing and negative if the IME count is decreasing\&. The velocity is in RPM of the internal encoder wheel\&. Since checking the IME for its type cannot reveal whether the motor gearing is high speed or high torque (in the 2-Wire Motor 393 case), the user must divide the return value by the number of output revolutions per encoder revolution:
.PP
.IP "\(bu" 2
\fC30\&.056\fP for the 269 IME
.IP "\(bu" 2
\fC39\&.2\fP for the 393 IME in high torque mode (factory default)
.IP "\(bu" 2
\fC24\&.5\fP for the 393 IME in high speed mode
.PP
.PP
If the IME address is invalid, or the IME has not been reset or initialized, the value stored in *value is undefined\&.
.PP
\fBParameters:\fP
.RS 4
\fIaddress\fP the IME address to fetch from 0 to IME_ADDR_MAX 
.br
\fIvalue\fP a pointer to the location where the value will be stored (obtained using the '&' operator on the target variable name e\&.g\&. \fCimeGetVelocity(2, &counts)\fP) 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the velocity was successfully read and the value stored in *value is valid; false otherwise 
.RE
.PP

.PP
Referenced by get_encoder_velocity()\&.
.SS "unsigned int imeInitializeAll ()"
Initializes all IMEs\&.
.PP
IMEs are assigned sequential incrementing addresses, beginning with the first IME on the chain (closest to the VEX Cortex I2C port)\&. Therefore, a given configuration of IMEs will always have the same ID assigned to each encoder\&. The addresses range from 0 to IME_ADDR_MAX, so the first encoder gets 0, the second gets 1, \&.\&.\&.
.PP
This function should most likely be used in \fBinitialize()\fP\&. Do not use it in \fBinitializeIO()\fP or at any other time when the scheduler is paused (like an interrupt)\&. Checking the return value of this function is important to ensure that all IMEs are plugged in and responding as expected\&.
.PP
This function, unlike the other IME functions, is not thread safe\&. If using imeInitializeAll to re-initialize encoders, calls to other IME functions might behave unpredictably during this function's execution\&.
.PP
\fBReturns:\fP
.RS 4
the number of IMEs successfully initialized\&. 
.RE
.PP

.PP
Referenced by init_encoders(), and initialize()\&.
.SS "bool imeReset (unsigned char address)"
Resets the specified IME's counters to zero\&.
.PP
This method can be used while the IME is rotating\&.
.PP
\fBParameters:\fP
.RS 4
\fIaddress\fP the IME address to reset from 0 to IME_ADDR_MAX 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the reset succeeded; false otherwise 
.RE
.PP

.PP
Referenced by autonomous()\&.
.SS "void imeShutdown ()"
Shuts down all IMEs on the chain; their addresses return to the default and the stored counts and velocities are lost\&. This function, unlike the other IME functions, is not thread safe\&.
.PP
To use the IME chain again, wait at least 0\&.25 seconds before using imeInitializeAll again\&. 
.SS "void ioClearInterrupt (unsigned char pin)"
Disables interrupts on the specified pin\&.
.PP
Disabling interrupts on interrupt pins which are not in use conserves processing time\&.
.PP
\fBParameters:\fP
.RS 4
\fIpin\fP the pin on which to reset interrupts from 1-9,11-12 
.RE
.PP

.SS "void ioSetInterrupt (unsigned char pin, unsigned char edges, \fBInterruptHandler\fP handler)"
Sets up an interrupt to occur on the specified pin, and resets any counters or timers associated with the pin\&.
.PP
Each time the specified change occurs, the function pointer passed in will be called with the pin that changed as an argument\&. Enabling pin-change interrupts consumes processing time, so it is best to only enable necessary interrupts and to keep the InterruptHandler function short\&. Pin change interrupts can only be enabled on pins 1-9 and 11-12\&.
.PP
Do not use API functions such as \fBdelay()\fP inside the handler function, as the function will run in an ISR where the scheduler is paused and no other interrupts can execute\&. It is best to quickly update some state and allow a task to perform the work\&.
.PP
Do not use this function on pins that are also being used by the built-in ultrasonic or shaft encoder drivers, or on pins which have been switched to output mode\&.
.PP
\fBParameters:\fP
.RS 4
\fIpin\fP the pin on which to enable interrupts from 1-9,11-12 
.br
\fIedges\fP one of INTERRUPT_EDGE_RISING, INTERRUPT_EDGE_FALLING, or INTERRUPT_EDGE_BOTH 
.br
\fIhandler\fP the function to call when the condition is satisfied 
.RE
.PP

.SS "bool isAutonomous ()"
Returns true if the robot is in autonomous mode, or false otherwise\&.
.PP
While in autonomous mode, joystick inputs will return a neutral value, but serial port communications (even over VexNET) will still work properly\&. 
.SS "bool isEnabled ()"
Returns true if the robot is enabled, or false otherwise\&.
.PP
While disabled via the VEX Competition Switch or VEX Field Controller, motors will not function\&. However, the digital I/O ports can still be changed, which may indirectly affect the robot state (e\&.g\&. solenoids)\&. Avoid performing externally visible actions while disabled (the kernel should take care of this most of the time)\&. 
.PP
Referenced by display_menu()\&.
.SS "bool isJoystickConnected (unsigned char joystick)"
Returns true if a joystick is connected to the specified slot number (1 or 2), or false otherwise\&.
.PP
Useful for automatically merging joysticks for one operator, or splitting for two\&. This function does not work properly during \fBinitialize()\fP or \fBinitializeIO()\fP and can return false positives\&. It should be checked once and stored at the beginning of \fBoperatorControl()\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIjoystick\fP the joystick slot to check 
.RE
.PP

.SS "bool isOnline ()"
Returns true if a VEX field controller or competition switch is connected, or false otherwise\&.
.PP
When in online mode, the switching between \fBautonomous()\fP and \fBoperatorControl()\fP tasks is managed by the PROS kernel\&. 
.SS "int joystickGetAnalog (unsigned char joystick, unsigned char axis)"
Gets the value of a control axis on the VEX joystick\&. Returns the value from -127 to 127, or 0 if no joystick is connected to the requested slot\&.
.PP
\fBParameters:\fP
.RS 4
\fIjoystick\fP the joystick slot to check 
.br
\fIaxis\fP one of 1, 2, 3, 4, ACCEL_X, or ACCEL_Y 
.RE
.PP

.PP
Referenced by get_joystick_cord(), and update_drive_motors()\&.
.SS "bool joystickGetDigital (unsigned char joystick, unsigned char buttonGroup, unsigned char button)"
Gets the value of a button on the VEX joystick\&. Returns true if that button is pressed, or false otherwise\&. If no joystick is connected to the requested slot, returns false\&.
.PP
\fBParameters:\fP
.RS 4
\fIjoystick\fP the joystick slot to check 
.br
\fIbuttonGroup\fP one of 5, 6, 7, or 8 to request that button as labelled on the joystick 
.br
\fIbutton\fP one of JOY_UP, JOY_DOWN, JOY_LEFT, or JOY_RIGHT; requesting JOY_LEFT or JOY_RIGHT for groups 5 or 6 will cause an undefined value to be returned 
.RE
.PP

.PP
Referenced by buttonGetState(), update_claw(), update_control(), update_lifter(), and updateIntake()\&.
.SS "void lcdClear (\fBPROS_FILE\fP * lcdPort)"
Clears the LCD screen on the specified port\&.
.PP
Printing to a line implicitly overwrites the contents, so clearing should only be required at startup\&.
.PP
\fBParameters:\fP
.RS 4
\fIlcdPort\fP the LCD to clear, either uart1 or uart2 
.RE
.PP

.PP
Referenced by init_main_lcd(), lcd_clear(), and log_info()\&.
.SS "void lcdInit (\fBPROS_FILE\fP * lcdPort)"
Initializes the LCD port, but does not change the text or settings\&.
.PP
If the LCD was not initialized before, the text currently on the screen will be undefined\&. The port will not be usable with standard serial port functions until the LCD is stopped\&.
.PP
\fBParameters:\fP
.RS 4
\fIlcdPort\fP the LCD to initialize, either uart1 or uart2 
.RE
.PP

.PP
Referenced by init_error(), and init_main_lcd()\&.
.SS "void unsigned char const char unsigned int lcdReadButtons (\fBPROS_FILE\fP * lcdPort)"
Reads the user button status from the LCD display\&.
.PP
For example, if the left and right buttons are pushed, (1 | 4) = 5 will be returned\&. 0 is returned if no buttons are pushed\&.
.PP
\fBParameters:\fP
.RS 4
\fIlcdPort\fP the LCD to poll, either uart1 or uart2 
.RE
.PP
\fBReturns:\fP
.RS 4
the buttons pressed as a bit mask 
.RE
.PP

.PP
Referenced by buttonGetState(), and lcd_get_pressed_buttons()\&.
.SS "void lcdSetBacklight (\fBPROS_FILE\fP * lcdPort, bool backlight)"
Sets the specified LCD backlight to be on or off\&.
.PP
Turning it off will save power but may make it more difficult to read in dim conditions\&.
.PP
\fBParameters:\fP
.RS 4
\fIlcdPort\fP the LCD to adjust, either uart1 or uart2 
.br
\fIbacklight\fP true to turn the backlight on, or false to turn it off 
.RE
.PP

.PP
Referenced by lcd_set_backlight(), and log_info()\&.
.SS "void lcdSetText (\fBPROS_FILE\fP * lcdPort, unsigned char line, const char * buffer)"
Prints the string buffer to the attached LCD\&.
.PP
The output string will be truncated as necessary to fit on the LCD screen, 16 characters wide\&. This function, like \fBfprint()\fP, is much, much faster than a formatted routine such as lcdPrint() and consumes less memory\&.
.PP
\fBParameters:\fP
.RS 4
\fIlcdPort\fP the LCD to write, either uart1 or uart2 
.br
\fIline\fP the LCD line to write, either 1 or 2 
.br
\fIbuffer\fP the string to write 
.RE
.PP

.PP
Referenced by lcd_print()\&.
.SS "void lcdShutdown (\fBPROS_FILE\fP * lcdPort)"
Shut down the specified LCD port\&.
.PP
\fBParameters:\fP
.RS 4
\fIlcdPort\fP the LCD to stop, either uart1 or uart2 
.RE
.PP

.SS "unsigned long micros ()"
Returns the number of microseconds since Cortex power-up\&. There are 10^6 microseconds in a second, so as a 32-bit integer, this will overflow and wrap back to zero every two hours or so\&.
.PP
This function is Wiring-compatible\&.
.PP
\fBReturns:\fP
.RS 4
the number of microseconds since the Cortex was turned on or the last overflow 
.RE
.PP

.SS "unsigned long millis ()"
Returns the number of milliseconds since Cortex power-up\&. There are 1000 milliseconds in a second, so as a 32-bit integer, this will not overflow for 50 days\&.
.PP
This function is Wiring-compatible\&.
.PP
\fBReturns:\fP
.RS 4
the number of milliseconds since the Cortex was turned on 
.RE
.PP

.PP
Referenced by calculate_accelerometer_odemetry(), init_localization(), and update_position()\&.
.SS "int motorGet (unsigned char channel)"
Gets the last set speed of the specified motor channel\&.
.PP
This speed may have been set by any task or the PROS kernel itself\&. This is not guaranteed to be the speed that the motor is actually running at, or even the speed currently being sent to the motor, due to latency in the Motor Controller 29 protocol and physical loading\&. To measure actual motor shaft revolution speed, attach a VEX Integrated Motor Encoder or VEX Quadrature Encoder and use the velocity functions associated with each\&.
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP the motor channel to fetch from 1-10 
.RE
.PP
\fBReturns:\fP
.RS 4
the speed last sent to this channel; -127 is full reverse and 127 is full forward, with 0 being off 
.RE
.PP

.SS "void motorSet (unsigned char channel, int speed)"
Sets the speed of the specified motor channel\&.
.PP
Do not use \fBmotorSet()\fP with the same channel argument from two different tasks\&. It is safe to use \fBmotorSet()\fP with different channel arguments from different tasks\&.
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP the motor channel to modify from 1-10 
.br
\fIspeed\fP the new signed speed; -127 is full reverse and 127 is full forward, with 0 being off 
.RE
.PP

.PP
Referenced by set_motor_immediate(), and updateMotors()\&.
.SS "void motorStop (unsigned char channel)"
Stops the motor on the specified channel, equivalent to calling \fBmotorSet()\fP with an argument of zero\&.
.PP
This performs a coasting stop, not an active brake\&. Since motorStop is similar to motorSet(0), see the note for \fBmotorSet()\fP about use from multiple tasks\&.
.PP
\fBParameters:\fP
.RS 4
\fIchannel\fP the motor channel to stop from 1-10 
.RE
.PP

.SS "void motorStopAll ()"
Stops all motors; significantly faster than looping through all motor ports and calling motorSet(channel, 0) on each one\&. 
.PP
Referenced by init_slew()\&.
.SS "\fBMutex\fP mutexCreate ()"
Creates a mutex intended to allow only one task to use a resource at a time\&. For signalling and synchronization, try using semaphores\&.
.PP
Mutexes created using this function can be accessed using the \fBmutexTake()\fP and \fBmutexGive()\fP functions\&. The semaphore functions must not be used on objects of this type\&.
.PP
This type of object uses a priority inheritance mechanism so a task 'taking' a mutex MUST ALWAYS 'give' the mutex back once the mutex is no longer required\&.
.PP
\fBReturns:\fP
.RS 4
a handle to the created mutex 
.RE
.PP

.PP
Referenced by init_slew()\&.
.SS "void mutexDelete (\fBMutex\fP mutex)"
Deletes the specified mutex\&. This function can be dangerous; deleting semaphores being waited on by a task may cause deadlock or a crash\&.
.PP
\fBParameters:\fP
.RS 4
\fImutex\fP the mutex to destroy 
.RE
.PP

.SS "bool mutexGive (\fBMutex\fP mutex)"
Relinquishes a mutex so that other tasks can use the resource it guards\&. The mutex must be held by the current task using a corresponding call to mutexTake\&.
.PP
\fBParameters:\fP
.RS 4
\fImutex\fP the mutex to release 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the mutex was released, or false if the mutex was not already held 
.RE
.PP

.PP
Referenced by set_motor_immediate(), set_motor_slew(), and updateMotors()\&.
.SS "bool mutexTake (\fBMutex\fP mutex, const unsigned long blockTime)"
Requests a mutex so that other tasks cannot simultaneously use the resource it guards\&. The mutex must not already be held by the current task\&. If another task already holds the mutex, the function will wait for the mutex to be released\&. Other tasks can run during this time\&.
.PP
\fBParameters:\fP
.RS 4
\fImutex\fP the mutex to request 
.br
\fIblockTime\fP the maximum time to wait for the mutex to be available, where -1 specifies an infinite timeout 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the mutex was successfully taken, or false if the timeout expired 
.RE
.PP

.PP
Referenced by set_motor_immediate(), set_motor_slew(), and updateMotors()\&.
.SS "void pinMode (unsigned char pin, unsigned char mode)"
Configures the pin as an input or output with a variety of settings\&.
.PP
Do note that INPUT by default turns on the pull-up resistor, as most VEX sensors are open-drain active low\&. It should not be a big deal for most push-pull sources\&. This function is Wiring-compatible\&.
.PP
\fBParameters:\fP
.RS 4
\fIpin\fP the pin to modify from 1-26 
.br
\fImode\fP one of INPUT, INPUT_ANALOG, INPUT_FLOATING, OUTPUT, or OUTPUT_OD 
.RE
.PP

.SS "unsigned int powerLevelBackup ()"
Returns the backup battery voltage in millivolts\&.
.PP
If no backup battery is connected, returns 0\&. 
.PP
Referenced by backup_battery_voltage()\&.
.SS "unsigned int powerLevelMain ()"
Returns the main battery voltage in millivolts\&.
.PP
In rare circumstances, this method might return 0\&. Check the output value for reasonability before blindly blasting the user\&. 
.PP
Referenced by main_battery_voltage()\&.
.SS "void print (const char * string)"
Prints the simple string to the debug terminal without formatting\&.
.PP
This method is much, much faster than \fBprintf()\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP the string to write 
.RE
.PP

.SS "int printf (const char * formatString,  \&.\&.\&.)"
Prints the formatted string to the debug stream (the PC terminal)\&.
.PP
\fBParameters:\fP
.RS 4
\fIformatString\fP the format string as specified in \fBfprintf()\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of characters written 
.RE
.PP

.PP
Referenced by autonomous(), calculate_accelerometer_odemetry(), debug(), info(), initialize(), lcd_assert(), log_info(), and printMatrix()\&.
.SS "int putchar (int value)"
Writes one character to 'stdout', which is the PC debug terminal, and returns the input value\&.
.PP
When using a wireless connection, one may need to press the spacebar before the input is visible on the terminal\&.
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP the character to write (a value of type 'char' can be used) 
.RE
.PP
\fBReturns:\fP
.RS 4
the character written 
.RE
.PP

.SS "int puts (const char * string)"
Behaves the same as the 'print' function, and appends a trailing newline ('\\n')\&.
.PP
\fBParameters:\fP
.RS 4
\fIstring\fP the string to write 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of characters written, excluding the new line 
.RE
.PP

.SS "\fBSemaphore\fP semaphoreCreate ()"
Creates a semaphore intended for synchronizing tasks\&. To prevent some critical code from simultaneously modifying a shared resource, use mutexes instead\&.
.PP
Semaphores created using this function can be accessed using the \fBsemaphoreTake()\fP and \fBsemaphoreGive()\fP functions\&. The mutex functions must not be used on objects of this type\&.
.PP
This type of object does not need to have balanced take and give calls, so priority inheritance is not used\&. Semaphores can be signalled by an interrupt routine\&.
.PP
\fBReturns:\fP
.RS 4
a handle to the created semaphore 
.RE
.PP

.SS "void semaphoreDelete (\fBSemaphore\fP semaphore)"
Deletes the specified semaphore\&. This function can be dangerous; deleting semaphores being waited on by a task may cause deadlock or a crash\&.
.PP
\fBParameters:\fP
.RS 4
\fIsemaphore\fP the semaphore to destroy 
.RE
.PP

.SS "bool semaphoreGive (\fBSemaphore\fP semaphore)"
Signals a semaphore\&. Tasks waiting for a signal using \fBsemaphoreTake()\fP will be unblocked by this call and can continue execution\&.
.PP
Slow processes can give semaphores when ready, and fast processes waiting to take the semaphore will continue at that point\&.
.PP
\fBParameters:\fP
.RS 4
\fIsemaphore\fP the semaphore to signal 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the semaphore was successfully given, or false if the semaphore was not taken since the last give 
.RE
.PP

.SS "bool semaphoreTake (\fBSemaphore\fP semaphore, const unsigned long blockTime)"
Waits on a semaphore\&. If the semaphore is already in the 'taken' state, the current task will wait for the semaphore to be signaled\&. Other tasks can run during this time\&.
.PP
\fBParameters:\fP
.RS 4
\fIsemaphore\fP the semaphore to wait 
.br
\fIblockTime\fP the maximum time to wait for the semaphore to be given, where -1 specifies an infinite timeout 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the semaphore was successfully taken, or false if the timeout expired 
.RE
.PP

.SS "void setTeamName (const char * name)"
Sets the team name displayed to the VEX field control and VEX Firmware Upgrade\&.
.PP
\fBParameters:\fP
.RS 4
\fIname\fP a string containing the team name; only the first eight characters will be shown 
.RE
.PP

.PP
Referenced by initialize()\&.
.SS "int snprintf (char * buffer, size_t limit, const char * formatString,  \&.\&.\&.)"
Prints the formatted string to the string buffer with the specified length limit\&.
.PP
The length limit, as per the C standard, includes the trailing null character, so an argument of 256 will cause a maximum of 255 non-null characters to be printed, and one null terminator in all cases\&.
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP the string buffer where characters can be placed 
.br
\fIlimit\fP the maximum number of characters to write 
.br
\fIformatString\fP the format string as specified in \fBfprintf()\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of characters stored 
.RE
.PP

.SS "void speakerInit ()"
Initializes VEX speaker support\&.
.PP
The VEX speaker is not thread safe; it can only be used from one task at a time\&. Using the VEX speaker may impact robot performance\&. Teams may benefit from an if statement that only enables sound if \fBisOnline()\fP returns false\&. 
.SS "void speakerPlayArray (const char ** songs)"
Plays up to three RTTTL (Ring Tone Text Transfer Language) songs simultaneously over the VEX speaker\&. The audio is mixed to allow polyphonic sound to be played\&. Many simple songs are available in RTTTL format online, or compose your own\&.
.PP
The song must not be NULL, but unused tracks within the song can be set to NULL\&. If any of the three song tracks is invalid, the result of this function is undefined\&.
.PP
The VEX speaker is not thread safe; it can only be used from one task at a time\&. Using the VEX speaker may impact robot performance\&. Teams may benefit from an if statement that only enables sound if \fBisOnline()\fP returns false\&.
.PP
\fBParameters:\fP
.RS 4
\fIsongs\fP an array of up to three (3) RTTTL songs as string values to play 
.RE
.PP

.SS "void speakerPlayRtttl (const char * song)"
Plays an RTTTL (Ring Tone Text Transfer Language) song over the VEX speaker\&. Many simple songs are available in RTTTL format online, or compose your own\&.
.PP
The song must not be NULL\&. If an invalid song is specified, the result of this function is undefined\&.
.PP
The VEX speaker is not thread safe; it can only be used from one task at a time\&. Using the VEX speaker may impact robot performance\&. Teams may benefit from an if statement that only enables sound if \fBisOnline()\fP returns false\&.
.PP
\fBParameters:\fP
.RS 4
\fIsong\fP the RTTTL song as a string value to play 
.RE
.PP

.SS "void speakerShutdown ()"
Powers down and disables the VEX speaker\&.
.PP
If a song is currently being played in another task, the behavior of this function is undefined, since the VEX speaker is not thread safe\&. 
.SS "int sprintf (char * buffer, const char * formatString,  \&.\&.\&.)"
Prints the formatted string to the string buffer\&.
.PP
If the buffer is not big enough to contain the complete formatted output, undefined behavior occurs\&. See \fBsnprintf()\fP for a safer version of this function\&.
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP the string buffer where characters can be placed 
.br
\fIformatString\fP the format string as specified in \fBfprintf()\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
the number of characters stored 
.RE
.PP

.SS "void standaloneModeEnable ()"
Enables the Cortex to run the op control task in a standalone mode- no VEXnet connection required\&.
.PP
This function should only be called once in \fBinitializeIO()\fP 
.SS "\fBTaskHandle\fP taskCreate (\fBTaskCode\fP taskCode, const unsigned int stackDepth, void * parameters, const unsigned int priority)"
Creates a new task and add it to the list of tasks that are ready to run\&.
.PP
\fBParameters:\fP
.RS 4
\fItaskCode\fP the function to execute in its own task 
.br
\fIstackDepth\fP the number of variables available on the stack (4 * stackDepth bytes will be allocated on the Cortex) 
.br
\fIparameters\fP an argument passed to the taskCode function 
.br
\fIpriority\fP a value from TASK_PRIORITY_LOWEST to TASK_PRIORITY_HIGHEST determining the initial priority of the task 
.RE
.PP
\fBReturns:\fP
.RS 4
a handle to the created task, or NULL if an error occurred 
.RE
.PP

.SS "void taskDelay (const unsigned long msToDelay)"
Delays the current task for a given number of milliseconds\&.
.PP
Delaying for a period of zero will force a reschedule, where tasks of equal priority may be scheduled if available\&. The calling task will still be available for immediate rescheduling once the other tasks have had their turn or if nothing of equal or higher priority is available to be scheduled\&.
.PP
This is not the best method to have a task execute code at predefined intervals, as the delay time is measured from when the delay is requested\&. To delay cyclically, use \fBtaskDelayUntil()\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fImsToDelay\fP the number of milliseconds to wait, with 1000 milliseconds per second 
.RE
.PP

.SS "void taskDelayUntil (unsigned long * previousWakeTime, const unsigned long cycleTime)"
Delays the current task until a specified time\&. The task will be unblocked at the time *previousWakeTime + cycleTime, and *previousWakeTime will be changed to reflect the time at which the task will unblock\&.
.PP
If the target time is in the past, no delay occurs, but a reschedule is forced, as if \fBtaskDelay()\fP was called with an argument of zero\&. If the sum of cycleTime and *previousWakeTime overflows or underflows, undefined behavior occurs\&.
.PP
This function should be used by cyclical tasks to ensure a constant execution frequency\&. While \fBtaskDelay()\fP specifies a wake time relative to the time at which the function is called, \fBtaskDelayUntil()\fP specifies the absolute future time at which it wishes to unblock\&. Calling taskDelayUntil with the same cycleTime parameter value in a loop, with previousWakeTime referring to a local variable initialized to \fBmillis()\fP, will cause the loop to execute with a fixed period\&.
.PP
\fBParameters:\fP
.RS 4
\fIpreviousWakeTime\fP a pointer to the location storing the last unblock time, obtained by using the '&' operator on a variable (e\&.g\&. 'taskDelayUntil(&now, 50);') 
.br
\fIcycleTime\fP the number of milliseconds to wait, with 1000 milliseconds per second 
.RE
.PP

.SS "void taskDelete (\fBTaskHandle\fP taskToDelete)"
Kills and removes the specified task from the kernel task list\&.
.PP
Deleting the last task will end the program, possibly leading to undesirable states as some outputs may remain in their last set configuration\&.
.PP
NOTE: The idle task is responsible for freeing the kernel allocated memory from tasks that have been deleted\&. It is therefore important that the idle task is not starved of processing time\&. Memory allocated by the task code is not automatically freed, and should be freed before the task is deleted\&.
.PP
\fBParameters:\fP
.RS 4
\fItaskToDelete\fP the task to kill; passing NULL kills the current task 
.RE
.PP

.PP
Referenced by deinitslew()\&.
.SS "unsigned int taskGetCount ()"
Determines the number of tasks that are currently being managed\&.
.PP
This includes all ready, blocked and suspended tasks\&. A task that has been deleted but not yet freed by the idle task will also be included in the count\&. Tasks recently created may take one context switch to be counted\&.
.PP
\fBReturns:\fP
.RS 4
the number of tasks that are currently running, waiting, or suspended 
.RE
.PP

.SS "unsigned int taskGetState (\fBTaskHandle\fP task)"
Retrieves the state of the specified task\&. Note that the state of tasks which have died may be re-used for future tasks, causing the value returned by this function to reflect a different task than possibly intended in this case\&.
.PP
\fBParameters:\fP
.RS 4
\fItask\fP Handle to the task to query\&. Passing NULL will query the current task status (which will, by definition, be TASK_RUNNING if this call returns)
.RE
.PP
\fBReturns:\fP
.RS 4
A value reflecting the task's status, one of the constants TASK_DEAD, TASK_RUNNING, TASK_RUNNABLE, TASK_SLEEPING, or TASK_SUSPENDED 
.RE
.PP

.SS "unsigned int taskPriorityGet (const \fBTaskHandle\fP task)"
Obtains the priority of the specified task\&.
.PP
\fBParameters:\fP
.RS 4
\fItask\fP the task to check; passing NULL checks the current task 
.RE
.PP
\fBReturns:\fP
.RS 4
the priority of that task from 0 to TASK_MAX_PRIORITIES 
.RE
.PP

.SS "void taskPrioritySet (\fBTaskHandle\fP task, const unsigned int newPriority)"
Sets the priority of the specified task\&.
.PP
A context switch may occur before the function returns if the priority being set is higher than the currently executing task and the task being mutated is available to be scheduled\&.
.PP
\fBParameters:\fP
.RS 4
\fItask\fP the task to change; passing NULL changes the current task 
.br
\fInewPriority\fP a value between TASK_PRIORITY_LOWEST and TASK_PRIORITY_HIGHEST inclusive indicating the new task priority 
.RE
.PP

.SS "void taskResume (\fBTaskHandle\fP taskToResume)"
Resumes the specified task\&.
.PP
A task that has been suspended by one or more calls to \fBtaskSuspend()\fP will be made available for scheduling again by a call to \fBtaskResume()\fP\&. If the task was not suspended at the time of the call to \fBtaskResume()\fP, undefined behavior occurs\&.
.PP
\fBParameters:\fP
.RS 4
\fItaskToResume\fP the task to change; passing NULL is not allowed as the current task cannot be suspended (it is obviously running if this function is called) 
.RE
.PP

.SS "\fBTaskHandle\fP taskRunLoop (void(*)(void) fn, const unsigned long increment)"
Starts a task which will periodically call the specified function\&.
.PP
Intended for use as a quick-start skeleton for cyclic tasks with higher priority than the 'main' tasks\&. The created task will have priority TASK_PRIORITY_DEFAULT + 1 with the default stack size\&. To customize behavior, create a task manually with the specified function\&.
.PP
This task will automatically terminate after one further function invocation when the robot is disabled or when the robot mode is switched\&.
.PP
\fBParameters:\fP
.RS 4
\fIfn\fP the function to call in this loop 
.br
\fIincrement\fP the delay between successive calls in milliseconds; the \fBtaskDelayUntil()\fP function is used for accurate cycle timing 
.RE
.PP
\fBReturns:\fP
.RS 4
a handle to the task, or NULL if an error occurred 
.RE
.PP

.PP
Referenced by init_localization(), and init_slew()\&.
.SS "void taskSuspend (\fBTaskHandle\fP taskToSuspend)"
Suspends the specified task\&.
.PP
When suspended a task will not be scheduled, regardless of whether it might be otherwise available to run\&.
.PP
\fBParameters:\fP
.RS 4
\fItaskToSuspend\fP the task to suspend; passing NULL suspends the current task 
.RE
.PP

.SS "int ultrasonicGet (\fBUltrasonic\fP ult)"
Gets the current ultrasonic sensor value in centimeters\&.
.PP
If no object was found or if the ultrasonic sensor is polled while it is pinging and waiting for a response, -1 (ULTRA_BAD_RESPONSE) is returned\&. If the ultrasonic sensor was never started, the return value is undefined\&. Round and fluffy objects can cause inaccurate values to be returned\&.
.PP
\fBParameters:\fP
.RS 4
\fIult\fP the Ultrasonic object from \fBultrasonicInit()\fP to read 
.RE
.PP
\fBReturns:\fP
.RS 4
the distance to the nearest object in centimeters 
.RE
.PP

.SS "\fBUltrasonic\fP ultrasonicInit (unsigned char portEcho, unsigned char portPing)"
Initializes an ultrasonic sensor on the specified digital ports\&.
.PP
The ultrasonic sensor will be polled in the background in concert with the other sensors registered using this method\&. NULL will be returned if either port is invalid or the ultrasonic sensor port is already in use\&.
.PP
\fBParameters:\fP
.RS 4
\fIportEcho\fP the port connected to the orange cable from 1-9,11-12 
.br
\fIportPing\fP the port connected to the yellow cable from 1-12 
.RE
.PP
\fBReturns:\fP
.RS 4
an Ultrasonic object to be stored and used for later calls to ultrasonic functions 
.RE
.PP

.SS "void ultrasonicShutdown (\fBUltrasonic\fP ult)"
Stops and disables the ultrasonic sensor\&.
.PP
The last distance it had before stopping will be retained\&. One more ping operation may occur before the sensor is fully disabled\&.
.PP
\fBParameters:\fP
.RS 4
\fIult\fP the Ultrasonic object from \fBultrasonicInit()\fP to stop 
.RE
.PP

.SS "void usartInit (\fBPROS_FILE\fP * usart, unsigned int baud, unsigned int flags)"
Initialize the specified serial interface with the given connection parameters\&.
.PP
I/O to the port is accomplished using the 'standard' I/O functions such as \fBfputs()\fP, \fBfprintf()\fP, and \fBfputc()\fP\&.
.PP
Re-initializing an open port may cause loss of data in the buffers\&. This routine may be safely called from \fBinitializeIO()\fP or when the scheduler is paused\&. If I/O is attempted on a serial port which has never been opened, the behavior will be the same as if the port had been disabled\&.
.PP
\fBParameters:\fP
.RS 4
\fIusart\fP the port to open, either 'uart1' or 'uart2' 
.br
\fIbaud\fP the baud rate to use from 2400 to 1000000 baud 
.br
\fIflags\fP a bit mask combination of the SERIAL_* flags specifying parity, stop, and data bits 
.RE
.PP

.SS "void usartShutdown (\fBPROS_FILE\fP * usart)"
Disables the specified USART interface\&.
.PP
Any data in the transmit and receive buffers will be lost\&. Attempts to read from the port when it is disabled will deadlock, and attempts to write to it may deadlock depending on the state of the buffer\&.
.PP
\fBParameters:\fP
.RS 4
\fIusart\fP the port to close, either 'uart1' or 'uart2' 
.RE
.PP

.SS "void wait (const unsigned long time)"
Alias of \fBtaskDelay()\fP intended to help EasyC users\&.
.PP
\fBParameters:\fP
.RS 4
\fItime\fP the duration of the delay in milliseconds (1 000 milliseconds per second) 
.RE
.PP

.SS "void waitUntil (unsigned long * previousWakeTime, const unsigned long time)"
Alias of \fBtaskDelayUntil()\fP intended to help EasyC users\&.
.PP
\fBParameters:\fP
.RS 4
\fIpreviousWakeTime\fP a pointer to the last wakeup time 
.br
\fItime\fP the duration of the delay in milliseconds (1 000 milliseconds per second) 
.RE
.PP

.SS "void watchdogInit ()"
Enables IWDG watchdog timer which will reset the cortex if it locks up due to static shock or a misbehaving task preventing the timer to be reset\&. Not recovering from static shock will cause the robot to continue moving its motors indefinitely until turned off manually\&.
.PP
This function should only be called once in \fBinitializeIO()\fP 
.PP
Referenced by initializeIO()\&.
.SH "Variable Documentation"
.PP 
.SS "void unsigned char const char* formatString"

.PP
Definition at line 1182 of file API\&.h\&.
.SS "void unsigned char line"

.PP
Definition at line 1182 of file API\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
