.TH "include/auto.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/auto.h \- Autonomous declarations and macros\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'drive\&.h'\fP
.br
\fC#include 'sensor_ports\&.h'\fP
.br
\fC#include 'lifter\&.h'\fP
.br
\fC#include 'claw\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFRONT_LEFT_IME\fP   0"
.br
.RI "Front left motor integrated motor encoder\&. "
.ti -1c
.RI "#define \fBGOAL_HEIGHT\fP   1325"
.br
.RI "The height of the goal using potentiometer readings\&. "
.ti -1c
.RI "#define \fBMID_LEFT_DRIVE\fP   1"
.br
.RI "Middle left motor integrated motor encoder\&. "
.ti -1c
.RI "#define \fBMID_RIGHT_DRIVE\fP   4"
.br
.RI "Middle right motor integrated motor encoder\&. "
.ti -1c
.RI "#define \fBSTOP_ONE\fP   500"
.br
.RI "First Stop position for stationary autonomous\&. "
.in -1c
.SH "Detailed Description"
.PP 
Autonomous declarations and macros\&. 


.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/18/2017 
.RE
.PP

.PP
Definition in file \fBauto\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define FRONT_LEFT_IME   0"

.PP
Front left motor integrated motor encoder\&. 
.PP
Definition at line 18 of file auto\&.h\&.
.SS "#define GOAL_HEIGHT   1325"

.PP
The height of the goal using potentiometer readings\&. 
.PP
Definition at line 38 of file auto\&.h\&.
.PP
Referenced by autonomous()\&.
.SS "#define MID_LEFT_DRIVE   1"

.PP
Middle left motor integrated motor encoder\&. 
.PP
Definition at line 23 of file auto\&.h\&.
.PP
Referenced by autonomous()\&.
.SS "#define MID_RIGHT_DRIVE   4"

.PP
Middle right motor integrated motor encoder\&. 
.PP
Definition at line 28 of file auto\&.h\&.
.PP
Referenced by autonomous()\&.
.SS "#define STOP_ONE   500"

.PP
First Stop position for stationary autonomous\&. 
.PP
Definition at line 33 of file auto\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
