.TH "include/claw.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/claw.h \- Code for controlling the claw that grabs the cones\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'slew\&.h'\fP
.br
\fC#include <API\&.h>\fP
.br
\fC#include 'controller\&.h'\fP
.br
\fC#include 'motor_ports\&.h'\fP
.br
\fC#include 'sensor_ports\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLAW_CLOSE\fP   \fBMASTER\fP, 6, \fBJOY_UP\fP"
.br
.RI "The joystick parameters for closing the claw\&. "
.ti -1c
.RI "#define \fBCLAW_CLOSE_VAL\fP   3000"
.br
.RI "The potentiometer value for a closed claw\&. "
.ti -1c
.RI "#define \fBCLAW_D\fP   \&.1"
.br
.RI "The derivative constant for the claw PID controller\&. "
.ti -1c
.RI "#define \fBCLAW_I\fP   0"
.br
.RI "The integral constant for the claw PID controller\&. "
.ti -1c
.RI "#define \fBCLAW_OPEN\fP   \fBMASTER\fP, 6, \fBJOY_DOWN\fP"
.br
.RI "The joystick parameters for opening the claw\&. "
.ti -1c
.RI "#define \fBCLAW_OPEN_VAL\fP   1500"
.br
.RI "The potentiometer value for a open claw\&. "
.ti -1c
.RI "#define \fBCLAW_P\fP   \&.1"
.br
.RI "The proportional constant for the claw PID controller\&. "
.ti -1c
.RI "#define \fBMAX_CLAW_SPEED\fP   50"
.br
.RI "The max motor vlaue of the claw\&. "
.ti -1c
.RI "#define \fBMIN_CLAW_SPEED\fP   \-50"
.br
.RI "The min motor vlaue of the claw\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBclaw_state\fP { \fBCLAW_OPEN_STATE\fP, \fBCLAW_CLOSE_STATE\fP }
.RI "The different states of the claw\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBclose_claw\fP ()"
.br
.RI "Drives the motors to close the claw\&. "
.ti -1c
.RI "unsigned int \fBgetClawTicks\fP ()"
.br
.RI "Gets the claw position in potentiometer ticks\&. "
.ti -1c
.RI "void \fBopen_claw\fP ()"
.br
.RI "Drives the motors to open the claw\&. "
.ti -1c
.RI "void \fBset_claw_motor\fP (const int v)"
.br
.RI "sets the claw motor speed "
.ti -1c
.RI "void \fBupdate_claw\fP ()"
.br
.RI "Updates the claw motor values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Code for controlling the claw that grabs the cones\&. 


.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett, Christian Desimone 
.RE
.PP
\fBDate:\fP
.RS 4
8/30/2017 
.RE
.PP

.PP
Definition in file \fBclaw\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLAW_CLOSE   \fBMASTER\fP, 6, \fBJOY_UP\fP"

.PP
The joystick parameters for closing the claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 47 of file claw\&.h\&.
.PP
Referenced by update_claw()\&.
.SS "#define CLAW_CLOSE_VAL   3000"

.PP
The potentiometer value for a closed claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 59 of file claw\&.h\&.
.PP
Referenced by update_claw()\&.
.SS "#define CLAW_D   \&.1"

.PP
The derivative constant for the claw PID controller\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 25 of file claw\&.h\&.
.PP
Referenced by update_claw()\&.
.SS "#define CLAW_I   0"

.PP
The integral constant for the claw PID controller\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 30 of file claw\&.h\&.
.SS "#define CLAW_OPEN   \fBMASTER\fP, 6, \fBJOY_DOWN\fP"

.PP
The joystick parameters for opening the claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 53 of file claw\&.h\&.
.PP
Referenced by update_claw()\&.
.SS "#define CLAW_OPEN_VAL   1500"

.PP
The potentiometer value for a open claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 65 of file claw\&.h\&.
.PP
Referenced by update_claw()\&.
.SS "#define CLAW_P   \&.1"

.PP
The proportional constant for the claw PID controller\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 20 of file claw\&.h\&.
.PP
Referenced by update_claw()\&.
.SS "#define MAX_CLAW_SPEED   50"

.PP
The max motor vlaue of the claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 36 of file claw\&.h\&.
.PP
Referenced by open_claw()\&.
.SS "#define MIN_CLAW_SPEED   \-50"

.PP
The min motor vlaue of the claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 41 of file claw\&.h\&.
.PP
Referenced by close_claw()\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBclaw_state\fP"

.PP
The different states of the claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICLAW_OPEN_STATE \fP\fP
.TP
\fB\fICLAW_CLOSE_STATE \fP\fP
.PP
Definition at line 101 of file claw\&.h\&.
.PP
.nf
101                 {
102   CLAW_OPEN_STATE,
103   CLAW_CLOSE_STATE
104 };
.fi
.SH "Function Documentation"
.PP 
.SS "void close_claw ()"

.PP
Drives the motors to close the claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 67 of file claw\&.c\&.
.PP
References CLAW_MOTOR, MIN_CLAW_SPEED, and set_motor_immediate()\&.
.PP
Referenced by autonomous()\&.
.PP
.nf
67                   {
68   set_motor_immediate(CLAW_MOTOR, MIN_CLAW_SPEED);
69 }
.fi
.SS "unsigned int getClawTicks ()"

.PP
Gets the claw position in potentiometer ticks\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 51 of file claw\&.c\&.
.PP
References analogRead(), and CLAW_POT\&.
.PP
Referenced by update_claw()\&.
.PP
.nf
51                            {
52   return analogRead(CLAW_POT);
53 }
.fi
.SS "void open_claw ()"

.PP
Drives the motors to open the claw\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 59 of file claw\&.c\&.
.PP
References CLAW_MOTOR, MAX_CLAW_SPEED, and set_motor_immediate()\&.
.PP
Referenced by autonomous()\&.
.PP
.nf
59                  {
60   set_motor_immediate(CLAW_MOTOR, MAX_CLAW_SPEED);
61 }
.fi
.SS "void set_claw_motor (const int v)"

.PP
sets the claw motor speed 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 43 of file claw\&.c\&.
.PP
References CLAW_MOTOR, and set_motor_immediate()\&.
.PP
Referenced by update_claw()\&.
.PP
.nf
43                                 {
44   set_motor_immediate(CLAW_MOTOR, v);
45 }
.fi
.SS "void update_claw ()"

.PP
Updates the claw motor values\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 7 of file claw\&.c\&.
.PP
References CLAW_CLOSE, CLAW_CLOSE_STATE, CLAW_CLOSE_VAL, CLAW_D, CLAW_OPEN, CLAW_OPEN_STATE, CLAW_OPEN_VAL, CLAW_P, getClawTicks(), joystickGetDigital(), and set_claw_motor()\&.
.PP
Referenced by operatorControl()\&.
.PP
.nf
7                    {
8   //Set the Error used in calculating d
9   static int last_error = 0;
10   //Set the initial claw state to open
11   static enum claw_state state = CLAW_OPEN_STATE;
12   //Listen for input and either close or open the claw
13   if(joystickGetDigital(CLAW_CLOSE)){
14     state = CLAW_CLOSE_STATE;
15   }
16   else if(joystickGetDigital(CLAW_OPEN)){
17     state = CLAW_OPEN_STATE;
18   } else {
19     //set the default motor speed
20     int p = 0;
21     //Change the base speed to the difference between the target
22     // and the current value
23     if(state == CLAW_OPEN_STATE) {
24       p = getClawTicks() - CLAW_OPEN_VAL;
25     } else {
26       p = getClawTicks() - CLAW_CLOSE_VAL;
27     }
28     //Set the d value to the difference between the current p and the last p
29     int d = (p - last_error);
30     //Set last error for use the next time the function is run
31     last_error = p;
32     //Construct the final motor speed value
33     int motor = CLAW_P * p + CLAW_D * d;
34     //Set the motor speed
35     set_claw_motor(motor);
36   }
37 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
