.TH "src/controller.c" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/controller.c
.SH SYNOPSIS
.br
.PP
\fC#include 'controller\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBcord\fP \fBget_joystick_cord\fP (enum \fBjoystick\fP \fBside\fP, int controller)"
.br
.RI "Gets the location of a joystick on the controller\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBcord\fP get_joystick_cord (enum \fBjoystick\fP side, int controller)"

.PP
Gets the location of a joystick on the controller\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 7 of file controller\&.c\&.
.PP
References joystickGetAnalog(), LEFT_JOY_X, LEFT_JOY_Y, RIGHT_JOY, RIGHT_JOY_X, RIGHT_JOY_Y, cord::x, and cord::y\&.
.PP
.nf
7                                                                   {
8   int x;
9   int y;
10   //Get the joystick value for either the right or left,
11   //depending on the mode
12   if(side == RIGHT_JOY) {
13     y = joystickGetAnalog(controller, RIGHT_JOY_X);
14     x = joystickGetAnalog(controller, RIGHT_JOY_Y);
15   } else {
16     y = joystickGetAnalog(controller, LEFT_JOY_X);
17     x = joystickGetAnalog(controller, LEFT_JOY_Y);
18   }
19   //Define a coordinate for the joystick value
20   struct cord c;
21   c\&.x = x;
22   c\&.y = y;
23   return c;
24 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
