.TH "include/controller.h" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/controller.h \- controller definitions, macros  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMASTER\fP   1"
.br
.RI "the master controller "
.ti -1c
.RI "#define \fBPARTNER\fP   2"
.br
.RI "the slave/partner controller "
.ti -1c
.RI "#define \fBRIGHT_JOY_X\fP   1"
.br
.RI "the right x joystick on controller "
.ti -1c
.RI "#define \fBRIGHT_JOY_Y\fP   2"
.br
.RI "the right y joystick on controller "
.in -1c
.SH "Detailed Description"
.PP 
controller definitions, macros 


.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP

.PP
Definition in file \fBcontroller\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define MASTER   1"

.PP
the master controller 
.PP
\fBDate:\fP
.RS 4
9/1/2017 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 15 of file controller\&.h\&.
.SS "#define PARTNER   2"

.PP
the slave/partner controller 
.PP
\fBDate:\fP
.RS 4
9/1/2017 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 22 of file controller\&.h\&.
.SS "#define RIGHT_JOY_X   1"

.PP
the right x joystick on controller 
.PP
\fBDate:\fP
.RS 4
9/1/2017 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 29 of file controller\&.h\&.
.SS "#define RIGHT_JOY_Y   2"

.PP
the right y joystick on controller 
.PP
\fBDate:\fP
.RS 4
9/1/2017 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 36 of file controller\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team A from the source code\&.
