.TH "cord" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cord \- A struct that contains cartesian coordinates\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'vmath\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct that contains cartesian coordinates\&. 


.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 32 of file vmath\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float cord::x"
the x coordinate 
.PP
Definition at line 34 of file vmath\&.h\&.
.PP
Referenced by get_joystick_cord(), and update_drive_motors()\&.
.SS "float cord::y"
the y coordinate 
.PP
Definition at line 36 of file vmath\&.h\&.
.PP
Referenced by get_joystick_cord(), and update_drive_motors()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
