.TH "src/drive.c" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/drive.c
.SH SYNOPSIS
.br
.PP
\fC#include 'drive\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <API\&.h>\fP
.br
\fC#include 'controller\&.h'\fP
.br
\fC#include 'vmath\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBset_side_speed\fP (\fBside\fP \fBside\fP, int speed)"
.br
.ti -1c
.RI "void \fBupdateDriveMotors\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void set_side_speed (\fBside\fP side, int speed)"
sets the speed of one side of the robot\&. 
.PP
\fBAuthor:\fP
.RS 4
Christian Desimone 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIside\fP a side enum which indicates the size\&. 
.br
\fIspeed\fP the speed of the side\&. Can range from -127 - 127 negative being back and positive forwards 
.RE
.PP

.PP
Definition at line 13 of file drive\&.c\&.
.SS "void updateDriveMotors ()"
Updates the drive motosrs during teleop 
.PP
\fBAuthor:\fP
.RS 4
Christian Desimone 
.RE
.PP
\fBDate:\fP
.RS 4
9/5/17 
.RE
.PP

.PP
Definition at line 31 of file drive\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team A from the source code\&.
