.TH "include/encoders.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/encoders.h \- wrapper around encoder functions  

.SH SYNOPSIS
.br
.PP
\fC#include <API\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIME_NUMBER\fP   6"
.br
.RI "The number of IMEs\&. This number is compared against the number detect in init_encoders\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBget_encoder_ticks\fP (unsigned char address)"
.br
.RI "Gets the encoder ticks since last reset\&. "
.ti -1c
.RI "int \fBget_encoder_velocity\fP (unsigned char address)"
.br
.RI "Gets the encoder reads\&. "
.ti -1c
.RI "bool \fBinit_encoders\fP ()"
.br
.RI "Initializes all motor encoders\&. "
.in -1c
.SH "Detailed Description"
.PP 
wrapper around encoder functions 


.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett, Christian Desimone 
.RE
.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP

.PP
Definition in file \fBencoders\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define IME_NUMBER   6"

.PP
The number of IMEs\&. This number is compared against the number detect in init_encoders\&. 
.PP
\fBSee also:\fP
.RS 4
\fBinit_encoders()\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBIME_NUMBER\fP 
.RE
.PP

.PP
Definition at line 20 of file encoders\&.h\&.
.PP
Referenced by init_encoders()\&.
.SH "Function Documentation"
.PP 
.SS "int get_encoder_ticks (unsigned char address)"

.PP
Gets the encoder ticks since last reset\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/15/2017 
.RE
.PP

.PP
Definition at line 23 of file encoders\&.c\&.
.PP
References imeGet()\&.
.PP
.nf
23                                              {
24   int i = 0;
25   imeGet(address, &i);
26   return i;
27 }
.fi
.SS "int get_encoder_velocity (unsigned char address)"

.PP
Gets the encoder reads\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/15/2017 
.RE
.PP

.PP
Definition at line 34 of file encoders\&.c\&.
.PP
References imeGetVelocity()\&.
.PP
.nf
34                                                 {
35   int i = 0;
36   imeGetVelocity(address, &i);
37   return i;
38 }
.fi
.SS "bool init_encoders ()"

.PP
Initializes all motor encoders\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBIME_NUMBER\fP 
.RE
.PP

.PP
Definition at line 10 of file encoders\&.c\&.
.PP
References IME_NUMBER, and imeInitializeAll()\&.
.PP
.nf
10                      {
11   #ifdef IME_NUMBER
12   return imeInitializeAll() == IME_NUMBER;
13   #else
14   return imeInitializeAll();
15   #endif
16 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
