.TH "include/encoders.h" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/encoders.h
.SH SYNOPSIS
.br
.PP
\fC#include <API\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIME_NUMBER\fP   1"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBinit_encoders\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IME_NUMBER   1"

.PP
Definition at line 6 of file encoders\&.h\&.
.SH "Function Documentation"
.PP 
.SS "bool init_encoders ()"

.PP
Definition at line 8 of file encoders\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team A from the source code\&.
