.TH "encoder_odemtry" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
encoder_odemtry
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBtheta\fP"
.br
.ti -1c
.RI "double \fBx\fP"
.br
.ti -1c
.RI "double \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file localization\&.c\&.
.SH "Field Documentation"
.PP 
.SS "double encoder_odemtry::theta"

.PP
Definition at line 14 of file localization\&.c\&.
.PP
Referenced by integrate_gyro_w()\&.
.SS "double encoder_odemtry::x"

.PP
Definition at line 12 of file localization\&.c\&.
.SS "double encoder_odemtry::y"

.PP
Definition at line 13 of file localization\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
