.TH "src/init.c" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/init.c \- File for initialization code\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main\&.h'\fP
.br
\fC#include 'slew\&.h'\fP
.br
\fC#include 'lcd\&.h'\fP
.br
\fC#include 'log\&.h'\fP
.br
\fC#include 'encoders\&.h'\fP
.br
\fC#include 'menu\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBinitializeIO\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
File for initialization code\&. 

This file should contain the user \fBinitialize()\fP function and any functions related to it\&.
.PP
Any copyright is dedicated to the Public Domain\&. http://creativecommons.org/publicdomain/zero/1.0/
.PP
PROS contains FreeRTOS (http://www.freertos.org) whose source code may be obtained from http://sourceforge.net/projects/freertos/files/ or on request\&. 
.PP
Definition in file \fBinit\&.c\fP\&.
.SH "Function Documentation"
.PP 
.SS "void initialize ()"
Runs user initialization code\&. This function will be started in its own task with the default priority and stack size once when the robot is starting up\&. It is possible that the VEXnet communication link may not be fully established at this time, so reading from the VEX Joystick may fail\&.
.PP
This function should initialize most sensors (gyro, encoders, ultrasonics), LCDs, global variables, and IMEs\&.
.PP
This function must exit relatively promptly, or the \fBoperatorControl()\fP and \fBautonomous()\fP tasks will not start\&. An autonomous mode selection menu like the pre_auton() in other environments can be implemented in this task if desired\&. 
.PP
Definition at line 47 of file init\&.c\&.
.PP
References imeInitializeAll(), printf(), and setTeamName()\&.
.PP
.nf
47                   {
48   int c = imeInitializeAll();
49   setTeamName("9228A");
50   printf("Counts : %d\n", c);
51 }
.fi
.SS "void initializeIO ()"
Runs pre-initialization code\&. This function will be started in kernel mode one time while the VEX Cortex is starting up\&. As the scheduler is still paused, most API functions will fail\&.
.PP
The purpose of this function is solely to set the default pin modes (\fBpinMode()\fP) and port states (\fBdigitalWrite()\fP) of limit switches, push buttons, and solenoids\&. It can also safely configure a UART port (usartOpen()) but cannot set up an LCD (\fBlcdInit()\fP)\&. 
.PP
Definition at line 30 of file init\&.c\&.
.PP
References watchdogInit()\&.
.PP
.nf
30                     {
31     watchdogInit();
32 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
