.TH "lcd_buttons" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lcd_buttons \- represents the state of the lcd buttons  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'lcd\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbutton_state\fP \fBleft\fP"
.br
.ti -1c
.RI "\fBbutton_state\fP \fBmiddle\fP"
.br
.ti -1c
.RI "\fBbutton_state\fP \fBright\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
represents the state of the lcd buttons 


.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP

.PP
Definition at line 48 of file lcd\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBbutton_state\fP lcd_buttons::left"

.PP
Definition at line 49 of file lcd\&.h\&.
.PP
Referenced by lcd_get_pressed_buttons()\&.
.SS "\fBbutton_state\fP lcd_buttons::middle"

.PP
Definition at line 50 of file lcd\&.h\&.
.PP
Referenced by lcd_get_pressed_buttons()\&.
.SS "\fBbutton_state\fP lcd_buttons::right"

.PP
Definition at line 51 of file lcd\&.h\&.
.PP
Referenced by lcd_get_pressed_buttons()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
