.TH "lcd_buttons" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lcd_buttons \- repreents the state of the lcd buttons  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lcd\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbutton_state\fP \fBleft\fP"
.br
.ti -1c
.RI "\fBbutton_state\fP \fBmiddle\fP"
.br
.ti -1c
.RI "\fBbutton_state\fP \fBright\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
repreents the state of the lcd buttons 


.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP

.PP
Definition at line 51 of file lcd\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBbutton_state\fP left"

.PP
Definition at line 52 of file lcd\&.h\&.
.SS "\fBbutton_state\fP middle"

.PP
Definition at line 53 of file lcd\&.h\&.
.SS "\fBbutton_state\fP right"

.PP
Definition at line 54 of file lcd\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team A from the source code\&.
