.TH "location" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
location
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'localization\&.h'\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBtheta\fP"
.br
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Vector storing the cartesian cords and an angle 
.PP
Definition at line 23 of file localization\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int location::theta"

.PP
Definition at line 26 of file localization\&.h\&.
.SS "int location::x"

.PP
Definition at line 24 of file localization\&.h\&.
.SS "int location::y"

.PP
Definition at line 25 of file localization\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
