.TH "include/localization.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/localization.h \- Declarations and macros for determining the location of the robot\&. [WIP]\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <API\&.h>\fP
.br
\fC#include 'encoders\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'matrix\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBlocation\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBLOCALIZATION_UPDATE_FREQUENCY\fP   0\&.500"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBlocation\fP \fBget_position\fP ()"
.br
.RI "Gets the current posituion of the robot\&. "
.ti -1c
.RI "bool \fBinit_localization\fP (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)"
.br
.RI "Starts the localization process\&. "
.in -1c
.SH "Detailed Description"
.PP 
Declarations and macros for determining the location of the robot\&. [WIP]\&. 


.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett, Christian Desimone 
.RE
.PP
\fBDate:\fP
.RS 4
9/27/2017 
.RE
.PP

.PP
Definition in file \fBlocalization\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define LOCALIZATION_UPDATE_FREQUENCY   0\&.500"
How often the localization code updates the position\&. 
.PP
Definition at line 18 of file localization\&.h\&.
.PP
Referenced by calculate_gryo_anglular_velocity(), init_localization(), and integrate_gyro_w()\&.
.SH "Function Documentation"
.PP 
.SS "struct \fBlocation\fP get_position ()"

.PP
Gets the current posituion of the robot\&. 
.PP
\fBParameters:\fP
.RS 4
\fIgyro1\fP The first gyro 
.RE
.PP
\fBReturns:\fP
.RS 4
the loacation of the robot as a struct\&. 
.RE
.PP

.PP
Definition at line 25 of file localization\&.c\&.
.PP
.nf
25                                {
26 
27 }
.fi
.SS "bool init_localization (const unsigned char gyro1, unsigned short multiplier, int start_x, int start_y, int start_theta)"

.PP
Starts the localization process\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett
.RE
.PP
\fBParameters:\fP
.RS 4
\fIgyro1\fP The first gyro  The multiplier parameter can tune the gyro to adapt to specific sensors\&. The default value at this time is 196; higher values will increase the number of degrees reported for a fixed actual rotation, while lower values will decrease the number of degrees reported\&. If your robot is consistently turning too far, increase the multiplier, and if it is not turning far enough, decrease the multiplier\&. 
.RE
.PP

.PP
Definition at line 89 of file localization\&.c\&.
.PP
References g1, gyroInit(), last_call, localization_task, LOCALIZATION_UPDATE_FREQUENCY, makeMatrix(), millis(), taskRunLoop(), and update_position()\&.
.PP
.nf
89                                                                                                                          {
90   g1 = gyroInit(gyro1, multiplier);
91   //init state matrix
92 
93   //one dimensional vector with x, y, theta, acceleration in x and y
94   state_matrix = makeMatrix(1, 5);
95   localization_task = taskRunLoop(update_position, LOCALIZATION_UPDATE_FREQUENCY * 1000);
96   last_call = millis();
97   return true;
98 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
