.TH "include/menu.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/menu.h \- Contains menu functionality and abstraction\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lcd\&.h'\fP
.br
\fC#include 'API\&.h'\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <vlib\&.h>\fP
.br
\fC#include 'log\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBmenu_t\fP"
.br
.RI "Represents a specific instance of a menu\&. Will cause a memory leak if not deinitialized via denint_menu\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBmenu_t\fP \fBmenu_t\fP"
.br
.RI "Represents a specific instance of a menu\&. Will cause a memory leak if not deinitialized via denint_menu\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmenu_type\fP { \fBINT_TYPE\fP, \fBFLOAT_TYPE\fP, \fBSTRING_TYPE\fP }
.RI "Represents the different types of menus\&. ""
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBcalculate_current_display\fP (char *rtn, \fBmenu_t\fP *menu)"
.br
.RI "Static function that calculates the string from menu\&. "
.ti -1c
.RI "static \fBmenu_t\fP * \fBcreate_menu\fP (enum \fBmenu_type\fP type, const char *prompt)"
.br
.RI "Static function that handles creation of menu\&. \fI Menu must be freed or will cause memory leak \fI \fP\fP"
.ti -1c
.RI "void \fBdenint_menu\fP (\fBmenu_t\fP *menu)"
.br
.RI "Destroys a menu \fI Menu must be freed or will cause memory leak \fI \fP\fP"
.ti -1c
.RI "int \fBdisplay_menu\fP (\fBmenu_t\fP *menu)"
.br
.RI "Displays a menu context, but does not display\&. \fI Menu must be freed or will cause memory leak! \fI Will exit if robot is enabled\&. This prevents menu from locking up system in even of a reset\&. \fP\fP"
.ti -1c
.RI "\fBmenu_t\fP * \fBinit_menu_float\fP (enum \fBmenu_type\fP type, float \fBmin\fP, float \fBmax\fP, float step, const char *prompt)"
.br
.RI "Creates a menu context, but does not display\&. \fI Menu must be freed or will cause memory leak! \fI \fP\fP"
.ti -1c
.RI "\fBmenu_t\fP * \fBinit_menu_int\fP (enum \fBmenu_type\fP type, int \fBmin\fP, int \fBmax\fP, int step, const char *prompt)"
.br
.RI "Creates a menu context, but does not display\&. \fI Menu must be freed or will cause memory leak \fI \fP\fP"
.ti -1c
.RI "\fBmenu_t\fP * \fBinit_menu_var\fP (enum \fBmenu_type\fP type, unsigned int nums, const char *prompt, char *options,\&.\&.\&.)"
.br
.RI "Creates a menu context, but does not display\&. \fI Menu must be freed or will cause memory leak \fI \fP\fP"
.in -1c
.SH "Detailed Description"
.PP 
Contains menu functionality and abstraction\&. 


.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP

.PP
Definition in file \fBmenu\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBmenu_t\fP  \fBmenu_t\fP"

.PP
Represents a specific instance of a menu\&. Will cause a memory leak if not deinitialized via denint_menu\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBmenu\&.h\fP 
.PP
\fBmenu_t\fP 
.PP
\fBcreate_menu\fP 
.PP
init_menu 
.PP
\fBdisplay_menu\fP 
.PP
\fBmenu_type\fP 
.PP
\fBdenint_menu\fP 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmenu_type\fP"

.PP
Represents the different types of menus\&. 
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBmenu\&.h\fP 
.PP
\fBmenu_t\fP 
.PP
\fBcreate_menu\fP 
.PP
init_menu 
.PP
\fBdisplay_menu\fP 
.PP
\fBmenu_type\fP 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINT_TYPE \fP\fP
Menu type allowing user to select a integer\&. The integer type menu has a max, min and a step value\&. Each step is calculated\&. Will return the index of the selected value\&. Example: User goes forwards twice then it will return 2\&. 
.TP
\fB\fIFLOAT_TYPE \fP\fP
Menu type allowing user to select a float The float type menu has a max, min and a step value\&. Each step is calculated\&. Will return the index of the selected value\&. Example: User goes forwards twice then it will return 2\&. 
.TP
\fB\fISTRING_TYPE \fP\fP
Menu type allowing user to select a string from a array of strings\&. Will return the index of the selected value\&. Example: User goes forwards twice then it will return 2\&. 
.PP
Definition at line 30 of file menu\&.h\&.
.PP
.nf
30                {
37   INT_TYPE,
44   FLOAT_TYPE,
50   STRING_TYPE
51 };
.fi
.SH "Function Documentation"
.PP 
.SS "static void calculate_current_display (char * rtn, \fBmenu_t\fP * menu)\fC [static]\fP"

.PP
Static function that calculates the string from menu\&. 
.PP
\fBParameters:\fP
.RS 4
\fIrtn\fP the string to be written to 
.br
\fImenu\fP the menu for prompt to be calculated from 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP

.SS "static \fBmenu_t\fP* create_menu (enum \fBmenu_type\fP type, const char * prompt)\fC [static]\fP"

.PP
Static function that handles creation of menu\&. \fI Menu must be freed or will cause memory leak \fI \fP\fP
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP

.SS "void denint_menu (\fBmenu_t\fP * menu)"

.PP
Destroys a menu \fI Menu must be freed or will cause memory leak \fI \fP\fP
.PP
\fBParameters:\fP
.RS 4
\fImenu\fP the menu to free 
.RE
.PP
\fBSee also:\fP
.RS 4
menu 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP

.PP
Definition at line 101 of file menu\&.c\&.
.PP
References menu_t::options, and menu_t::prompt\&.
.PP
.nf
101                               {
102   free(menu->prompt);
103   if(menu->options != NULL) free(menu->options);
104   free(menu);
105 }
.fi
.SS "int display_menu (\fBmenu_t\fP * menu)"

.PP
Displays a menu context, but does not display\&. \fI Menu must be freed or will cause memory leak! \fI Will exit if robot is enabled\&. This prevents menu from locking up system in even of a reset\&. \fP\fP
.PP
\fBParameters:\fP
.RS 4
\fImenu\fP the menu to display 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBmenu_type\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP

.PP
Definition at line 83 of file menu\&.c\&.
.PP
References calculate_current_display(), menu_t::current, delay(), isEnabled(), lcd_get_pressed_buttons(), lcd_print(), PRESSED, menu_t::prompt, RELEASED, and TOP_ROW\&.
.PP
.nf
83                               {
84   lcd_print(TOP_ROW, menu->prompt);
85   //Will exit if teleop or autonomous begin\&. This is extremely important if robot disconnects or resets\&.
86   while(lcd_get_pressed_buttons()\&.middle == RELEASED && !isEnabled()) {
87     char val[16];
88     calculate_current_display(val, menu);
89 
90     if(lcd_get_pressed_buttons()\&.right == PRESSED) {
91       menu->current += 1;
92     }
93     if(lcd_get_pressed_buttons()\&.left == PRESSED) {
94       menu->current -= 1;
95     }
96     delay(500);
97   }
98   return menu->current;
99 }
.fi
.SS "\fBmenu_t\fP* init_menu_float (enum \fBmenu_type\fP type, float min, float max, float step, const char * prompt)"

.PP
Creates a menu context, but does not display\&. \fI Menu must be freed or will cause memory leak! \fI \fP\fP
.PP
\fBParameters:\fP
.RS 4
\fItype\fP the type of menu 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBmenu_type\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fImin\fP the minimum value 
.br
\fImax\fP the maximum value 
.br
\fIstep\fP the step value 
.br
\fIprompt\fP the prompt to display to user 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP

.PP
Definition at line 48 of file menu\&.c\&.
.PP
References create_menu(), max(), menu_t::max_f, min(), menu_t::min_f, and menu_t::step_f\&.
.PP
.nf
48                                                                                                   {
49   menu_t* menu = create_menu(type, prompt);
50   menu->min_f = min;
51   menu->max_f = max;
52   menu->step_f = step;
53   return menu;
54 }
.fi
.SS "\fBmenu_t\fP* init_menu_int (enum \fBmenu_type\fP type, int min, int max, int step, const char * prompt)"

.PP
Creates a menu context, but does not display\&. \fI Menu must be freed or will cause memory leak \fI \fP\fP
.PP
\fBParameters:\fP
.RS 4
\fItype\fP the type of menu 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBmenu_type\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fImin\fP the minimum value 
.br
\fImax\fP the maximum value 
.br
\fIstep\fP the step value 
.br
\fIprompt\fP the prompt to display to user 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP

.PP
Definition at line 40 of file menu\&.c\&.
.PP
References create_menu(), max(), menu_t::max, min(), menu_t::min, and menu_t::step\&.
.PP
.nf
40                                                                                           {
41   menu_t* menu = create_menu(type, prompt);
42   menu->min = min;
43   menu->max = max;
44   menu->step = step;
45   return menu;
46 }
.fi
.SS "\fBmenu_t\fP* init_menu_var (enum \fBmenu_type\fP type, unsigned int nums, const char * prompt, char * options,  \&.\&.\&.)"

.PP
Creates a menu context, but does not display\&. \fI Menu must be freed or will cause memory leak \fI \fP\fP
.PP
\fBParameters:\fP
.RS 4
\fItype\fP the type of menu 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBmenu_type\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fInums\fP the number of elements passed to function 
.br
\fIprompt\fP the prompt to display to user 
.br
\fIoptions\fP the options to display for user 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/17 
.RE
.PP

.PP
Definition at line 26 of file menu\&.c\&.
.PP
References create_menu(), menu_t::length, and menu_t::options\&.
.PP
.nf
26                                                                                                     {
27   menu_t* menu = create_menu(type, prompt);
28   va_list values;
29   char **options_array = (char**)calloc(sizeof(char*), nums);
30   va_start(values, options);
31   for(unsigned int i = 0; i < nums; i++){
32     options_array[i] = va_arg(values, char*);
33   }
34   va_end(values);
35   menu->options = options_array;
36   menu->length = nums;
37   return menu;
38 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
