.TH "menu" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
menu
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <menu\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "enum \fBmenu_type\fP \fBtype\fP"
.br
.ti -1c
.RI "char ** \fBoptions\fP"
.br
.ti -1c
.RI "unsigned int * \fBlength\fP"
.br
.ti -1c
.RI "int * \fBmin\fP"
.br
.ti -1c
.RI "int * \fBmax\fP"
.br
.ti -1c
.RI "int * \fBstep\fP"
.br
.ti -1c
.RI "float * \fBmin_f\fP"
.br
.ti -1c
.RI "float * \fBmax_f\fP"
.br
.ti -1c
.RI "float * \fBstep_f\fP"
.br
.ti -1c
.RI "int \fBcurrent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file menu\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int current"

.PP
Definition at line 25 of file menu\&.h\&.
.SS "unsigned int* length"

.PP
Definition at line 18 of file menu\&.h\&.
.SS "int* max"

.PP
Definition at line 20 of file menu\&.h\&.
.SS "float* max_f"

.PP
Definition at line 23 of file menu\&.h\&.
.SS "int* min"

.PP
Definition at line 19 of file menu\&.h\&.
.SS "float* min_f"

.PP
Definition at line 22 of file menu\&.h\&.
.SS "char** options"

.PP
Definition at line 17 of file menu\&.h\&.
.SS "int* step"

.PP
Definition at line 21 of file menu\&.h\&.
.SS "float* step_f"

.PP
Definition at line 24 of file menu\&.h\&.
.SS "enum \fBmenu_type\fP type"

.PP
Definition at line 16 of file menu\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team A from the source code\&.
