.TH "src/mobile_goal_intake.c" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mobile_goal_intake.c
.SH SYNOPSIS
.br
.PP
\fC#include 'mobile_goal_intake\&.h'\fP
.br
\fC#include 'partner\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBlower_intake\fP ()"
.br
.ti -1c
.RI "static void \fBraise_intake\fP ()"
.br
.ti -1c
.RI "static void \fBset_intake_motor\fP (int n)"
.br
.ti -1c
.RI "void \fBupdateIntake\fP ()"
.br
.RI "updates the mobile goal intake in teleop\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void lower_intake ()\fC [static]\fP"

.PP
Definition at line 8 of file mobile_goal_intake\&.c\&.
.PP
References set_intake_motor()\&.
.PP
Referenced by updateIntake()\&.
.PP
.nf
8                            {
9   set_intake_motor(100);
10 }
.fi
.SS "static void raise_intake ()\fC [static]\fP"

.PP
Definition at line 12 of file mobile_goal_intake\&.c\&.
.PP
References set_intake_motor()\&.
.PP
Referenced by updateIntake()\&.
.PP
.nf
12                            {
13   set_intake_motor(-100);
14 }
.fi
.SS "static void set_intake_motor (int n)\fC [static]\fP"

.PP
Definition at line 4 of file mobile_goal_intake\&.c\&.
.PP
References INTAKE_MOTOR, and set_motor_immediate()\&.
.PP
Referenced by lower_intake(), raise_intake(), and updateIntake()\&.
.PP
.nf
4                                     {
5   set_motor_immediate(INTAKE_MOTOR, n);
6 }
.fi
.SS "void updateIntake ()"

.PP
updates the mobile goal intake in teleop\&. 
.PP
Definition at line 16 of file mobile_goal_intake\&.c\&.
.PP
References get_mode(), JOY_DOWN, JOY_UP, joystickGetDigital(), lower_intake(), MAIN_CONTROLLER_MODE, MASTER, PARTNER, PARTNER_CONTROLLER_MODE, raise_intake(), and set_intake_motor()\&.
.PP
Referenced by operatorControl()\&.
.PP
.nf
16                     {
17   if(joystickGetDigital(MASTER, 7, JOY_UP) && (get_mode() == MAIN_CONTROLLER_MODE)
18   || joystickGetDigital(PARTNER, 6, JOY_UP) && get_mode() == PARTNER_CONTROLLER_MODE) {
19     raise_intake();
20   }
21   else if(joystickGetDigital(MASTER, 7, JOY_DOWN) && (get_mode() == MAIN_CONTROLLER_MODE)
22   || joystickGetDigital(PARTNER, 6, JOY_DOWN) && get_mode() == PARTNER_CONTROLLER_MODE){
23     lower_intake();
24   }
25   else set_intake_motor(0);
26 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
