.TH "include/partner.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/partner.h
.SH SYNOPSIS
.br
.PP
\fC#include 'controller\&.h'\fP
.br
\fC#include 'API\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCONTROLL_MODE\fP { \fBMAIN_CONTROLLER_MODE\fP, \fBPARTNER_CONTROLLER_MODE\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "enum \fBCONTROLL_MODE\fP \fBget_mode\fP ()"
.br
.ti -1c
.RI "void \fBupdate_control\fP ()"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCONTROLL_MODE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMAIN_CONTROLLER_MODE \fP\fP
.TP
\fB\fIPARTNER_CONTROLLER_MODE \fP\fP
.PP
Definition at line 7 of file partner\&.h\&.
.PP
.nf
7                    {
8   MAIN_CONTROLLER_MODE,
9   PARTNER_CONTROLLER_MODE
10 };
.fi
.SH "Function Documentation"
.PP 
.SS "enum \fBCONTROLL_MODE\fP get_mode ()"

.PP
Definition at line 5 of file partner\&.c\&.
.PP
References mode\&.
.PP
Referenced by update_drive_motors(), update_lifter(), and updateIntake()\&.
.PP
.nf
5                               {
6   return mode;
7 }
.fi
.SS "void update_control ()"

.PP
Definition at line 9 of file partner\&.c\&.
.PP
References JOY_LEFT, JOY_RIGHT, joystickGetDigital(), MAIN_CONTROLLER_MODE, mode, PARTNER, and PARTNER_CONTROLLER_MODE\&.
.PP
Referenced by operatorControl()\&.
.PP
.nf
9                       {
10   if(joystickGetDigital(PARTNER, 7, JOY_LEFT)) {
11     mode = MAIN_CONTROLLER_MODE;
12   } else if(joystickGetDigital(PARTNER, 7, JOY_RIGHT)) {
13     mode = PARTNER_CONTROLLER_MODE;
14   }
15 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
