.TH "polar_cord" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
polar_cord \- A struct that contains polar cordinates\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vmath\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBangle\fP"
.br
.ti -1c
.RI "float \fBmagnitue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct that contains polar cordinates\&. 


.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP
\fBAuthor:\fP
.RS 4
Chris Jerrett 
.RE
.PP

.PP
Definition at line 19 of file vmath\&.h\&.
.SH "Field Documentation"
.PP 
.SS "float angle"

.PP
Definition at line 20 of file vmath\&.h\&.
.SS "float magnitue"

.PP
Definition at line 21 of file vmath\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team A from the source code\&.
