.TH "include/potentiometer.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/potentiometer.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEG_MAX\fP   250\&.0"
.br
.ti -1c
.RI "#define \fBTICK_MAX\fP   4095\&.0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEG_MAX   250\&.0"

.PP
Definition at line 5 of file potentiometer\&.h\&.
.PP
Referenced by lifterPotentiometerToDegree()\&.
.SS "#define TICK_MAX   4095\&.0"

.PP
Definition at line 4 of file potentiometer\&.h\&.
.PP
Referenced by lifterPotentiometerToDegree()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
