.TH "include/sensor_ports.h" 3 "Tue Nov 28 2017" "Version 1.1.4" "Vex Team 9228A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/sensor_ports.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCLAW_POT\fP   1"
.br
.ti -1c
.RI "#define \fBIME_FRONT_RIGHT\fP   0"
.br
.RI "Number of integrated motor encoders Used when checking to see if all imes are plugged in\&. "
.ti -1c
.RI "#define \fBLIFTER\fP   2"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CLAW_POT   1"

.PP
Definition at line 21 of file sensor_ports\&.h\&.
.PP
Referenced by getClawTicks()\&.
.SS "#define IME_FRONT_RIGHT   0"

.PP
Number of integrated motor encoders Used when checking to see if all imes are plugged in\&. 
.PP
\fBSee also:\fP
.RS 4
\fBinit_encoders\fP 
.RE
.PP
\fBAuthor:\fP
.RS 4
Christian Desimone 
.RE
.PP
\fBDate:\fP
.RS 4
9/7/2017 
.RE
.PP

.PP
Definition at line 18 of file sensor_ports\&.h\&.
.SS "#define LIFTER   2"

.PP
Definition at line 20 of file sensor_ports\&.h\&.
.PP
Referenced by autonomous(), and getLifterTicks()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team 9228A from the source code\&.
