.TH "include/vmath.h" 3 "Sat Sep 9 2017" "Vex Team A" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/vmath.h \- Vex Specific Math Functions, includes: Cartesian to polar cordinates\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBpolar_cord\fP"
.br
.RI "A struct that contains polar cordinates\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBpolar_cord\fP \fBcartesian_to_polar\fP (float x, float y)"
.br
.RI "Function to convert x and y 2 dimensional cartesian cordinated to polar pordinates\&. "
.in -1c
.SH "Detailed Description"
.PP 
Vex Specific Math Functions, includes: Cartesian to polar cordinates\&. 


.PP
\fBAuthor:\fP
.RS 4
Christian Desimone 
.PP
Chris Jerrett 
.RE
.PP
\fBDate:\fP
.RS 4
9/9/2017 
.RE
.PP

.PP
Definition in file \fBvmath\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "struct \fBpolar_cord\fP cartesian_to_polar (float x, float y)"

.PP
Function to convert x and y 2 dimensional cartesian cordinated to polar pordinates\&. 
.PP
\fBAuthor:\fP
.RS 4
Christian Desimone 
.RE
.PP
\fBDate:\fP
.RS 4
9/8/2017
.RE
.PP
\fBParameters:\fP
.RS 4
\fIx\fP float value of the x cartesian cordinate\&. 
.br
\fIy\fP float value of the y cartesian cordinate\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
a struct containing the angle and magnitude\&. 
.RE
.PP

.PP
Definition at line 34 of file vmath\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Vex Team A from the source code\&.
